SDWebImage/SDWebImage

SDWebImage/SDWebImageDownloader.m

See @timkoma's comment at https://github.com/rs/SDWebImage/pull/1046.

Make sure callbacksForURL won't be modified

---

SDWebImage.podspec

The podspec version has not been updated in 8 months, this will allow people to update to newer changes.

Bumping podspec version

---

.travis.yml
SDWebImage/MKAnnotationView+WebCache.h
SDWebImage/MKAnnotationView+WebCache.m
SDWebImage/NSData+ImageContentType.h
SDWebImage/NSData+ImageContentType.m
SDWebImage/SDWebImageManager.h
SDWebImage/SDWebImageManager.m
SDWebImage/UIButton+WebCache.h
SDWebImage/UIButton+WebCache.m
SDWebImage/UIImageView+HighlightedWebCache.h
SDWebImage/UIImageView+HighlightedWebCache.m
SDWebImage/UIImageView+WebCache.h
SDWebImage/UIImageView+WebCache.m

Image scale for 3.0 in SDWebImageCompat

Image scale for 3.0

---

README.md

This should be `~>3.7` rather than `~>3.6`, right?

Updates Podfile entry to v3.7

---

.gitmodules

Adds the new URL to `.gitmodules`

libwebp submodule moved to another location

---

WebImage/WebImage.h

Now it compiles with `-Weverything` :tada:

A minor thing: Avoid compiler warning about the missing new line at the end of the file

---

SDWebImage/SDWebImageDownloader.m

progress callbacks now report on main thread

---

README.md

Add Swift installation tips

---

SDWebImage/SDWebImagePrefetcher.h
SDWebImage/SDWebImagePrefetcher.m

that allows it to be instantiated with any image manager

Added a new constructor to SDWebImagePrefetcher

---

Examples/SDWebImage Demo/SDWebImage Demo-Info.plist

fixed ios 9 load images caused by new App Transport Security feature

iOS 9 App Transport Security Demo Target

---

SDWebImage.xcodeproj/project.pbxproj
SDWebImage.xcodeproj/xcshareddata/xcschemes/WebImage tvOS.xcscheme
SDWebImage.xcodeproj/xcshareddata/xcschemes/WebImage.xcscheme
WebImage/Info.plist
WebImage/WebImage.h

This will fix https://github.com/rs/SDWebImage/issues/1302

Add support for tvOS

---

SDWebImage/SDWebImageDecoder.m

autorelease the bitmap context for clearing cache when memory warnings

Memory usage upgrade

---

.travis.yml
SDWebImage.podspec

Add CocoaPods support for tvOS

---

SDWebImage/UIButton+WebCache.m

Fixed sd_cancelBackgroundImageLoadForState in sd_setBackgroundImageWithURL method

Fixed #1361 sd_cancelBackgroundImageLoadForState

---

SDWebImage/SDWebImageDecoder.m

[fix] Issue #1423

---

SDWebImage/SDWebImageDownloader.h
SDWebImage/SDWebImageDownloader.m

I needed this method for a project using SDWebImage, so hopefully others will find it useful.

Added "cancelAllDownloads" method to SDWebImageDownloader.

---

README.md

...
Update readme for 1st party progress indicator support
From [this merge](https://github.com/rs/SDWebImage/pull/1217/files#diff-2cc725cd4b29e8acd64b4b01e5f82f36R382 "this merge")

Update readme for 1st party progress indicator support

---

.github/PULL_REQUEST_TEMPLATE.md

fix typo in PULL_REQUEST_TEMPLATE.md

---

README.md

Update the method name in the README to match the method name in 4.0.0.
Update the method name in README.

Small README Update For 4.0.0

---

README.md

For those who using cocoapods and gifs.

---

README.md

This pull request is just to update the CocoaPods script into README to use latest version of the library.

Update CocoaPods script to use latest version of the lib (4.0 instead of 3.8)

---

SDWebImage/SDWebImageCompat.h

spelling correction

---

SDWebImage/UIImageView+WebCache.m

Assumes that calls to sd_setAnimationImagesWithURLs should create an animation image that is always in the same order as the array specified. Currently the code populates the animation in the order that the images are returned

Fixed issue where animated image arrays could be populated out of order

---

SDWebImage/SDWebImageDownloader.m

Allow custom SDWebImageDownloaderOperation to handle HTTP redirect

---

SDWebImage/SDWebImageManager.h
SDWebImage/SDWebImageManager.m

fix 'nullable' to 'nonull'

---

SDWebImage/SDWebImageDownloaderOperation.m

This merge request fixes / reffers to the following issues: #2156 
It seems I considered too much. `-[NSURLCache cachedResponseForRequest:]` and `-[NSURLCache storeCachedResponse:forRequest:]` is not thread-safe actually. See https://developer.apple.com/documentation/foundation/nsurlcache#2317483.
Althrough after I try to figure out the reason using some reverse engineering(😅), I find that it may be thread-safe on iOS 11 but not thread-safe on iOS 8-10. Currently we do not add any system version check and use `@synchonized` to avoid our lib itself to acess the shared URLCache at the same time(But if user code call this method with the same URL without `@synchonized`, we can not help). This is easier and will not need to seperate different downloader instance to use different cache like …

Use the @synchronized to access NSURLCache and try fix the potential thread-safe problem

---

SDWebImage/SDImageCache.m

This merge request fixes / reffers to the following issues: #2224 
Just fix warning. Move that ivar into a property to make it more easy to use. Actually there is no reason to directlly use that ivar because it read-only and no write will trigger after init method, thread-safe.

Fix CLANG_WARN_OBJC_IMPLICIT_RETAIN_SELF warning

---

SDWebImage/SDWebImageManager.m

This merge request fixes / reffers to the following issues: The comment word "bellow" is confusing for beginners like me.
I think it should be "below" ^_^

Clarify the block comment in SDWebImageManager

---

SDWebImage/WebP/SDImageWebPCoder.m

There seems a bug in the **WebP Encoding** ...
Which `SDWebImageCoder` encoding always assume the input `CGImage` is RGBA8888 color mode. See the [code here](https://github.com/rs/SDWebImage/blob/5.x/SDWebImage/WebP/SDImageWebPCoder.m#L505-L509). And if you don't know what color mode is, it's the layout order of R/G/B/A pixel. See [Apple-Color Spaces and Bitmap Layout](https://developer.apple.com/library/content/documentation/GraphicsImaging/Conceptual/drawingwithquartz2d/dq_images/dq_images.html#//apple_ref/doc/uid/TP30001066-CH212-CJBHEGIB)
This will cause, for example, input `BGRA8888` image encode a wrong WebP image data, which mass up RGB color channel. This code seems original from me, but at that time I didn't realize …

Bugfix webp encode color mode

---

SDWebImage/SDImageCache.h
SDWebImage/SDImageCache.m
SDWebImage/SDImageCodersManager.m

This is just a MR during 5.x development. No need to add to 5.x milestone or tag.
Fix for `SDImageCache`'s cache options issue

Bugfix 5.x image cache options

---

SDWebImage/SDWebImageCompat.h

This merge request optimize the following issues: 
Minor optimize for dispatch_queue_async_safe

Minor optimize for dispatch_queue_async_safe

---

SDWebImage/SDImageCache.m

This merge request fixes / reffers to the following issues: #2014
This fix the 5.x's feature image transformer for `SDImageCache` bug. Since this is a bug during development, which will not mark as 5.x milestone.

fix that SDImageCache does not use transformed key to query cache when provide a transformer

---

SDWebImage/SDAnimatedImageView.h
SDWebImage/SDWebImageDownloader.m

Fix HTTP Header key field nullable

---

CHANGELOG.md
Docs/API-Diff/5.0/apidiff.css
Docs/API-Diff/5.0/apidiff.html
Docs/SDWebImage-5.0-Migration-guide.md
Docs/SDWebImage.mdj
README.md
SDWebImage.podspec
WebImage/Info.plist

Bumped the `5.x` branch version to `5.0.0-beta` -  this will be the version we release first.
Updating `CHANGELOG.md` + adding `SDWebImage-5.0-Migration-guide.md`

5.x CHANGELOG + Migration guide + version update

---

SDWebImage/SDWebImageDownloader.h
SDWebImage/SDWebImageDownloader.m
SDWebImage/SDWebImageDownloaderOperation.h
SDWebImage/UIView+WebCache.m

Discussion in #2396 .
resolved #2396 .

Replace SDWebImageDownloaderOperation with NSOperation<SDWebImageDownloaderOperationInterface> to make generic

---

Tests/Tests/SDAnimatedImageTest.m
Tests/Tests/SDTestCase.h
Tests/Tests/SDWebCacheCategoriesTests.m

This is another test case PR...Only try to fix our code coverage about new features in 5.x
To say, writing something about UI without Xcode UI Testing is not so good :)

Add the test cases for View Transition and View Indicator, both iOS && macOS

---

.github/CONTRIBUTING.md

I have recently came across https://opensource.guide/ a collection of guides for open source. There is awesome info here regarding open source projects, building communities, handling projects, ...
I want us to learn a lot from those other open source practitioners.
One part that immediately caught my eye is how we describe the contributions we want to this project. I think we can do a lot better (details here: https://opensource.guide/how-to-contribute/).
I made a few proposals in this PR, please add your thoughts.
@dreampiggy @mythodeia @skyline75489 @zhongwuzw

Added a bit more description to the way to contribute to this project.

---

SDWebImage/SDWebImageDownloaderOperation.m
SDWebImage/SDWebImageManager.m

Fixes #2427 .
We use GCD to do some progressive or decode work, it would produce some big size autorelease objects. But actually, GCD would not guarantee when to drain these objects, sometimes would leads to crash, like #2427 . So we need to add a explicitly `autoreleasepool` to  drain them timely.
PS. [Apple Documents](https://developer.apple.com/library/archive/documentation/General/Conceptual/ConcurrencyProgrammingGuide/OperationQueues/OperationQueues.html#//apple_ref/doc/uid/TP40008091-CH102-SW1)
> If your block creates more than a few Objective-C objects, you might want to enclose parts of your block’s code in an @autorelease block to handle the memory management for those objects. Although GCD dispatch queues have their …

Add autoreleasepool to release autorelease objects in advance when using GCD

---

SDWebImage/SDWebImageDownloaderOperation.m
SDWebImage/SDWebImageManager.m

Sync to `4.x`, details please see #2474 .

Add autoreleasepool to release autorelease objects in advance when using GCD for 4.x

---

CHANGELOG.md
Docs/API-Diff/5.0/apidiff.html
Docs/SDWebImage-5.0-Migration-guide.md

Update one changelog
This PR contains any update for the wiki/documentation/changelog. You can just put anything to change for these into single PR.
Everyone who need to change documentations can directlly add commit here. So we don't need to merge again and again.
Until final update is done, we can merge and release the 5.0 version (Or another beta version if we find something important to change and test)

Update the migration guide with the latest version.

---

SDWebImage/SDWebImageCompat.m

Optimize when scale = 1

---

SDWebImage/FLAnimatedImage/FLAnimatedImageView+WebCache.m

Fix FLAnimatedImageView reuse wrong image && remove GCD strong retained

---

SDWebImage/SDImageCoder.h
SDWebImage/SDImageCodersManager.h
SDWebImage/UIImageView+WebCache.h

Fix comments in code

---

SDWebImage/FLAnimatedImage/FLAnimatedImageView+WebCache.m

fix: FLAnimatedImage custom property

---

SDWebImage/SDWebImageDownloaderOperation.m

This merge request fixes / reffers to the following issues: #2500 
This is the cherry-pick PR from 5.x's #2500 . The issue exist in 4.x as well. @zhongwuzw

Fix background download 4.x

---

SDWebImage/SDWebImageManager.m

This PR contains two simple code movement, no API break or function changes.
The reason and propose to do a little code refactory, it's because that current logic inside manager become more and more huge. Seperate them into small functions instead of put them together can enhance readability and maitain cost.
Another reason, it's about the 5.0.0-beta5 's enhancement feature (or even v5.1 in the future ?) I'm doing. See #2542 . It's about the image transformer. To finish that feature, I need to do a much more changes about this manager logic (because I need to process transformer inside two part, one is cache query logic, another is store cache logic). So if this can be merged separately, the final PR can become much more …

Refactory manager logic, move code for readability and future maintain

---

SDWebImage/SDWebImageWebPCoder.m

This merge request fixes / reffers to the following issues: #2584 
This PR fix the current bug of WebP decoding, which totally ignore the ICC Profile for color management. And always using `CGColorSpaceCreateDeviceRGB`.
Note: Color management is a professional topic, if you don't understand some concept I talked here, read the documentation if you don't understand some of the concept below.
+ [Color Programming Topics](https://developer.apple.com/library/archive/documentation/Cocoa/Conceptual/DrawColor/Concepts/AboutColorSpaces.html)
+ [Best Practices for Color Management in OS X and iOS](https://developer.apple.com/library/archive/technotes/tn2313/_index.html)
The reason that cause the issue, because WebP support you to attch [ICC Profile](https://en.wikipedia.org/wiki/ICC_profile) for …

Fix that WebP image with ICC Profile does not show color correctly, should use the profile colorspace instead of device colorspace

---

SDWebImage/SDWebImageImageIOCoder.m

Fix wrong decompression scale calculation

---

SDWebImage/SDWebImageWebPCoder.m

Fixes #2592 .
Fix modify data pointer if webp image scaled down.

Fix modify data pointer if webp image scaled down

---

SDWebImage/SDWebImageWebPCoder.m

Update comments, the reason comes from https://github.com/SDWebImage/SDWebImage/pull/2627#discussion_r260592497.

Update color space filter comment when create icc profile color space

---

SDWebImage.podspec

Fixes #2625 . The reason from [comment](https://github.com/SDWebImage/SDWebImage/pull/2625/files#r260294423)

Update libwebp constraint to lower 2.0

---

SDWebImage/SDWebImageDownloader.h
SDWebImage/SDWebImageDownloader.m

Based on the discussion on #2611 it seems reasonable to contribute a convenience method for downloading images.

Define SDWebImageDownloader convenience method

---

SDWebImage/MapKit/MKAnnotationView+WebCache.m
SDWebImage/NSButton+WebCache.m
SDWebImage/UIButton+WebCache.m
SDWebImage/UIImageView+HighlightedWebCache.m

Replace the weak-strong dance code with weakify && strongify depend on pr #2647

Clean some code to weakify && strongify macros which is depened on  pr #2647

---

SDWebImage/SDImageCachesManager.h
SDWebImage/SDImageCachesManager.m
SDWebImage/SDImageCodersManager.h
SDWebImage/SDImageCodersManager.m
SDWebImage/SDImageLoadersManager.h
SDWebImage/SDImageLoadersManager.m

Guarantee thread-safe for SDImageCachesManager SDImageCodersManager SDImageLoadersManager

---

Examples/SDWebImage Demo/MasterViewController.m
SDWebImage/UIView+WebCache.m

Cancel latest image load when call cancelCurrentImageLoad

---

SDWebImage/SDImageIOCoder.m

No API changes, only contains consolidate and clean changes.

Clean and consolidate some logic code in SDImageIOCoder

---

.travis.yml
codecov.yml

Current Travis-CI code coverage, seems does not contains iOS platform. Update the script here.

Fix the Travis-CI script about code coverage submit

---

SDWebImage/SDImageAPNGCoder.m

Fixes crash for apng coder when properties are nil

---

.travis.yml
Tests/SDWebImage Tests.xcodeproj/project.pbxproj

Update Travis-CI script for uploading code coverage report to codecov.io.
Upgrade the CI Xcode to 10.1

Update the Codecov script, try to fix the report issue

---

Configs/Test-Shared.xcconfig
SDWebImage/SDWebImageDefine.m
Tests/SDWebImage Tests.xcodeproj/project.pbxproj
Tests/Tests/SDAnimatedImageTest.m
Tests/Tests/SDCategoriesTests.m
Tests/Tests/SDImageCacheTests.m
Tests/Tests/SDImageCoderTests.m
Tests/Tests/SDImageTransformerTests.m
Tests/Tests/SDUtilsTests.m
Tests/Tests/SDWebCacheCategoriesTests.m
Tests/Tests/SDWebImageDownloaderTests.m
Tests/Tests/SDWebImagePrefetcherTests.m

This PR, added many many test cases for current SDWebImage core code. Which aim to raise the code coverage to 85% (from 77%)
Including: 
+ Cache
+ View Category
+ Deocder
+ Downloader
+ Transformer
+ Utils (New)
Maybe appending more before finally merging.

Added many test case to ensure the code behavior and coverage

---

SDWebImage/SDWebImageDownloaderOperation.m

New Pull Request Checklist
So this case does not need

Delete unnecessary code

---

SDWebImage/SDAnimatedImage.h

* [x  I have run the tests and they pass
This merge request fixes / refers to the following issues: #2770
This PR just update the documentation about `SDAnimatedImage.animatedImageData`, see more in #2770

Fix the documentation about SDAnimatedImage.animatedImageData to match its behavior

---

SDWebImage/SDAnimatedImageView.m

When cell had been reused ,  we reset animated image and pause the display link.  
But `fetchQueue` is a async operation, we should check whether the displayLink had been paused when set frame to `frameBuffer` container.

Fix frame buffer bug when display link is pause

---

SDWebImage/SDMemoryCache.m

I found `weakCache` just apply to iOS/tvOS platform.
So, It's unnecessary to crate `weakCache` on macOS/watchOS platform.

Only create weak cache in iOS/tvOS platform.

---

SDWebImage/SDWebImagePrefetcher.m

Adding autoreleasepool  release `prefetchOperation` objects to reduce memory usage!

Add a autoreleasepool when prefetch many images

---

SDWebImage/Core/SDWebImageDownloader.m
Tests/Tests/SDWebImageDownloaderTests.m

This merge request fixes / refers to the following issues: #2823
@SmithJackyson For the Bug details behavior, see #2823. I just copied the description here.
> For example:(assume the downloadQueue.maxConcurrentOperationCount = 1)
there are 7 operation added into downloadQueue, the execution order will like:
> 7->6->5->4->3->2->1
> the "lastAddedOperation" is operation 7, now the operation 7 is removed because it is complete, and this time new 7 operation are added into downloadQueue, the execution order will be:
> 6->5->4->3->2->1->14->13->12->11->10->9->8
> the expected order should be 7 -> 14 -> 13 -> 12 -> 11 -> 10 -> 9 -> 8 -> 6 -> 5 -> 4 -> 3 -> 2 -> 1
I write a test case `test15DownloaderLIFOExecutionOrder` to simulate this case. And the bug exist. The only difference between the …

Fix the LIFO order inverse issue when adding new urls during previous url query

---

Tests/Tests/SDWebImageDownloaderTests.m

because of the queue dispatch delay, we should . add the next 8-14 urls just after url 7 start downloading
Fix master branch test case `test15DownloaderLIFOExecutionOrder` which introduced in #2852

Try to fix the test case `test15DownloaderLIFOExecutionOrder`

---

SDWebImage/Core/SDAnimatedImageView.m

The commit: f97c7d4d8712aa2cd383a6510c715dbeafc8c7e4 break the SDAniamtedImageView on macOS, which will have wrong rendering speed after pause and resume again.
The CVDisplayLink duration is wrong after that code changes, because the first time `CVDisplayLinkGetCurrentTime` will return the last paused timestamp, but not current timestamp. So all the things is go wrong. The duration calculation become wrong and rendering speed take really fast.

Fix the issue that SDAnimatedImageView on macOS will change the wrong duration speed when pause and resume again

---

SDWebImage/Core/UIImage+Transform.m

Fix the leak when CIImage does not contains a CGImage data (or system version less than iOS 10). Follow CoreFoundation Get/Copy rule.

Fix the leak of CIImage based UIImage for `sd_colorAtPoint`

---

SDWebImage/Core/SDWebImageManager.h

Fixed docs to show correct arguments for SDInternalCompletionBlock

---

SDWebImage/Private/SDFileAttributeHelper.m

Simplify the xattr helper method's code with modern Objective-C syntax

---

SDWebImage/Core/SDImageIOAnimatedCoder.m

This PR is split from original #2988. Already reviewed.
Need to cherry pick to 5.7.3

Fix the encoding options which does not passthrough the correct value to ImageIO

---

SDWebImage/Core/SDWebImageTransition.h
SDWebImage/Core/SDWebImageTransition.m

These APIs matches the SDWebImageSwiftUI: https://github.com/SDWebImage/SDWebImageSwiftUI/pull/116

Added the convenient transition with duration APIs

---

LICENSE

Signed-off-by: JonyFang <jony.chunfang@gmail.com>
Bumped Copyright to cover 2020

Bumped Copyright to cover 2020

---

SDWebImage/Core/SDImageCache.m

Fix 2 typos   'form' -> 'from ' in SDImageCache.m .
...

fix typos in SDImageCache

---

SDWebImage/Core/SDAnimatedImagePlayer.h
SDWebImage/Core/SDAnimatedImagePlayer.m
SDWebImage/Core/SDAnimatedImageView.h
SDWebImage/Core/SDAnimatedImageView.m
Tests/Tests/SDAnimatedImageTest.m

About [issue #3105 ](https://github.com/SDWebImage/SDWebImage/issues/3105)

Add some animation playback mode

---

SDWebImage/Core/SDImageCache.m

Shorten code indentation and improve readability

 Shorten code indentation

---

Docs/HowToUse.md
README.md

Some of the docs contained typos and missed markdown. 
I fixed them. 🙂

Fix typos and markdown in docs

---

SDWebImage/Core/SDWebImageDownloader.h

Correct document for `responseModifier` property

Correct document in SDWebImageDownloader

---

SDWebImage/Core/SDImageIOAnimatedCoder.m

This pull request aim to fix #3273

Fix image source release in iOS 15

---

SDWebImage/SDWebImageManager.m

* [ ✅] I have read and understood the [CONTRIBUTING guide](https://github.com/rs/SDWebImage/blob/master/.github/CONTRIBUTING.md)
* [ ✅] I have read the [Documentation](http://cocoadocs.org/docsets/SDWebImage/)
* [ ✅] I have searched for a similar pull request in the [project](https://github.com/rs/SDWebImage/pulls) and found none
* [ ✅] I have updated this branch with the latest master to avoid conflicts (via merge from master or rebase)
* [ ✅] I have added the required tests to prove the fix/feature I am adding
* [ ✅] I have updated the documentation (if necessary)
* [ ✅] I have run the tests and they pass
* [ ✅] I have run the lint and it passes (`pod lib lint`)
...
When the task is executed in a concurrent queue, when the …

Fix SDWebImageCombinedOperation was leak.

---

SDWebImage/Core/NSImage+Compatibility.m
SDWebImage/Core/SDImageIOAnimatedCoder.m
SDWebImage/Core/SDImageIOCoder.m
SDWebImage/Core/UIView+WebCache.m

This fix the issue talked in #https://github.com/SDWebImage/SDWebImage/pull/3262
Also, the main stream compile issue.

Fix pixel ratio thumbnail calculation

---

SDWebImage/Core/SDWebImageDownloaderOperation.m

This merge request fixes / refers to the following issues:
https://github.com/SDWebImage/SDWebImage/issues/3272
Fatal Exception: NSInvalidArgumentException
0  CoreFoundation                 0x129708 __exceptionPreprocess
1  libobjc.A.dylib                0x287a8 objc_exception_throw
2  Foundation                     0x13c234 NSZoneMalloc
3  Foundation                     0xecf4 -[_NSPlaceholderData initWithBytes:length:copy:deallocator:]
4  SDWebImage                     0x25dbc -[SDWebImageDownloaderOperation URLSession:dataTask:didReceiveData:] + 426 (SDWebImageDownloaderOperation.m:426)
5  SDWebImage                     0x22740 -[SDWebImageDownloader URLSession:dataTask:didReceiveData:] + 447 (SDWebImageDownloader.m:447)
6  FirebasePerformance            0x1b028 …

Don't copy image data

---

README.md

update URL for SDWebImageSVGKitPlugin in readme

---

SDWebImage/Core/SDImageCache.h
SDWebImage/Core/SDImageCache.m

feat: store image data

---

SDWebImage/Core/SDWebImageManager.m
SDWebImage/Core/UIImage+Transform.m

Including potential leaks and unused code

Fix the clang analyze issue

---

SDWebImage/Core/NSButton+WebCache.m

Built and noticed this warning
```
external/SDWebImage/SDWebImage/Core/NSButton+WebCache.m:152:9: warning: unknown pragma ignored [-Wunknown-pragmas]
#pragma mar - Private
^
```

Fix pragma mark typo

---

SDWebImage/Core/SDWebImageManager.m

This merge request fixes / refers to the following issues: https://github.com/SDWebImage/SDWebImage/issues/3392
This pull request provides synchronization of the getter and setter of the `cancelled` property of the `SDWebImageCombinedOperation`. This avoids data races.

Synchronise getter and setter of the cancelled property of the SDWebImageCombinedOperation

---

SDWebImage/Core/SDImageIOAnimatedCoder.m

This PR fix the Clang Analayze issue because the `CGImageCreateScaled/CGImageCreateDecoded/SDCGImageCreateCopy` may fail when out of RAM

Add the possible nullable logic check when the force-decode/copy failed

---

SDWebImage/Core/SDImageCoderHelper.m
SDWebImage/Core/SDWebImagePrefetcher.m

for-Loop does not cause untimely release, these places don't need autoreleasepool

Fix del redundant autoreleasepool

---

SDWebImage/Core/SDAnimatedImagePlayer.m

[Performance]when frame timestamp not reached, we should prefetch frame in advance for image render.

---

SDWebImage/Core/SDImageCoderHelper.m

I think this issue is a possible fix for user who faced #3417 
This is back compatible to old version's RAM behavior

Update the decode solution to allows CoreGraphics avoid using any UIKit method

---

.github/workflows/CI.yml

Updates GitHub’s action/checkout to v3 so it should be more stable (I would presume)

Bump actions/checkout to v3

---

.github/workflows/CI.yml
codecov.yml

Fix codecov upload token issue

Try to fix codecov upload issue using token

---

Examples/SDWebImage Demo.xcodeproj/project.pbxproj
Examples/SDWebImage OSX Demo/AppDelegate.m
Examples/SDWebImage OSX Demo/Base.lproj/Main.storyboard
Examples/SDWebImage OSX Demo/WindowController.h
Examples/SDWebImage OSX Demo/WindowController.m
SDWebImage/Core/SDWebImageDownloader.m
SDWebImage/Private/SDDisplayLink.h
SDWebImage/Private/SDDisplayLink.m
Tests/Tests/SDUtilsTests.m

Try to fix the SDAnimatedImageView playback speed issue in Promotion devices (iPhone Pro)

---

SDWebImage/Core/UIImage+Transform.m

Close #3502. Because the CGContext draw logic is no longer need
Also, fix small bugs that should follow Apple's [UIImageEffects](https://developer.apple.com/library/archive/samplecode/UIImageEffects/Listings/UIImageEffects_UIImageEffects_m.html#//apple_ref/doc/uid/DTS40013396-UIImageEffects_UIImageEffects_m-DontLinkElementID_9)

Fix the blur effect logic by avoid color convert and always use three box-blur methodology

---

SDWebImage/Core/SDWebImageDefine.m
SDWebImage/Private/SDImageAssetManager.m

Fix the warning of C function with no param

---

SDWebImage/Private/SDDisplayLink.m
Tests/Tests/SDImageCacheTests.m

Revert the SDDisplayLink for watchOS, fix the animated image duration bug

---

SDWebImage/Core/SDImageCache.m

This is the quick find and opt for the user reply from #3515 
There are other opt ways , need to merge one by one

Performance: Opt when multiple same URLs queried in parallel, which may cause duplicated decode and store disk operation

---

SDWebImage/Private/SDDisplayLink.m

fix #3530 
The `__bridge` is actually `unsafe_unretained` for the object, which will cause the danger pointer when:
1. main thread dealloc `SDDisplayLink` objc object
2. global thread CVDisplayLinkRef callback the `DisplayLinkCallback` and pass in the context arg
3. The context arg is now danger pointer because the pointed `SDDisplayLink` has been dealloced
Using the same solution from iOS/watchOS via SDWeakProxy

Try to fix macOS SDDisplayLink crash because of accessing the deallocated objc pointer during CVDisplayLinkRef callback

---

SDWebImage/Core/SDAnimatedImage.h
SDWebImage/Core/SDAnimatedImagePlayer.h
SDWebImage/Core/SDGraphicsImageRenderer.h
SDWebImage/Core/SDImageCoderHelper.h
SDWebImage/Core/SDWebImageDefine.h
SDWebImage/Core/SDWebImageDownloader.h
SDWebImage/Core/SDWebImageError.h
SDWebImage/Core/UIImage+Transform.h

This only update for documentation, NFC.

Update some comments to allows SwiftDocC generate better page

---

SDWebImage/Core/SDWebImageDownloaderOperation.m

Make sure the assert work
This close #3585

Add extra check for empty data during URLSession data callback

---

Configs/Module-Shared.xcconfig
README.md
SDWebImage/Core/SDAnimatedImage.m
SDWebImage/Core/SDGraphicsImageRenderer.m
SDWebImage/Core/SDImageCacheDefine.m
SDWebImage/Core/SDWebImageCompat.h
SDWebImage/Core/SDWebImageDefine.m
SDWebImage/Core/SDWebImageDownloader.m
SDWebImage/Core/SDWebImageIndicator.h
SDWebImage/Core/SDWebImageIndicator.m
SDWebImage/Private/SDImageAssetManager.m

See:
https://twitter.com/DreamingPiggy/status/1671841279205076992?s=20

(Part 1) Support to build for visionOS (no package manager support)

---

SDWebImage/Core/SDWebImageDownloader.m

Try to remove the unused NSNotification object filter, do filter by ourself

---

Examples/SDWebImage Demo/MasterViewController.m
Tests/Tests/SDTestCase.m
Tests/Tests/SDWebImageDownloaderTests.m
Tests/Tests/SDWebImageManagerTests.m
Tests/Tests/SDWebImagePrefetcherTests.m

This only effect test cases
This close #3638

[Unit test] Use placehold.co to replace the down site via.placeholder.com

---

SDWebImage/Core/SDImageIOAnimatedCoder.m

Fix the warning during clang-analyze

---

README.md

docs: add signature step to manual installation guide
remind that I dont add this in wiki
> See: https://github.com/firebase/firebase-ios-sdk/issues/12238

docs: add signature step to manual installation guide

---

.github/workflows/CI.yml

Seems need to boot the simulator firstly, other platforms does not has this issue

[github-action] Try to workaround visionOS simulator bug in unit tests

---

SDWebImage/Core/SDImageCache.m

I'm delighted to have the opportunity to contribute to SDWebImage. 
I discovered a simple spelling mistake in the code and have corrected it. Please review.

Fix typo in SDImageCache.m

---

SDWebImage/Core/UIImage+Metadata.m

This close https://github.com/SDWebImage/SDWebImageSVGCoder/issues/53
In the future we may move the test case into SDWebImage Core, currently seems no...

Fix the detection of SVGImageRep on macOS AppKit

---

SDWebImage/Private/SDDisplayLink.m

#3776
Adds an `@autoreleasepool` to the `DisplayLinkCallback` to release any objects added to an `AutoreleasePool` during the callback thereby avoiding leaking the objects until the `CVDisplayLink` is closed.
...

Add autoreleasepool to DisplayLinkCallback to release objects

---

SDWebImage/Core/SDImageTransformer.h
SDWebImage/Core/SDImageTransformer.m
SDWebImage/Core/SDWebImageManager.m
Tests/Tests/SDWebImageTestTransformer.h
Tests/Tests/SDWebImageTestTransformer.m

This is PR for feature request #3795

Allows user to directly customize preserveImageMetadata for our built-in transformers

---

.github/workflows/CD.yml
.github/workflows/CI.yml
Scripts/build-frameworks.sh
Scripts/create-xcframework.sh

Seems CD release of XCFramwork broken from v5.20.1, investigating...

ci: Fix the GitHub Action cd release
