SDWebImage/SDWebImageDownloaderOperation.m

In current version, `SDWebImageDownloaderOperation`'s notifications are dispatched on multiple threads. Considering notifications are global and supposed to be used for other purposes, dispatching on main thread seems to be better. UIApplication's `setNetworkActivityIndicatorVisible:` in `SDNetworkActivityIndicator` seems to be better to execute on main thread ,too.

Fix NSNotificationCenter dispatch on subthreads.

---

SDWebImage/SDWebImageDownloader.m
Tests/Podfile

Sometimes, the completion handlers were not executed. (Maybe, related to #1032)

fix SDWebImageDownloader threading issue

---

SDWebImage/SDImageCache.h
SDWebImage/SDImageCache.m
SDWebImage/SDWebImageDownloader.h
SDWebImage/SDWebImageDownloader.m
SDWebImage/SDWebImageDownloaderOperation.h
SDWebImage/SDWebImageDownloaderOperation.m
SDWebImage/SDWebImagePrefetcher.h
SDWebImage/SDWebImagePrefetcher.m

decodedImageWithImage category method consumes too much memory.
* Adds option to decompress images in cache and post download.
* Adds option for selecting the prefetcher queue to fetch images.

Adds option to decompress images and select prefetcher Queue

---

SDWebImage/MKAnnotationView+WebCache.m
SDWebImage/SDWebImageCompat.h
SDWebImage/SDWebImageCompat.m
SDWebImage/SDWebImageDownloaderOperation.m
SDWebImage/UIButton+WebCache.m
SDWebImage/UIImageView+HighlightedWebCache.m
SDWebImage/UIImageView+WebCache.m

It's really nice to expose a constant for the error domain so that consumers of the API can check for this if they so wish. This makes that happen.

Make a constant for the error domain

---

SDWebImage/SDImageCache.m

Method `@selector(diskImageDataBySearchingAllPathsForKey:)` sometimes called in the background thread. While method `@selector(addReadOnlyCachePath:)` called in some other threads such as main thread usually, there is an existing risk crash: `Collection <__NSArrayM: > was mutated while being enumerated`

Bug fix:Collection <__NSArrayM: > was mutated while being enumerated

---

SDWebImage/SDWebImagePrefetcher.m

If self.progressblock captures objects, captured objects remain until next time SDWebImagePrefetcher works. So clear self.progressBlock with nil value as well as completionBlock.

[Memory Issue] Clear SDWebImagePrefetcher progressBlock when it has completed

---

SDWebImage/SDImageCache.h
SDWebImage/SDImageCache.m

i need custom diskCachePath; I am subclass SDImageCache and override SDWebImageManager.createCache
using:
```swift
class BMWebImageManager: SDWebImageManager {
override init() {
super.init();
}
func createCache()->SDImageCache {
return BMImageCache.sharedImageCache();
}
}
class BMImageCache:SDImageCache{
override func makeDiskCachePath(fullNamespace: String!) -> String! {
return path;
}
}

allow override diskCachePath

---

SDWebImage/MKAnnotationView+WebCache.m
SDWebImage/SDWebImageDownloader.m
SDWebImage/UIButton+WebCache.m
SDWebImage/UIImageView+HighlightedWebCache.m
SDWebImage/UIImageView+WebCache.m

Signed-off-by: 庞博 <bopang@sohu-inc.com>

Use __typeof(self) when assigning weak reference for block.

---

SDWebImage.xcodeproj/project.pbxproj

Deployment target in the framework is set to 8.3 for some reason, which fails in Xcode 6.2. I’m assuming nothing in SDWebImage requires 8.3; I’ve set the deployment target back to 8.0.

Carthage build fails in Xcode 6.2

---

SDWebImage/SDWebImageDownloaderOperation.m

If response doesn't respondToSelector 'statusCode' the attempt to call `[((NSHTTPURLResponse *)response) statusCode] != 304` is still made and causes a crash.
This change fixes it.

Fix parenthesis to avoid crashes

---

SDWebImage/SDImageCache.h
SDWebImage/SDImageCache.m

Addresses https://github.com/rs/SDWebImage/issues/538
I just did the following test. 
Setting the limit to 40, scrolling full screen images on an iphone6. During the session my persisted allocation hovered around ~28mb 
Setting the limit to 400 created a session that grew well past 100mb until a memory pressure event

Add NSCache countLimit property

---

SDWebImage/SDWebImageManager.m

For example:
- A image download failed at first.
- I have used `SDWebImageRetryFailed` to retry download a image, now the image is ok.
- But then I use the same url to download image with no `SDWebImageRetryFailed`, it's still failed.
I think it's a bug.
:)

failedURLs can be removed at the appropriate time.

---

SDWebImage/SDImageCache.m
SDWebImage/SDWebImageManager.m

This fixes an issue with the transparency being lost when transforming and caching an image that didn't originally have an alpha channel.
This is described in more detail in #864

Fix for transparency being lost in transformed images.

---

SDWebImage/SDWebImageManager.m

This PR makes `SDWebImageManager` handle the error codes `NSURLErrorInternationalRoamingOff`, `NSURLErrorCallIsActive` or `NSURLErrorDataNotAllowed` on iOS 7 so that the URL that triggered the error isn't put in the failed URL anymore, as the URL can be tried again once the conditions are right (Since the error doesn't come from the server)

Add handling for additional error codes that shouldn't be considered a permanent failure

---

SDWebImage/SDWebImageDownloader.m

Send WebP as accepted content type only if it is enabled. In case it's not, stick with the standard formats in order to avoid the server sending us back WebP images.

add webp accepted content type only if WebP enabled

---

SDWebImage/SDWebImageCompat.h

When the code is copied within a swift module, or when a target is linked against the static library or when using from cocoapods - the debugger not longer gets broken.

Applied patch for issue #1074

---

SDWebImage/UIImage+WebP.m

webp needs to be WebP of compile will not work on case sensitive HDs

Fixing casing for #import "webp/decode.h"

---

Examples/SDWebImage Demo/MasterViewController.m
SDWebImage/SDImageCache.h
SDWebImage/SDImageCache.m
SDWebImage/SDWebImageCompat.m
SDWebImage/SDWebImageDecoder.m
SDWebImage/UIImageView+WebCache.h
SDWebImage/UIImageView+WebCache.m

added the following in my fork:
fixes #391 -> option to cache only on Disk. will replace #1130
fixes #343 -> iCloud backup Option
fixes #371 -> CGBitmapContextCreate: unsupported parameter combination
fixes #576 -> scale set to screen scale
fixes #1035 -> progress queue with dispatch_async
new feature -> activity indicator using auto layout. The activity indicator feature will replace #131

Import fixes from @mythodeia 's fork

---

SDWebImage/SDWebImageDecoder.m

Without this fix, this url: https://abs.twimg.com/sticky/default_profile_images/default_profile_3_normal.png isn't correctly decoded and the method returns a nil image.. perhaps there should be a failsafe that checks the return value and returns the input image instead if the return value is nil.

Fix unsupported colorspace issue.

---

SDWebImage/SDWebImagePrefetcher.m

Remove macro that checks for DEBUG, SD_VERBOSE, and SD_LOG_NONE
Remove calls to NSLog

SDWebImagePrefetcher: remove logging

---

SDWebImage/SDWebImageManager.m

sometimes user may pass @"" as url to sdwebimage to download, now it will also run NSURLConnection and try to download, actually there is no need to do this. I think maybe use url.absoluteString.length == 0 to avoid that url is not nil but a empty string will be better

don't to perform download if url is "" but not nil

---

SDWebImage/SDImageCache.m

As requested in #967, append the original file extension to the cached path, so that things (like QuickLook) which guess the file type based on the extension can show the image.

append the original path extension to the hash filename. closes #967

---

SDWebImage/SDWebImageDecoder.m

When downloading an image for the first time or retrieving the image from memory or disk cache, the image would be scaled correctly using SDScaledImageForKey in SDWebImageCompat, but later when it was being decompressed it would lose the correct scale. This decompression happens for all downloads, and for all memory or disk cache hits when shouldDecompressImages set to YES in SDImageCache.
For example, a 200x200px image @2x should report an image.size of 100x100pt rather than 200x200pt (which happens with this bug).
This issue was fixed years ago in f800a52f1c6eb409760bf14a5af5a636f3391100 but recently broken in 4cfb12c01cef5e4f45aa1215d38afcbb2381b594

Fixes a bug where image scale & orientation are ignored when decoding / decompressing an image.

---

SDWebImage/SDWebImageDecoder.m

This pull request fixes https://github.com/rs/SDWebImage/issues/1382 adding CMYK to the list of unsupported color space models.
Without forcing the ColorSpace to RGB when decoding the image it's not possible to add the Alpha channel.
I have also attached an example project that replicate this problem, even is trivial to reproduce, all you have to do is to try to download this image `https://d262o8ek72aza.cloudfront.net/mimg/debenhams_125x125_2.gif`.
Follows the logs showing the issue:
```
Dec 30 15:46:28  webimagetest[57562] <Error>: 
CGBitmapContextCreate: unsupported parameter combination:
8 integer bits/component;
40 bits/pixel;
CMYK color space model; kCGImageAlphaPremultipliedFirst;
640 bytes/row.
Valid parameters for CMYK color space model are:
32  bits per pixel,		 8  bits per …
```

added CMYK unsupported color space model

---

SDWebImage/UIButton+WebCache.m
SDWebImage/UIImageView+WebCache.m

If the `completedBlock` is nil, won't create a NSError Instance

Without creating a NSError instance when completedBlock is nil

---

SDWebImage/UIImage+GIF.m

We came upon an amimated gif that contained a frame that would return a nil CGImageRef, when adding this image reference to the image array, our app crashed. 
This is the bad gif:
This change skips the malformed frames and avoids the crash.

Protect against malformed frame

---

LICENSE

Here is the story.
I'd like to show the LICENSE on TVML, but since TVML is just a kind of XML, TVMLKit's DOMParser cannot parse XML special characters.  
We need to escape these characters to let DOMParser parse the strings.  
Since not every one would use TVML, I didn't escape them but deleted.

Remove XML special characters from LICENSE

---

SDWebImage/SDWebImageCompat.m

Images without a specified resolution (@2x, @3x etc) shouldn't be resized when loaded from the cache. Instead, the original size and (1x) resolution should be maintained.

Fixed changed image size (#1437)

---

SDWebImage/MKAnnotationView+WebCache.m

MKAnnotationView+WebCache partially ignores the options parameter. Options like SDWebImageAvoidAutoSetImage and SDWebImageDelayPlaceholder are very useful even in MKAnnotationView. 
This PR adds in the completion handler of method downloadImageWithURL:options:progress:complete: the same logic used in UIImageView+WebCache.

Fixed completion logic in MKAnnotationView+WebCache

---

SDWebImage/SDImageCache.m

In the iPad environment, NSCache lead to anonymous VM very high, if reaches a certain value, app will be crash. Because of SDImageCache don't clear memory when receive memory warning notification, modify define TARGET_OS_IPHONE to TARGET_OS_IOS can resolve this issue.

Repair memory release in the iPad environment

---

SDWebImage/SDWebImageManager.h

- Fixed grammar issues in the first sentence.
- Removed the second sentence since it is redundant. Moving to the front of the queue implies that they will be loaded first. Also doesn't seem necessary to inform the user that the queued images might take a while to download.

Improve documentation for SDWebImageHighPriority

---

SDWebImage/SDWebImageDownloaderOperation.h
SDWebImage/SDWebImageDownloaderOperation.m

This pull request fixes the following issues: #1291 #1318 #823 #1566
- one session per operation to preserve the ordering and priority functionalities
- removed all the runloop code that was only used to keep the operation running. I am relying on non-setting the isFinished property to keep the operation running
- todo: check deallocation, test background tasks

Replace deprecated NSURLConnection with NSURLSession

---

SDWebImage/SDWebImageManager.m

fixed crash that string property of NSURLComponents can`t use on iOS7

fixed crash on ios7 user device

---

SDWebImage/SDWebImageDownloader.m
SDWebImage/SDWebImageDownloaderOperation.h
SDWebImage/SDWebImageDownloaderOperation.m

- the URL session is created and maintained y the image downloader
- the session will be injected to each operation and it will use it to create the data task
- when delegate callbacks are called, the downloader will call the same delegate methods on the appropriate operation
- if no session is injected upon creating a operation, it will create its own session for backwards compatibility.

Updated image downloader with a single session that manages all tasks

---

SDWebImage.xcodeproj/project.pbxproj
SDWebImage/MKAnnotationView+WebCache.h
SDWebImage/MKAnnotationView+WebCache.m
SDWebImage/NSData+ImageContentType.h
SDWebImage/NSData+ImageContentType.m
SDWebImage/SDImageCache.h
SDWebImage/SDImageCache.m
SDWebImage/SDWebImageCompat.m
SDWebImage/SDWebImageDecoder.h
SDWebImage/SDWebImageDecoder.m
SDWebImage/SDWebImageDownloader.h
SDWebImage/SDWebImageDownloader.m
SDWebImage/SDWebImageDownloaderOperation.h
SDWebImage/SDWebImageDownloaderOperation.m
SDWebImage/SDWebImageManager.h
SDWebImage/SDWebImageManager.m
SDWebImage/SDWebImagePrefetcher.h
SDWebImage/SDWebImagePrefetcher.m
SDWebImage/UIButton+WebCache.h
SDWebImage/UIButton+WebCache.m
SDWebImage/UIImage+MultiFormat.h
SDWebImage/UIImage+MultiFormat.m
SDWebImage/UIImage+WebP.h
SDWebImage/UIImage+WebP.m
SDWebImage/UIImageView+HighlightedWebCache.h
SDWebImage/UIImageView+HighlightedWebCache.m
SDWebImage/UIImageView+WebCache.h
SDWebImage/UIImageView+WebCache.m
SDWebImage/UIView+WebCacheOperation.h
SDWebImage/UIView+WebCacheOperation.m

This merge request fixes #1565
- Implemented Lightweight Generics - both for Swift interoperability and for easier to read code
- Implemented Nullability according to https://developer.apple.com/swift/blog/?id=25. Decided to make explicit `nullable` and `nonnull` and not use `NS_ASSUME_NONNULL_BEGIN` so everything is clearer when read. Done so in the implementation files as well

Xcode 7 ObjC updates

---

SDWebImage/SDWebImageDownloader.m
Tests/Tests/SDWebImageManagerTests.m

This merge request add the support for downloading images that are behind an HTTP redirect.

Add support for downloading images behind redirect

---

SDWebImage/SDWebImageDownloader.h
SDWebImage/SDWebImageDownloader.m

We are using https://www.packetzoom.com - service intended to optimize loading performance of images by rerouting HTTP requests. In order for their SDK to work we need to specify their `NSURLProtocol` class in `NSURLSessionConfiguration.protocolClasses`.
This pull request exposes an initializer on `SDWebImageDownloader` allowing to pass session configuration that'll be used by the downloader.
There are no breaking changes introduced, everyone who used the only public initializer available up to now will get the same behavior as they use to.

Allow to specify NSURLSessionConfiguration for SDWebImageDownloader

---

SDWebImage/SDWebImageCompat.h

I wanted to have 0 warning coming from my Pods but SDWebImage had this warning about Macro redefinition.
In our own project we also had the dispatch_main_sync_safe macro.
by simply adding #ifndef dispatch_main_sync_safe
It will now display no warning in such specific case.

Updated dispatch_ macro in order to avoid redefinition when included as Pod

---

Examples/SDWebImage Demo/DetailViewController.m
SDWebImage/SDWebImageDownloader.h
SDWebImage/SDWebImageDownloader.m
SDWebImage/SDWebImageDownloaderOperation.m

When tableView reuses a UITableViewCell, the progress block in every cell can't recognize the status of cells, which creates a trouble for updating every cell's progressView, so adding url as callback param can help to make a unique "id".

Add url as param to progress block

---

SDWebImage/FLAnimatedImage/FLAnimatedImageView+WebCache.m

Fix FLAnimatedImageView+WebCache.m not got compiled
Because of missing SD_UIKIT definition.
This is critical to merge pull request, because animated gifs are not working at all.

Fix FLAnimatedImageView+WebCache.m not got compiled

---

SDWebImage/SDWebImageDecoder.h
SDWebImage/SDWebImageDecoder.m
SDWebImage/SDWebImageDownloader.h
SDWebImage/SDWebImageDownloaderOperation.m
SDWebImage/SDWebImageManager.h
SDWebImage/SDWebImageManager.m

Difference with the previous PR  #769:
- I have updated the scale down code, following the sample code of Apple "Large Image Downsizing". It is now perfectly safe to download large images with SDWebImage. Note: if the image is very large it can take time several seconds to get the image
Comment from the previous PR:
- I added an option to scale down large images as it is a common problem with SDWebImage.
- I chose to not add another method to SDWebImageManagerDelegate because I think we could choose the right maximum size for the library users.
Let me know what you think?
PS: I create a new pull request because I think my previous one closed can't be updated

Add an option to scale down large images on iOS

---

SDWebImage/SDWebImagePrefetcher.h

...
Updated prefetchUrls: and prefetchUrls:progress:completed: documentation to mention that any already running prefetch operations are canceled if the operation is called.

Update Prefetch Docs

---

SDWebImage/FLAnimatedImage/FLAnimatedImageView+WebCache.h

This fix the import issue when trying to use `SDWebImage/GIF` with CocoaPods.

Fix FLAnimatedImage import when using CocoaPods

---

SDWebImage/SDWebImageManager.m

we found a download error situation will add to the blacklisted when we close the network manually,and reopen the network it will not to download image.

add a network error situation

---

CHANGELOG.md

- Fixed SDImageCacheConfig class name in Changelog.md

- Fixed SDImageCacheConfig class name in Changelog.md

---

README.md

Add a missing `GIF` subspecs in README according to `SDWebImage.podspec`

Correct available subspecs in README

---

SDWebImage/SDImageCache.h
SDWebImage/SDImageCache.m

This merge request fixes / reffers to the following issues: https://github.com/rs/SDWebImage/issues/1786
As mentioned in issue above it's possible to change properties of SDImageCacheConfig. But it's not because of forward declaration. So, pull request fixes this.

SDImageCacheConfig forward declaration changed to import

---

SDWebImage/SDWebImageDownloader.h
SDWebImage/SDWebImageDownloader.m
SDWebImage/SDWebImageDownloaderOperation.m

I think the problem is that when calling `[[NSURLCache sharedURLCache] cachedResponseForRequest:`, the iOS system will do some `cache merging`. See the last line of the crash log:
` -[NSCachedURLResponse _reestablishInternalCFCachedURLResponse:] `
This implies that every time you call this method, the response caches will be reestablished. I think this is the cause of our problem. If we are caching multiple responses on different threads, then it may cause a crash.
After digging into the code, I found that this call is reductant. If we specify to use system cache, then the system will do it correctly, which means what you get in `- (void)URLSession:(NSURLSession *)session task:(NSURLSessionTask *)task …

Making image downloading cache policy more clearer

---

SDWebImage/SDImageCache.m

Added @autoreleasepool to SDImageCache.storeImage to prevent huge memory consumption when store a lot of images in series.
This what it look like when you try to store a lot of images in a loop:
And that is what it look like after @autoreleasepool added:

[bugfix] Added @autoreleasepool to SDImageCache.storeImage

---

SDWebImage/SDWebImageDownloader.m

...
Added barrier before accessing `self.URLOperations` in `SDWebImageDownloaderOperation.completionHandler`

#1909: Crash on multiple concurrent downloads when accessing self.URLOperations dictionary

---

SDWebImage/FLAnimatedImage/FLAnimatedImageView+WebCache.h
SDWebImage/MKAnnotationView+WebCache.h
SDWebImage/UIButton+WebCache.h
SDWebImage/UIImageView+HighlightedWebCache.h
SDWebImage/UIImageView+WebCache.h

This PR aims to fix #1764 and prevents potential problems. Compared with #1785, this PR takes a simple approach by adding `NS_REFINED_FOR_SWIFT` to a few methods. By carefully selecting the right methods to rename, this PR accomplishes the goal with minimum code changes and lowest redundancy.

Fix #1764 Swift naming collision

---

SDWebImage/SDWebImageDownloader.h
SDWebImage/SDWebImageDownloader.m

This merge request fixes / reffers to the following issues: #1870
Fixes issue #1870
I realized that changing the NSURLSession would require cancelling everything in the download queue, which seemed like a bigger-than-acceptable side effect for a property setter, so I went with exposing a read-only sessionConfiguration property and a createNewSessionWithConfiguration: method for the public API.

Add ability to change NSURLSessionConfiguration used by SDWebImageDownloader

---

Examples/SDWebImage OSX Demo/ViewController.m
README.md
SDWebImage/UIImage+GIF.m

macOS provide animated GIF support for built-in NSImageView and can use FLAnimatedImageView
SDWebImage 4.0-core drop the animated GIF support and use `FLAnimatedImageView` to take care of GIF. But actually macOS has a well built-in support for GIF and it's really easy to use. So it's no need to only show the first frame on macOS. Instead, use the built-in NSImage to maintain and render on NSImageView.
Fix:
When loading GIF images on macOS, showing the entire animated GIF images on NSImageView if you set `NSImageView.animates`=YES or only show the first frame of GIF images if you set `NSImageView.animates`=NO

support animated GIF on macOS

---

SDWebImage/SDWebImageCompat.m
SDWebImage/UIImage+WebP.h
SDWebImage/UIImage+WebP.m
Tests/Tests/UIImageMultiFormatTests.m

SDWebImage 4.0 add support for animated WebP images. And the UIImage+WebP category use `+[UIImage animatedImageWithImages:duration:]` to create animated image. 
Fixed Bugs:
1. While decoding animated WebP image, for each frame, you need to draw the frame image on the canvas. The older version just use `sd_rawWepImageWithData` to draw, but the `config.input.width/height` for this frame does not refer the total image size, it refer to this frame's canvas size(can be smaller than image size). So finally this will lead the final UIImage array (which is used to build animated image) have different size, cause UIImage render strange.
2. CGBitmapInfo should not use 0 for non-alpha channel, you should explicit assign it to …

#1951: Fix animated WebP decoding issue, including canvas size, the support for dispose method and the duration per frame

---

SDWebImage/SDWebImageDecoder.m

Pass NULL to CGBitmapContextCreate whenever the data param is not used later to reduce memory leak issue
As Apple Docs says for `CGBitmapContextCreate` first param `data`:
> A pointer to the destination in memory where the drawing is to be rendered. The size of this memory block should be at least (bytesPerRow*height) bytes.
> 
> Pass NULL if you want this function to allocate memory for the bitmap. This frees you from managing your own memory, which reduces memory leak issues.
Here if `CGBitmapContextCreate` success,  `destBitmapData` will contains the bitmap vector. But it not used in later procedure and not been released after line:197 `CGContextRelease(destContext)` (You need call `free(destBitmapData)`). It's better to …

Fix CGBitmapContextCreate bitmap memory leak issue

---

SDWebImage/SDWebImageDownloaderOperation.m

Fix CFRelease on NULL if CGImageSourceRef create failed, this may happen on progressive download with wrong image data
Fix CFRelease on NULL if the CGImageSourceRef create failed.
This may happen if you use progressive download and the imagedata can't be decoded to image data. The previous version only check `CGImageSourceCreateImageAtIndex` and `CGImageSourceCopyPropertiesAtIndex` but forget CFRelease need called on nonnull CFTypeRef

Fix CFRelease on NULL if CGImageSourceRef create failed

---

SDWebImage/SDWebImageCompat.h
SDWebImage/SDWebImageDownloader.h
SDWebImage/SDWebImageDownloaderOperation.h

Use `FOUNDATION_EXPORT` over `extern` to be compatible with C++.

Use FOUNDATION_EXPORT over extern

---

SDWebImage/SDWebImageCompat.h
Tests/SDWebImage Tests.xcodeproj/project.pbxproj
Tests/Tests/SDCategoriesTests.m
Tests/Tests/SDImageCacheTests.m
Tests/Tests/SDTestCase.h
Tests/Tests/SDTestCase.m
Tests/Tests/SDWebImageDecoderTests.m
Tests/Tests/SDWebImageDownloaderTests.m
Tests/Tests/SDWebImageManagerTests.m
Tests/Tests/SDWebImagePrefetcherTests.m
Tests/Tests/UIImageMultiFormatTests.m

Let's make writing test cases easier. Besides `kAsyncTestTimeout` in `SDWebImageCompat.h` just feels wrong to me.

Move common test logic to SDTestCase

---

SDWebImage/UIImage+GIF.m
SDWebImage/UIImage+WebP.m

Fix unreachable code warning because of the return and break expression in #if SD_MAC
This merge request fixes / reffers to the following issues: Fix pod lib lint warning
It's my fault, I build the project for both 4 platform targets and Xcode does report any warning (seems strange but you can also have a try). And after I integrated SDWebImage master branch to my project and build, it does not report any warning issues. So my last commit I forgot to run `pod lib lint`. But once I use `pod lib lint`, it shows `warning: code will never be executed` here. This because of that `return` and `break` expression into the `#if SD_MAC` macros. So this is an fix to get actual **0-warning**

Fix unreachable code build warning on macOS

---

Examples/SDWebImage Demo/DetailViewController.m
SDWebImage/SDWebImageDownloader.m

This merge request fixes the following issues: #1993 and refers to #1737 
- Fixed #1993 Load image with option `SDWebImageRefreshCached` get error
#1737 introduced an issue that is using `NSURLRequestReturnCacheDataDontLoad` for our cached images which makes us never download again, which is not ok when using `SDWebImageRefreshCached`.
- Fixed by reverting to the original implementation here: `NSURLRequestUseProtocolCachePolicy` vs `NSURLRequestReloadIgnoringLocalCacheData` (when `SDWebImageRefreshCached` is set).
- The docs say the `progressBlock` is called on a background queue, so when doing UI, we need to dispatch on the main queue
```
* @param progressBlock A block called while image is downloading
* @note the progress block is executed on a background queue
```

Fix request cache policy

---

Tests/Tests/SDWebImageDownloaderTests.m

Fix one block prototype with no params warning

Fix clang strict prototype warning in test

---

Tests/Tests/SDWebImageManagerTests.m

+ Add test for `SDWebImageRefreshCached ` to ensure that download image twice works.

Add a test for SDWebImageRefreshCached

---

Examples/SDWebImage Demo.xcodeproj/project.pbxproj

Xcode 9 forbid build macOS Demo project because Storyboard in macOS only supported after 10.10. We need change the deployment target to 10.10.

Update macOS Demo deployment target to 10.10 to support build on Xcode 9

---

SDWebImage/SDWebImageDownloaderOperation.m

Force acess to imageData on the same delegate queue to solve non thread safe issue. And ensure image process and completion block with non-mutable data
This PR is about #1998 
The NSMutableData `imageData` can be set to nil during `-(void)reset` call and some call in `URLSessionDelegate`. So there may be an data race that the `reset queue` and `delegate queue` is not equal, and this can cause multi-thread problem.
We can make all the access(getter and setter) to `imageData` into an single queue to ensure this. But since all the acess to `imageData` is under `NSURLSessionDelegate` call, so we just need to change that `self.imageData = nil` in to the same delegate queue. So I get the queue from the session and put that nil …

Fix SDWebImageDownloadOperation imageData multi-thread issue.

---

SDWebImage/UIButton+WebCache.m

This merge request fixes / reffers to the following issues: #1964
This is the update for #1790. Which will set UIButton's placeholer-image even if the url is nil. This behavior is what SD3.x obey but break in SD4.0

Set UIButton's placeholer-image even if the url is nil

---

SDWebImage/FLAnimatedImage/FLAnimatedImageView+WebCache.h
SDWebImage/FLAnimatedImage/FLAnimatedImageView+WebCache.m
SDWebImage/UIImage+WebP.m

This merge request fixes / reffers to the following issues: #1887 
SD now import the source webp headers with local `"webp/xxx.h"` but not global `<webp/xxx.h>`, which cause the third party application can't import webp headers if they also manually install `libwebp` dependency by building it from source and add the framework to project. We can change the webp headers to "<>" to allow search global libwebp header files preferentially, then check project header files.
This also fix an header issue in `FLAnimatedImageView+WebCache`, it use an mixed import local and global headers in header file and source file.

Fix SDWebImage v4 can not import libwebp framework's header files.

---

SDWebImage/SDWebImageDownloaderOperation.m

@bpoplauschi  Sorry to bother. In #2032 I adopt the previous behavior and add a cache image check. But there is a mistake that the early return code in line 475 will cause `[self done]` not been called. It will not mark this operation to be completed and may cause problems(such as memory leak, logic error. SD itself will be safe but our users may add KVO to this `NSOperation`. And maybe this is why all the tests is passed with no issues). So I advice to fix it as soon as possible(Maybe another little patch release?). 😢

Fix SDWebImageDownloaderOperation not call done when use SDWebImageDownloaderIgnoreCachedResponse

---

SDWebImage/SDWebImageCodersManager.h
SDWebImage/SDWebImageCodersManager.m
SDWebImage/SDWebImageGIFCoder.h
SDWebImage/SDWebImageGIFCoder.m
SDWebImage/SDWebImageImageIOCoder.h
SDWebImage/SDWebImageImageIOCoder.m
SDWebImage/UIImage+GIF.h

Give back our GIF category animation support since we now use plugin coders. 
This will not affect FLAnimatedImageView which just create the first frame.
1. Change default coders to [IOCoder, WebPCoder]
2. Add back our previous GIF decoding code, with loop count support
3. Add GIF encoding code for animation
4. Modify IOCoder for GIF format because FLAnimatedImageView need just use the first frame
Welcome back our previous `UIImage+GIF` category for animated GIF!
Because we have do refactor and separate the UIImage+XXX category with different coders. And then SD inner will not relay on that `UIImage+GIF` any methods.
This means we can keep our `FLAnimatedImageView` fast but also provide the full version `UIImage+GIF` support. …

Give back our GIF category animation support since we now use plugin coders

---

SDWebImage/SDImageCache.m
SDWebImage/SDImageCacheConfig.h
SDWebImage/SDImageCacheConfig.m

SDImageCache disk cache use the NSData to load the disk cache. Which provide a reading options such as mapped file(using virtual memory). This can improve performance and reduce memory usage in some cases. I advice to expose this options to user and let them to decide whether to use it or not(default is 0).
This is also related to #1707. After some experiment, I found that why `CGImageSourceCreateWithURL:` is faster that `[UIImage imageWithData:]:` is not so magic(See the comments in #1707 ). The `CGImageSourceCreateWithURL` will always use the mapped file while reading file URL. This feature will not break any public API, current behaviour and I think it's a easier and better ways to improve SDImageCache performance.

Allow user to provide reading options such as mapped file to improve performance in SDImageCache disk cache

---

SDWebImage/SDWebImageGIFCoder.m
SDWebImage/SDWebImageImageIOCoder.m

Add the full animated GIF encoding support. It now use NSImage's API and can share the same logic for UIImage.
Tested locally with GIF works. But maybe a test in our project is better. I'll add one later.

Add the animated GIF encoding support for SDWebImageGIFCoder on macOS(use NSImage's API)

---

SDWebImage/SDWebImageManager.m

This merge request fixes / reffers to the following issues: #1941 
This is an non thread-safe issue related to `SDWebImageManager`.
Our SDWebImageManager have a `- (void)cancel` method and it can be called through any queue. But we also have `operation.cancelBlock` this setter method during the `queryCacheOperationForKey:done:` block. 
Assume this situation:
1. Queue2: cancel method called and `self.cancelled = YES;`
2. Queue1: done block call `setCancelBlock:` setter method and `if (self.isCancelled)` passed
3. Queue1: setter method hit `_cancelBlock = nil;`
4. Queue2: cancel method hit `self.cancelBlock();`
This will cause a crash. 
Moreover, beside crash, current code has another race condition which will cause logic error. So this could not solved by simply change property attribute …

Fix #1941 by placing a lock to avoid multi-thread issue for SDWebImageCombinedOperation cancelBlock

---

Examples/SDWebImage Demo/MasterViewController.m
Tests/Podfile
Tests/Tests/SDCategoriesTests.m
Tests/Tests/SDImageCacheTests.m
Tests/Tests/SDTestCase.h
Tests/Tests/SDTestCase.m
Tests/Tests/SDWebImageDecoderTests.m
Tests/Tests/SDWebImageDownloaderTests.m
Tests/Tests/SDWebImageManagerTests.m
Tests/Tests/SDWebImagePrefetcherTests.m

- Added explicit tests for `SDWebImageGIFCoder`
- Refactored the `SDWebImageDecoderTests` a bit. Per DRY, created `verifyCoder:withLocalImageURL:isAnimatedImage:` method that will take a imageURL and a coder and will check decoding and encoding back and forth, sizes and so. Reusing this method for the static WebP image, for the animated WebP image and for the GIF.
- Switched all the tests from using https://s3.amazonaws.com/fast-image-cache/demo-images/* images which are big and sometimes fail to arrive in 5 seconds (before the test can timeout) to smaller images, basically using http://via.placeholder.com/ like http://via.placeholder.com/50x50.jpg or http://via.placeholder.com/200x200.png
This should speed up the tests a bit and also avoid some of the random failures due to timeout
- …

Fixed our tests and improved the code coverage

---

SDWebImage/SDImageCache.m

Info                    | Value                               |
-------------------------|-------------------------------------|
Platform Name           | iOS / tvOS
Platform Version        | All supported
SDWebImage Version      | e.g. 3.7.0+
Integration Method      | All supported
Xcode Version           | All supported
Repro rate              | 100%
Repro with our demo prj | With custom URL
I have been having issues with `-[SDImageCache cachedFileNameForKey:]`, returning an invalid path when the key contains dots that don't represent a path extension separator, for instance : `https://maps.googleapis.com/maps/api/staticmap?center=48.8566,2.3522&format=png&maptype=roadmap&scale=2&size=375x200&zoom=15`. This is a URL pointing to an image, but the image doesn't have any easily …

Cached image filename are sometimes generated with invalid path extensions

---

SDWebImage/NSImage+WebCache.m

Although we introduce this method to integrate FLAnimatedImage from 4.0. (This `isGIF` method is also in UIImage+GIF category). And previously used for some GIF logic but then we directly use `UIImage.images` because it's more clear and easy). And now since we do not rely on UIImage+GIF category, we can implement and open this to user.

Implements -[NSImage isGIF] method to return whether current NSImage is GIF representation.

---

SDWebImage/SDWebImageImageIOCoder.m

This merge request fixes / reffers to the following issues: #2026
We should keep previous behavior. So for shouldScaleDown options, we need to modify the original image data after we sucessfully scaled down the image.

For ImageIO coder, if the image is scaled down, then we need to modify the original image data pointer

---

SDWebImage.podspec
SDWebImage/FLAnimatedImage/FLAnimatedImageView+WebCache.m
SDWebImage/SDWebImageCodersManager.h
SDWebImage/SDWebImageGIFCoder.h
SDWebImage/SDWebImageImageIOCoder.m
SDWebImage/UIView+WebCache.h
SDWebImage/UIView+WebCache.m

This merge request fixes / reffers to the following issues:  #1901
@Silence-GitHub 
When using FLAnimatedImageView in table view cell, displaying too many
GIF images may lead to performance problem. Creating FLAnimatedImage in
global queue (not in main queue) solves the problem, and makes
scrolling smoothly.

Creating FLAnimatedImage in global queue to improve displaying gif performance

---

SDWebImage/SDWebImageDownloaderOperation.m

This merge request fixes / reffers to the following issues: #1991 
Because we don't break when we find the 1st coder that can decode progressively, we will always rewrite the `progressiveCoder ` with an `SDWebImageIOCoder` instance

Fixed create progressive coder issue

---

SDWebImage/NSData+ImageContentType.h
SDWebImage/NSData+ImageContentType.m
SDWebImage/SDWebImageCoder.h
SDWebImage/SDWebImageImageIOCoder.m

This merge request fixes / reffers to the following issues: #1853 #2038 
HEIC, Which is a type of [HEIF](https://en.wikipedia.org/wiki/High_Efficiency_Image_File_Format) with that HEVC codec. (Like WebP is used VP8 codec). This is a [ISO standard](https://www.iso.org/standard/66067.html). Attension, HEIF is a **Superset** and HEIC is specify the image use HEVC codec. HEIC image format is **Natively** support on iOS 11, tvOS 11 & macOS 10.13. But HEIF with other codec is currently not supported.
The `Natively` means all that interface does not need any changes and transparently support this image format. Apple implement this under Image/IO layer(UIKit/CoreImage -> Core Graphics ->Image/IO). So that previous version SDWebImage also be benefited from this support decoding this kind of type …

Add image format detect of HEIC (One type of HEIF which use HEVC codec). This is supported natively in iOS 11 & macOS 10.13

---

SDWebImage/NSData+ImageContentType.m

According to http://nokiatech.github.io/heif/technical.html, we shoudl also add all 4 standard brand for HEIC images.

Add all 4 standard HEIC brand file signature, ftypheic & ftypheix is for single image, ftyphevc & ftyphevx is for sequence image

---

SDWebImage/SDWebImageCompat.h
SDWebImage/UIView+WebCache.m

Add a more common macro to do current queue check
This merge request fixes / reffers to the following issues: #2092
Our use relay on the behavior that completion and set-image block should happend during one run loop without add it to the end of main queue. This means we should use `dispatch_main_async_safe` to dispatch queue when current queue is main queue.
This behavior is changed during #2047. At that time I didn't realized that completion and set-image block should immediately call when current queue is main queue. So we then do code refactor about this logic.
```objectivec
dispatch_queue_t targetQueue = shouldUseGlobalQueue ? dispatch_get_global_queue(DISPATCH_QUEUE_PRIORITY_HIGH, 0) : dispatch_get_main_queue();
dispatch_async(targetQueue, ^{});
```
In fact, we should do like this: …

Fix that completion block and set image block are called asynchronously for UIView+WebCache

---

SDWebImage/SDWebImageWebPCoder.m

because that libwebp will output last_y to zero, which means current image data is not enough to decode first stride
For WebP progressive decoding, libwebp will output last_y to zero, which means current image data is not enough to decode first stride.
So at this case, if we try to create `CGImage`, Image/IO may log an error `Demo[69478:682360] [Unknown process name] CGImageCreate: invalid image size: 1024 x 0.` And then that `CGImage` is NULL, this should return at the beginning instead of let Image/IO log this error.
To say, this will have no distinct performance affect, but a protection is better, right ? 😅

Fix WebP progressive decoding may do extra calculate

---

SDWebImage/SDWebImageImageIOCoder.m
SDWebImage/SDWebImageWebPCoder.m

let Core Animation not to call extra `aligned_malloc`
Core Animation will try to realign bitmap buffer for `CALayer` if the bitmap is not 64-bytes alignment. It will call `CA::Render::aligned_malloc` to copy your bitmap data. This will increate extra memory usage. For our WebP and Image/IO Coder, we should keep byte-aligned to enhance performance since it's really easy to do.
Tested with our demo and can reduce nearly 3MB. I also test that if we pass `bytePerRow` to 0, Core Graphics will automatically calculate and align. Maybe I can change all these args to 0 ?
References: https://github.com/path/FastImageCache#byte-alignment

Byte Alignment to 64 bytes to reduce memory usage

---

SDWebImage/SDWebImageDownloader.h
SDWebImage/SDWebImageDownloader.m
Tests/Tests/SDWebImageDownloaderTests.m

This merge request fixes / reffers to the following issues: #1944 
SDWebImageDownloader set `session` property's delegate to self. So we need to invalidate it to break retain cycle when we do not need it because `NSURLSession` hold a strong reference to delegate. 
For the shared downloader, it's OK since it's all alive during application lifecycle. But for custom instance, sadly we do not have a public API to touch that `session` itself. So we should introduce one to let user call invalidate when they use custom downloader instead of the shared one. 😹

Add a public API to allow user to invalidate URLSession used in SDWebImageDownloader to avoid memory leak on non-singleton instance

---

SDWebImage/SDWebImagePrefetcher.m

This merge request fixes / reffers to the following issues: #2110 
When user call `cancelPrefetching` from different queue, maybe that completion block in `loadImageWithURL:` are still processing. Then the index previously used will pointer to the our of range index. So we should better capture the `NSURL` object and avoid using index again.

capture currentURL instead of using index to access to avoid race condition

---

SDWebImage/FLAnimatedImage/FLAnimatedImageView+WebCache.m
SDWebImage/SDImageCache.m
SDWebImage/SDWebImageCodersManager.m
SDWebImage/SDWebImageCompat.h
SDWebImage/SDWebImageCompat.m
SDWebImage/SDWebImageDownloader.m
SDWebImage/SDWebImageDownloaderOperation.m
SDWebImage/SDWebImagePrefetcher.h
SDWebImage/UIView+WebCache.h
SDWebImage/UIView+WebCache.m

Keep the refactored code for future maintain
This merge request fixes / reffers to the following issues: #2102 
Revert previous performance enhancement #2047 
The detail information is talked on that #2102. Because of that case counld not be solved by currently implementation and design. So we have to revert code.
But our previouly refactored code and that that `SDWebImageInternalSetImageInGlobalQueueKey` can be kept for future usage and may fit some user's custom usage.

Revert changes for FLAnimatedImage performance enhancement.

---

SDWebImage/SDWebImageManager.m
SDWebImage/UIImageView+WebCache.m
SDWebImage/UIView+WebCache.h
SDWebImage/UIView+WebCache.m

Our `SDWebImageManager` have many configuration and process to use. But sometimes, we need to create a custom one instead of using the shared manager(Because it can be created with `SDImageCache` and `SDWebImageDownloader` instance, which have many cache control, network control). And this feature is indeed important for real world application usage incuding myself.
Howover, current our `UIImageView+WebCache` and `UIView+WebCache` implementation hard-coded the manager to shared manager, so if I want to create one with someting custom configuration, I need to totally create a new category for easy use and copy all the logic in `UIView+WebCache`. This is not good at all. Maybe we should provide a extra arguments to let user to …

Add a SDWebImageExternalCustomManagerKey context arguments to allow user to custom image manager for UIView category

---

SDWebImage/SDWebImageWebPCoder.m

This merge request fixes / reffers to the following issues: #2130 
Apple change that `CGDataProviderCreateWithData` function behavior, it will return a `NULL` when the `size` argument is 0. (Previously it will return a valid data provider instance with size set to 0). The previous version code is also written by me. But at that time I didn't realize this because it just works without any issue.
So now, we need to calculate the rgba size and create this data provider. :)

Fix progressive WebP decoding by creating data provider with actual data size

---

SDWebImage/SDImageCache.m

Since 4.2 coder refactor, we change that `-[SDImageCache storeImage:imageData:forKey:toDisk:completion:]` implementation to use the coder methods. When you store image with valid image but nil data to disk,  it previously will `SDImageFormatUndefined`, and finally will try to encode to PNG when image contains alpha, and JPEG when not.
Maybe this choice is better on performance, and we should also obey this behavior. Since now we have custom coder, we'd better not provide such a `SDImageFormatUndefined` arguments. It's better to copy that check logic to use PNG or JPEG format.

When store image with no data for SDImageCache, check whether it contains alpha to use PNG or JPEG format

---

Examples/SDWebImage Demo.xcodeproj/xcshareddata/xcschemes/SDWebImage OSX Demo.xcscheme
Examples/SDWebImage Demo.xcodeproj/xcshareddata/xcschemes/SDWebImage TV Demo.xcscheme
Examples/SDWebImage Demo.xcodeproj/xcshareddata/xcschemes/SDWebImage Watch Demo.xcscheme
SDWebImage.xcodeproj/xcshareddata/xcschemes/SDWebImage OSX.xcscheme
SDWebImage.xcodeproj/xcshareddata/xcschemes/SDWebImage iOS static.xcscheme
SDWebImage.xcodeproj/xcshareddata/xcschemes/SDWebImage iOS.xcscheme
SDWebImage.xcodeproj/xcshareddata/xcschemes/SDWebImage tvOS.xcscheme
SDWebImage.xcodeproj/xcshareddata/xcschemes/SDWebImage watchOS static.xcscheme
SDWebImage.xcodeproj/xcshareddata/xcschemes/SDWebImage watchOS.xcscheme
SDWebImage.xcworkspace/xcshareddata/xcschemes/SDWebImage iOS Demo.xcscheme
SDWebImage/SDWebImageGIFCoder.m
Tests/SDWebImage Tests.xcodeproj/xcshareddata/xcschemes/Tests.xcscheme

This merge request fixes / reffers to the following issues: #2142
Xcode 9.2 introduce new Clang Static Analyzer for number nil check. You should either compare number(`NSNumber, CFNumber, OSNumber`) with `nil/NULL/nullptr` for nil check, or use the `boolValue` to get the bool value to check.

Fix Clang Static Analyzer warning for number nil check from Xcode 9.2

---

SDWebImage/SDWebImageImageIOCoder.h
SDWebImage/SDWebImageImageIOCoder.m

This merge request fixes / reffers to the following issues: #2138
Because some user need to place our `SDWebImageImageIOCoder` to a higher priority, so if HEIC images can not be decoded, it should be ignored and `canDecodeFromData` should return YES to let next coder to process it. Currently we will always return YES.
I search for resources, but find there are no ways to directly get the HEIC encoding support with public API. Althrough there is a actually private global variable `gHEIF_HEVC_DecodingSupported` in Image/IO framework through decompilation(:p). But since Apple does not allow you to use private API, So I just give up and use the system version check to get it :)

Adopt the current requirement, change ImageIO coder's canDeocdeFromHEIC to actual implementation

---

SDWebImage.podspec
SDWebImage.xcodeproj/project.pbxproj
Tests/SDWebImage Tests.xcodeproj/project.pbxproj

This merge request fixes / reffers to the following issues:
Xcode 8.0 and above
iOS 8.0+ / macOS 10.10+ / tvOS 9.0+(not change) / watchOS 2.0+(not change)
I want to import APNG support for build-in coder. This is introduced during iOS 8+ and macOS 10.10+ into Image/IO framework and it;s gradually adopted by many social media app such as LINE, instagram, imgur. (And Safari 8, Chrome 59 also support this kind of animated image format).  And other image library has already support it by default such as YYImage .
Since iOS 7 support is really not the main minimum version of current iOS develop industry. After we update the minimum deployment to iOS 8, we can also have these benefits:
+ `CGImagePropertyOrientation`: which can be used in `imageOrientationFromEXIFOrientation:` and …

Upgrade deployment target version

---

SDWebImage/SDImageCache.h
SDWebImage/SDImageCache.m
SDWebImage/SDImageCacheConfig.h
SDWebImage/SDImageCacheConfig.m
SDWebImage/SDWebImageImageIOCoder.m
Tests/Tests/SDImageCacheTests.m
Tests/Tests/SDMockFileManager.h
Tests/Tests/SDMockFileManager.m

This merge request fixes / reffers to the following issues: #1898 
This is a refactor branch for Image cache. We seperate the image cache refactor commits to this branch.

Refactor storeImageDataToDisk and support writing options

---

SDWebImage/SDWebImageDownloader.h
SDWebImage/SDWebImageDownloader.m

It's obvious that we should not invalid the `URLSession` used in shared downloader, or all the image download will fail. But however, we'd better add a protect to avoid user **accidentally** call `invalidateSessionAndCancel:` on shared downloader instance :)

Avoid user accidentally invalidates the session used in shared downloader

---

SDWebImage/SDWebImageDownloaderOperation.m

This issue is faced by me that our "Downloaded image has 0 pixels" check is size equal to (0,0), which means `width and height is 0" but not "width or height is 0", this may cause some calculation wrong when the image width or height is 0(such as devided by 0 exception).

Fix that 0 pixels error should be used when width OR height is zero but not AND

---

SDWebImage/SDImageCache.m

This merge request fixes / reffers to the following issues: #1594 
The `AutoPurgeCache` which add a notification for `UIApplicationDidReceiveMemoryWarningNotification` is useless because `SDImageCache` itself has already add a notifiacation for this. And will actually call `[self.memCache removeAllObjects];`
So we do not need to trigger clean twice. :)

Remove the extra memory warning notification for AutoPurgeCache

---

SDWebImage.podspec

This merge request fixes / reffers to the following issues: #2167 
We previously have no version limit for `libwebp` dependency. However, we actually use the API(`WebPFree`) from `libwebp` 0.5.0 and our submodule version is already 0.6.0. So we should add the version limit but not leave it empty.

Update the spec file to define the dependency version for libwebp

---

SDWebImage/FLAnimatedImage/FLAnimatedImageView+WebCache.m
SDWebImage/SDImageCache.h
SDWebImage/SDImageCache.m
SDWebImage/SDWebImageImageIOCoder.m
SDWebImage/SDWebImageManager.h
SDWebImage/SDWebImageManager.m

This merge request fixes / reffers to the following issues: #2161 #2140 
This commits is from the refactor branch in 5.x.
This introduce a cache options used in `-[SDImageCache queryCacheOperationForKey:]` Because of that really tricky logic specify for `FLAnimatedImage`(Such as query the disk cache even we have memory UIImage, and call completion block synchronously)
This can also fix #2161 that `ImageIOCoder` produce a `UIAnimatedImage`, this may be some issue for rendering other than the normall `UIImage`. So we should keep `ImageIOCoder` only produce the static image instead.
Except the fix for #2161 and the feature about `SDImageCacheOptions`, this can also have a little performance benefit on `non-FLAnimatedImageView` with `AnimatedImages`. Because previously we will query the disk …

Feature query cache options

---

SDWebImage/SDImageCache.h
SDWebImage/SDImageCache.m
SDWebImage/SDImageCacheConfig.h

This merge request fixes / reffers to the following issues: #1818 
During SD 3.x -> 4.x, we remove that `diskImageExistsWithKey` sync version API and replaced with a async version API. This may because #781 deadlock
However, this change's pain is large than the gain. Sometimes we need to build something based on SDImageCache and need a sync version check. We have no choice to `force` to **simulate** a sync version API, see #1448.
For the deadlock, the reason is that previously, we expose our inner `ioQueue` to user, so if the user call `dispatch_sync` on the outside with the `ioQueue`, the deadlock occur.
But now, we do not expose that to the user, so this issue no longer happend. We should give back the sync version API.
And, I also copied some refactor code from 5.x branch. Including …

Move that `maxMemoryCost` and `maxMemoryCountLimit` to config property. Add sync version API `diskImageDataExistsWithKey`

---

Docs/HowToUse.md

Added missing param in storeImage examples

---

SDWebImage/UIView+WebCache.h
SDWebImage/UIView+WebCache.m
Tests/Tests/SDCategoriesTests.m
Tests/Tests/SDTestCase.h
Tests/Tests/SDTestCase.m
Tests/Tests/SDWebImageDownloaderTests.m
Tests/Tests/SDWebImageManagerTests.m

This merge request fixes / reffers to the following issues: #2150 #970
[NSProgress](https://developer.apple.com/library/ios/documentation/Foundation/Reference/NSProgress_Class/index.html#//apple_ref/occ/cl/NSProgress) seems a powerful class to allow you add KVO on it(If you don't use KVO, actually you don't need it at all), and can be used to make a [progress tree](https://developer.apple.com/documentation/foundation/progress#1661088)
Assume this problem: You're building a online image file browser which need to download different images and need calculate the total progress to show on the screen, you'll find it really hard to build by current progressBlock design. You need to synchonized different progressBlock by writting many ugly code, keep thread-safe(the progressBlock queue is …

Add a NSProgress property represent the image loading progress, this allow user add KVO on it for complicated logic

---

SDWebImage/UIImageView+WebCache.m

This merge request fixes / reffers to the following issues: #1209 
It seems that this weak-strong usage is wrong. The weak reference is outside the block, so it may dealloc at any time if there are no strong reference to it. However, when you call `dispatch_main_async_safe`, there is a queue dispatch and will cause much more time. This weak instance may be alive when the `loadImageWithURL` completion block called, but when dispatch to the main queue it dealloced. This is not a designed behavior. So we should keep the strong reference before call `dispatch_main_async_safe`.
Any other similar code like this should also be fixed. If you also find some like this, fix it! :)

Fix the issue that `setAnimationImagesWithURLs` weak reference may dealloc before the animated images was set

---

SDWebImage/UIImageView+WebCache.h

This merge request fixes / reffers to the following issues: #793 
This PR deprecate a wrong design API `-[UIImageView(WebCache) sd_setImageWithPreviousCachedImageWithURL:placeholderImage:options:progress:completed:]` with the alternative replacement by using the specify cache options introduced in #2162. This follow the [semver](https://semver.org/#spec-item-7) that just mark it as deprecated, the implementation is not changed and kept compatibility.
This wrong design API is introdueced from #541. It designed to solve the issue:
We always set the placeholder firstly(without `SDWebImageDelayPlaceholder`) to make it works for cell reuse. But if the memory cache missed(By many condition, for example, memory warning, user disable the memory cache), we will query the disk cache, this is a …

Deprecate the sd_setImageWithPreviousCachedImageWithURL with the specify options to achieve this usage

---

SDWebImage/SDImageCache.m

It looks like a bug but in most cases it works without any issue :)

Fix the getSize method which use the default file manager instead of current file manager

---

SDWebImage/FLAnimatedImage/FLAnimatedImageView+WebCache.m

This merge request fixes / reffers to the following issues: #2179 
It looks like that `FLAnimatedImageView` is really hard to integrate to our library. See #2179 about the effort we try to solve the performance and render problem.
The biggest problem is that `FLAnimatedImage` is not a subclass of `UIImage/NSImage`, it will cause our memory cache totally failed. So we have to query the disk cache, but this will cause render problem because it a async operation and time consuming. If we try to make it sync, it block the main queue and cause frame rate.
I'm tired of this. Just try to force store the `FLAnimatedImage` into the memory cache, solve the problem once and for all. For more detail information, see the code comments here :)

Use the associate object to store the FLAnimatedImage into memory cache, avoid blinking or UIView transaction. Tricky but may work

---

SDWebImage/SDWebImageDownloader.h
SDWebImage/SDWebImageDownloader.m
SDWebImage/SDWebImageDownloaderOperation.h
SDWebImage/SDWebImageManager.m

This merge request fixes / reffers to the following issues: #2176 #2118
It seems that our current implementation in `-[SDWebImageManager loadImageWithURL:options:progress:completed:]` may contains bug. There is a race condition that will cause the `runningOperations` not empty after all image query & download finished.
See the issue #2176 #2118, if you use a big scrollView or tableView to load the image, and then after all the images finished, check `Xcode Memory Graph`, you may see there are some `SDWebImageCombinedOperation` leave withtout dealloc. This is a big issue that because `SDWebImageCombinedOperation` keep the strong reference a `cancelBlock`, which contains `self` and the `subOperationToken`, they will also not dealloc at all. This may cause leak.
```objective-c …
```

Use the weak-strong dancing and the weak reference to manager instance to avoid the leak of runningOperations

---

SDWebImage/SDWebImageDownloader.m

This merge request fixes / reffers to the following issues: #803 
Our current `SDWebImageDownloader` use a `dispatch_queue(serial)` to acess the `URLOperations` property(Which is a `NSMutableDictionary`. This may works on normal condition. But there is a race condition that the `dispatch_queue` is called on the same queue, for example, the [NSOpertaion.completionBlock](https://developer.apple.com/documentation/foundation/operation/1408085-completionblock) may called the same queue because this is no guarantee.
> The completion block takes no parameters and has no return value.
> The exact execution context for your completion block is not guaranteed but is typically a secondary thread. Therefore, you should not use this block to do any work that requires a very specific execution context …

Use a lock instead of barrier queue to avoid dispatch_sync blocking the main queue on race condition

---

SDWebImage/SDWebImageManager.h
SDWebImage/SDWebImageManager.m

This merge request fixes / reffers to the following issues: #1818 
Some user need to access cache only without any network. This new introduces `SDWebImageFromCacheOnly` may solve their use case.
Because this can be easily implemented without any extra effect, so we can add this in 4.3.0.

Add a option SDWebImageFromCacheOnly to load the image from cache only and prevent network

---

SDWebImage/SDImageCache.h
SDWebImage/SDImageCache.m
SDWebImage/SDWebImageDownloader.h
SDWebImage/SDWebImageDownloader.m
SDWebImage/SDWebImageDownloaderOperation.h
SDWebImage/SDWebImageDownloaderOperation.m
SDWebImage/SDWebImageManager.h
SDWebImage/SDWebImageManager.m
SDWebImage/UIView+WebCache.m

This merge request fixes / reffers to the following issues: #2166
t seems that there are always some trick logic specify for some rare use case :). We should make our lib more flexible for these changes.
I think, we should use a context which should be passed from the UIView category(top) to the manager, downloader(bottom) and connect all the process. Each important API should reserve this context and we can then add some specify logic. And the good thing is that we do not need to change API again and again.
See Kingfisher's [KingfisherOptionsInfo]( https://github.com/onevcat/Kingfisher/blob/master/Sources/KingfisherOptionsInfo.swift) design. It take advantage of Swift's powerful `enum`(Which you can bind a `object`, `block` and even `multiple value` but not a simple integer) and make …

Pass the context arg from the top level to the bottom level to allow specify logic in the future

---

Examples/SDWebImage Demo/MasterViewController.m
Examples/SDWebImage OSX Demo/ViewController.m
SDWebImage.xcodeproj/project.pbxproj
SDWebImage/SDWebImageManager.h
SDWebImage/SDWebImageTransition.h
SDWebImage/SDWebImageTransition.m
SDWebImage/UIView+WebCache.h
SDWebImage/UIView+WebCache.m
WebImage/SDWebImage.h

This merge request fixes / reffers to the following issues: #2179 
This is a feature to end up our current chaos way to add view transition. And it's nearly the same feature like Kingfisher's [ImageTransition](https://github.com/onevcat/Kingfisher/blob/master/Sources/ImageTransition.swift)
Maybe user want add some custom transition after the image was load, such as `fade`, `flip` or something. Previously then can only do this by using the `completedBlock` in `sd_setImageWithURL:xxx`, and then write their own transition code.
However, this is not so easy and may cause extra cost because the correct usage to call `+[UIView transitionWithView:]` is when you change the image, so the proper time is when we use our `setImageBlock` in `UIView+WebCache.h`. If you set the transition on completion …

Feature image transition

---

Examples/SDWebImage OSX Demo/Assets.xcassets/Contents.json
Examples/SDWebImage OSX Demo/Base.lproj/Main.storyboard
Examples/SDWebImage OSX Demo/ViewController.m
SDWebImage.xcodeproj/project.pbxproj
SDWebImage/NSButton+WebCache.h
SDWebImage/NSButton+WebCache.m
SDWebImage/UIButton+WebCache.h
SDWebImage/UIButton+WebCache.m
WebImage/SDWebImage.h

This PR add a WebCache category for `NSButton` on macOS.
The `NSButton`'s design is quite different from `UIButton`, which based on its `NSButtonCell` and the image for rendering is based on by two properties called `state` and `type`. See [SettingButtonImage](https://developer.apple.com/library/content/documentation/Cocoa/Conceptual/Button/Tasks/SettingButtonImage.html#//apple_ref/doc/uid/20000088-BAJBCGCG)
In fact, this means there is not a `key-value pair` for `[UIControlState : UIImage]` like in UIKit. So if we use `#define NSButton UIButton` will cause many issue(For example, the `forState` arg is totally unused for `NSButton`).  So we'd better seperate to create a new category instead.
Thanks to that `UIView+WebCache` …

Feature nsbutton webcache

---

SDWebImage/SDImageCache.h
SDWebImage/SDImageCache.m
SDWebImage/SDImageCacheConfig.h
SDWebImage/SDImageCacheConfig.m

This merge request fixes / reffers to the following issues: #2151
This PR contains some part of #2151. Why I create this again is that this `diskImageDataExistsWithKey` is actually important for some user who need extra logic(Such as use downloader for non-UI related stuff). These user understand that sync version API should call from backrgound queue to avoid blocking main queue. And our lib itself does not use this sync version API so there is no influence to the current behavior.
This is not a API-break change and the implementation change is really simple. I know the context that why we remove that sync version API to check image exist. But that is becasuse SD 3.x expose `self.ioQueue` to public. And if user call from `self.ioQueue` with `dispatch_sync`, the deadlock occur.
But now, …

Add sync version API diskImageDataExistsWithKey and keep thread-safe. Add diskCacheWritingOptions

---

SDWebImage/SDWebImagePrefetcher.m

This merge request fixes / reffers to the following issues: #2193 
This change that wrong usage of `dispatch_queue_async_safe` in `SDWebImagePrefetcher`. Because that if we call the block immediately, this will use recursion and will reach stack overflow if the input url lists is huge. (Test that 2K+ will trigger this issue on real device. 20K+ will trigger on iPhone Simulator)

Fix the issue that prefetcher will cause stack overflow is the input urls list is huge because of recursion function call

---

SDWebImage/SDWebImageDownloader.m
SDWebImage/SDWebImageDownloaderOperation.m

This also fix the leak when response error code below iOS 10
This merge request fixes / reffers to the following issues: #1953 #1305 #1597
Our usage to let `SDWebImageDownloader` to pass `URLSessionDelegate` to the operation seems a wrong design. It's because that sometimes, the `SDWebImageDownloaderOperation` will be a nil. Because in Apple's doc about [URLSession life cycle](https://developer.apple.com/library/content/documentation/Cocoa/Conceptual/URLLoadingSystem/NSURLSessionConcepts/NSURLSessionConcepts.html). It does not means that `didCompleteWithError:` is the final call. But at that time we already removed the `SDWebImageDownloaderOperation` from the operation queue. So some of delegate methods will not do the correct way like the URLSession behavior, especially some delegate …

Ensure all the session delegate completionHandler called

---

SDWebImage/SDWebImageDownloader.m

This merge request fixes / reffers to the following issues: #961
Well. Thread-safe problem again. It seems that our library's code does not think of multi-thread environment during the development.
For `Mutable Object`, you should always use a lock because mark it as `atomic` does not solve any problem. The instance itself can be mutated from their methods. So what you can do is just to mark all the methods which may mutate the instance with lock(Dispatch queue is another way to keep thread-safe. But the queue dispatch may be slower than a lock and may also consume the GCD thread-pool resource. For simple one instance like `NSMutableDictionary`, it's not recommend to do so)
For `Immutable Object`, you should also ask yourself : "Coult the getter and setter come from different queue ?". If …

Use a lock to ensure headers mutable dictionary thread-safe

---

Examples/SDWebImage Demo/DetailViewController.m
Examples/SDWebImage Demo/MasterViewController.m
Examples/SDWebImage OSX Demo/ViewController.m
SDWebImage.xcodeproj/project.pbxproj
SDWebImage/SDWebImageIndicator.h
SDWebImage/SDWebImageIndicator.m
SDWebImage/UIView+WebCache.h
SDWebImage/UIView+WebCache.m
WebImage/SDWebImage.h

Use two protocol `SDWebImageIndicator` & `SDWebImageProgressIndicator` to make this more customizable. Implement two class about activity indicator and progress indicator for both UIKit/AppKit
Our current design for that `Image Indicator` is really hard-code and relay on `UIAcitivityIndicatorView`. Which make this not available on macOS and not customizable. I want to make our lib more flexible for user to integrate their use case. So I do refactory.
This refactory basic idea is from my previous feature `SDWebImageTransition` and the reference from [Kingfisher](https://github.com/onevcat/Kingfisher/blob/master/Sources/Indicator.swift). For a image indicator, it may be reused unlike image transition. And unlike image …

Refactor the image indicator usage for UIView category

---

SDWebImage/SDWebImageDownloaderOperation.m

This just a little improvement to the `SDWebImageDownloadOperation`. Including these:
+ Add a cache check for 304 response when using NSURLCache
+ Remove the extra cost to nil the imageData
+ Fix download operation may not marked as finished when data task create failed
+ Adopt the priority options to change URLSessionTask's priority

Improvement download operation for priority and some protect

---

SDWebImage/SDImageCache.m

This merge request fixes / reffers to the following issues: #2216 
Maybe this is a issue during #2162. For the image which the actual `UIImage` from memory cache but contains a valid `NSData`,we should treat this as a memory cache type. However, current implementation treat this as a disk cache type. So this should be fixed.

Fix that SDImageCacheQueryDataWhenInMemory should response cacheType to memory cache when the in-memory cache hit

---

SDWebImage/FLAnimatedImage/FLAnimatedImageView+WebCache.h

This merge request fixes / reffers to the following issues: #2217
In SD 4.3.0. We introduce a way to use associate object to bind `FLAnimatedImage` to `UIImage`. This allow user to "store" the FLAnimatedImage into our memory cache and fix some potential issue. At that time I mark this property `readonly` because I think user should avoid touching this in most cases.
However, some user also argue that they need to set placeholder of a `FLAnimatedImage` instance. Since `FLAnimatedImage` is not a `UIImage` subclass, they can not do this. So maybe we should just open this ability to allow write to that associate type. User now just set a `FLAnimatedImage` to `UIImage` placeholder and all things done.
This will not cause API-breaking because `readwrite` is superset of `readonly`. This is used …

Expose the read write to FLAnimatedImage associate to the UIImage to allow advanced feature like placeholder

---

Examples/SDWebImage OSX Demo/ViewController.m
SDWebImage.xcodeproj/project.pbxproj
SDWebImage/SDAnimatedImageRep.h
SDWebImage/SDAnimatedImageRep.m
SDWebImage/SDWebImageCoderHelper.h
SDWebImage/SDWebImageCoderHelper.m
SDWebImage/SDWebImageFrame.h
SDWebImage/SDWebImageGIFCoder.m
WebImage/SDWebImage.h

Well, for macOS, GIF rendering seems contains issue when the frame duration is lower than 50ms because AppKit build-in `NSImage` and `NSBitmapImageRep` use the `kCGImagePropertyGIFDelayTime` when you switch frame, so the duration is always clamped.
However, many GIF relay on the correct frame duration, and there is no options to change this to allow the correct rendering. Most GIF images from https://giphy.com could not show correctly.  It's really frustrating and you have to do many extra struff such as write you own view with Core Animation. You can see our demo's first GIF rendering, which is really slow and the duration is wrong.
Previouslly I think there is no way to fix it, however, after some research that I found we …

Create a subclass of NSBitmapImageRep to fix the GIF frame duration issue on macOS

---

SDWebImage/SDWebImageDownloaderOperation.h
SDWebImage/SDWebImageDownloaderOperation.m

Because URLSession delegate queue is a barrier queue and shared between different operation
The decoding process for image may be a time consuming process. Current design, the `SDWebImageDownloader` pass the URLSession delegate to the `SDWebImageDownloadOperation`. So each operation created by the downloader share the same delegate queue. This queue is a serial queue obviously. So the process to decode the image will be queued between different urls. This result that your download timing is become `longer` than excepted. (Frame rate is not effected)
And it's especially time-consuming for big WebP images(200ms per WebP, if we have 5 WebP images, the last one need to be queued for 1000ms). This is not necessary because our …

Decode the image in the operation level's queue instead of URLSession delegate queue

---

SDWebImage/SDImageCache.m
SDWebImage/UIView+WebCacheOperation.m

Only remove the cache when memory warning and sync back the alive instance from weak cache into cache.
This merge request fixes / reffers to the following issues: #791 #2227
See the description in #791. We can add a weak cache into memory cache for a little performance improvement on iOS/tvOS.
This is useful when the memory warning, the cache was purged. However, the image instance can be retained by other instance such as imageViews and alive. At this case, we can sync weak cache back and do not need to load from disk cache.
For example, you are showing a big imageView with a image, and a tableView contains the thumb image(Through the `UIImage` instance is the same one, only size and scale on `UIImageView` different). When memory warning and cache purged, you can also directlly get the …

Create a subclass of NSCache using a weak cache.

---

SDWebImage/SDWebImageDownloader.h
SDWebImage/SDWebImageDownloaderOperation.m

This merge request fixes / reffers to the following issues: #2230 
The `NSURLSessionTaskPriorityHigh` in Apple docs show that it's defined in Foundation. However, in iOS 8, it defined in CFNetwork.framework. If youo do not import CFNetwork manually, you will face a crash. (Sorry that our application import this framework so I didn't realize this issue in advance).
This is a bug caused by Apple. See [Radar](https://openradar.appspot.com/23956486) and [stackoverflow](https://stackoverflow.com/questions/24043532/dyld-symbol-not-found-nsurlauthenticationmethodclientcertificate-when-trying)

Fix that iOS 8 NSURLSessionTaskPriorityHigh symbol not defined in Foundation framework and cause crash

---

SDWebImage/SDWebImageDownloader.m

This merge request fixes / reffers to the following issues: 
Just a little improvement to fix potential issue (Though works well now, but it's like a wrong usage). See [Apple's doc this one](https://developer.apple.com/library/content/documentation/General/Conceptual/ConcurrencyProgrammingGuide/OperationObjects/OperationObjects.html#//apple_ref/doc/uid/TP40008091-CH101-DontLinkElementID_6) and [this one](https://developer.apple.com/library/content/documentation/General/Conceptual/ConcurrencyProgrammingGuide/OperationObjects/OperationObjects.html#//apple_ref/doc/uid/TP40008091-CH101-DontLinkElementID_5)
> Important: You should make all necessary configuration and modifications to an operation object before adding it to a queue, because once added, the operation may be run at any time, …

Follow Apple's doc, add NSOperation only after all configuration done.

---

SDWebImage/SDWebImageManager.h
SDWebImage/SDWebImageManager.m

This merge request fixes / reffers to the following issues: #2235 
Some user need the custom logic to mark one URL as failed when a error occur. Our current implementation handler all the thing through a switch case for error code. I think we can provide a delegate method to allow user to check the error information and decide whether to block this base on their business logic.
A new delegate is provided for this feature. Since this is not really common usage and we already use one `imageManager:shouldDownloadImageForURL` delegate method. I think we just do this as a delegate method instead of block.
```objective-c
- (BOOL)imageManager:(nonnull SDWebImageManager *)imageManager shouldBlockFailedURL:(nonnull NSURL *)imageURL withError:(nonnull NSError *)error;
```

Add a delegate method to control the custom logic when blocking the failed url

---

SDWebImage/SDWebImagePrefetcher.h
SDWebImage/SDWebImagePrefetcher.m
Tests/Tests/SDWebImagePrefetcherTests.m

This merge request fixes / reffers to the following issues: #1679 
Our `SDWebImagePrefetcher` seems design to use like a normal object but not to used as a `sharedPrefetcher`. Currently its implementation will cancel all the current request when you call `prefetchURLs`. So if you use the shared prefetcher somewhere to prefetch one url list, and another background queue start to prefetch another url list, all of your first request will be canceled and even the completion block will never called(This seems a bug). This is too misunderstanding and this cause some issue in my real application. Many programmers does not aware of this behavior when using.
And always, the #1679 show that some user want to cancel the specify urls because they do not want to affect the current requested urls. …

Refactor the implementation of SDWebImagePrefetcher

---

Examples/SDWebImage OSX Demo/ViewController.m
SDWebImage/SDImageCache.h
SDWebImage/SDImageCache.m
SDWebImage/SDWebImageCodersManager.h
SDWebImage/SDWebImageCodersManager.m
SDWebImage/SDWebImageDownloader.h
SDWebImage/SDWebImageDownloader.m
SDWebImage/SDWebImageDownloaderOperation.m
SDWebImage/SDWebImageGIFCoder.h
SDWebImage/SDWebImageImageIOCoder.h
SDWebImage/SDWebImageManager.h
SDWebImage/SDWebImagePrefetcher.h
SDWebImage/SDWebImageWebPCoder.h
SDWebImage/UIImage+ForceDecode.m
SDWebImage/UIImage+MultiFormat.m
Tests/Tests/SDImageCacheTests.m
Tests/Tests/SDWebImageDownloaderTests.m

In 5.x, we adopt many modern Objective-C feature and make the API more easy to for Swift user. By introducing these attribute or changes from the Objective-C side, we can make the generated Swift API more Swifty :)
The rule including these, the future contribute should also follow these rules:
+ Use property instead of `-(void)setXXX` , `-(id)XXX` to make the property available in Swift
+ Use class property with the correct name instead of `+(instanceType)sharedInstance` in singleton to make it more easy to use in Swift. The generated interface should be simple `open class var shared { get }`
+ Add all nullability annotation to avoid any `AnyObject!` implicitly unwrapped optionals(Except that `null_resettable`)
+ Add all Core …

Refactor api style

---

SDWebImage/SDWebImageManager.h
SDWebImage/SDWebImageManager.m

This merge request fixes / reffers to the following issues: #2127 #2236 #2227
Many user facing the performance of WebP decoding. Since Apple does not adopt WebP images in Apple's framework(UIKit, Image/IO), we use [libwebp](https://github.com/webmproject/libwebp) from Google to do WebP decoding. For the same image, WebP decoding spend 5x time slower than JPEG images. And it's even time-consuming when decoding Animated WebP.
So, some user argue to store the encoded image into disk cache instead of the original data from the server. Since we previously adopt the behavior to store the original data, this property is optional. Default to store the original data.
Since some user may decide to encode the image to another data, which is also time-consuming. The cache serializer block is dispatch …

Add cacheKeyFilter to allow user provide modified version of data when storing the disk cache in SDWebImageManager

---

SDWebImage/SDWebImageCodersManager.h
SDWebImage/SDWebImageCodersManager.m

The `coders` property in `SDWebImageCodersManager` declaration is wrong. Which should represent an `Array of id<SDWebImageCoder>`. But now means that `NSArray` itself conform to `SDWebImageCoder`. However, Xcode can not show this wrong as a warning...

Fix the wrong declaration of NSArray generics

---

SDWebImage/NSImage+Additions.h
SDWebImage/NSImage+Additions.m
SDWebImage/SDAnimatedImage.m
SDWebImage/SDImageCache.m
SDWebImage/SDWebImageAPNGCoder.m
SDWebImage/SDWebImageCoder.h
SDWebImage/SDWebImageCoder.m
SDWebImage/SDWebImageCoderHelper.m
SDWebImage/SDWebImageCodersManager.m
SDWebImage/SDWebImageDefine.h
SDWebImage/SDWebImageDefine.m
SDWebImage/SDWebImageDownloaderOperation.m
SDWebImage/SDWebImageGIFCoder.m
SDWebImage/SDWebImageImageIOCoder.m
SDWebImage/SDWebImageManager.m
SDWebImage/SDWebImageWebPCoder.m
SDWebImage/UIImage+Transform.m
SDWebImage/UIImage+WebCache.h
SDWebImage/UIImage+WebCache.m
Tests/Tests/SDWebImageDecoderTests.m

This merge request fixes / reffers to the following issues: #1793 #1884 #1554 
The `image scale factor` is a quite frustrating problem for image download from network. Actually, scale factor this concept is created by Apple only. It's used for Retina display but not other level. For image format, it only care about pixel resolution. So the scale factor is not stored as a metadata or something into image data. It only from filename or some other information such as Xcode's asset JSON description. Means, for image from network, we does not have the context to know its scale 😅 
For our framework's solution, we grab the scale factor from `URL` and `cache key` in the history by using `SDScaledImageForKey`. It search the string to check whether it contains `@2x, @3x`.  However, since the …

Feature scale factor

---

Examples/SDWebImage OSX Demo/ViewController.m
SDWebImage/NSImage+Additions.h
SDWebImage/NSImage+Additions.m
SDWebImage/SDAnimatedImage.m
SDWebImage/SDImageCache.m
SDWebImage/SDWebImageAPNGCoder.m
SDWebImage/SDWebImageCoder.h
SDWebImage/SDWebImageCoderHelper.h
SDWebImage/SDWebImageCoderHelper.m
SDWebImage/SDWebImageDefine.m
SDWebImage/SDWebImageGIFCoder.m
SDWebImage/SDWebImageImageIOCoder.m
SDWebImage/SDWebImageWebPCoder.m
SDWebImage/UIImage+Transform.m
Tests/Tests/SDWebImageDecoderTests.m

This merge request fixes / reffers to the following issues: See #316 
`UIImage`'s initialize method `-[UIImage initWithData:scale:]` can handle EXIF orientation correctly. It does not work on earily iOS version. But after testing, it should works for above iOS 8.
And also, `NSImage`'s `-[NSImage initWithData:]` or its category method creating by our own `-[NSImage initWithData:scale]` works for EXIF orientationi as well. So we can put these logic together.

Remove the extra calculation of image orientation for ImageIO coder & Fix macOS image orientation

---

SDWebImage/SDWebImageImageIOCoder.m
Tests/Tests/SDWebImageDecoderTests.m

This should only exclude animated images. All other images should use the display alpha info based on whether contains alpha or not to force decode
This merge request fixes / reffers to the following issues: 4cfb12c01cef5e4f45aa1215d38afcbb2381b594
It seems there is a bug in implementation for our `force decode` method. Which will be used if you prefer `shouldDecompressImages` to ON and let we do background decoding before seting image to imageView to enhance performance.
I guess this may be a mistake to exclude alpha-channel image to be force decode. Because this PR contains some knowledge about bitmap alpha info. I can describe it for people who are not familiar with it.
First, what is bitmap alpha info is the order for `R, G, B, A` pixels vector layout. (Each of it is a `uint8`, …

Fix that force decode not works for alpha-channel images.

---

SDWebImage.xcodeproj/project.pbxproj
SDWebImage/SDWebImageDefine.h
SDWebImage/SDWebImageDefine.m
SDWebImage/SDWebImageDownloader.h
SDWebImage/SDWebImageDownloader.m
SDWebImage/SDWebImageDownloaderOperation.h
SDWebImage/SDWebImageDownloaderOperation.m
SDWebImage/SDWebImageDownloaderRequestModifier.h
SDWebImage/SDWebImageDownloaderRequestModifier.m
SDWebImage/SDWebImageManager.h
SDWebImage/SDWebImageManager.m
SDWebImage/UIView+WebCacheOperation.h
SDWebImage/UIView+WebCacheOperation.m
Tests/Tests/SDWebImageDownloaderTests.m
WebImage/SDWebImage.h

This PR is a replacement for #2166. Which provide a more abstract and common usage, for not only HTTP headers modification, but also the request itself modification. And we provide more abstract information about the `download operation` and `cache operation`. This allow we hidden the detail for most common usage, but make it accessible for advacend user who really need the information such as `HTTP response`.
Through we currently have one `headerFilter` property in `SDWebImageDownloader`, this is only concentrate on the HTTP headers, however, some advacend user advice to control more information, such as HTTP Method, HTTP Body and more for their usage. So maybe we should provide a more common solution for this problem, …

Feature request modifier and response

---

Examples/SDWebImage Demo/AppDelegate.m
SDWebImage/SDImageCache.h
SDWebImage/SDImageCache.m
Tests/Tests/SDImageCacheTests.m

This merge request fixes / reffers to the following issues: #1355 
This PR is original from #2195, which seems to be a seperate part for cache refactory. So I seperate it to this one.
Some of current API like cache paths is really counter-intuitive. If I want to get the cache file name, I have to call `[SDImageCache sharedImageCache] cachePathForKey:"image.jpg" inPath:@""]`, really suck. It's looks like a internal API but should not publish to user.
Why cause this it's may because of the historic issue that we introduce one feature to let user customize the read only cache path. So we need to know both the folder and cache file name after MD5 hash. However, this should be refactor using a more common design.
And if we have custom disk cache. Current cache paths API may become a problem …

Refactor cache - Cache Path API

---

SDWebImage/SDImageCache.h
SDWebImage/SDImageCache.m
Tests/Tests/SDImageCacheTests.m
Tests/Tests/SDMockFileManager.h
Tests/Tests/SDMockFileManager.m

This merge request fixes / reffers to the following issues: #1898 
The reason to revert the PR is list in #2195 . `SDImageCache` is a image memory-disk cache. However, memory cache does not contains `error` and this is really rare for most of people.
We introduce a more abstract solution for advanced user who need this information. Just subclass to use disk cache with your `errorHandler`, then grab the error information when you need from that.
However, this just rever the `NSError` pointer, the `NSFileManager` feature will be kept, but with the more abstract `config` property instead. See more in #2195

Revert "Merge pull request #1898 from walkline/master into 5.x"

---

SDWebImage/SDImageCache.h
SDWebImage/SDImageCache.m
SDWebImage/SDImageCacheConfig.h
SDWebImage/SDImageCacheConfig.m
SDWebImage/SDWebImageDefine.h
SDWebImage/SDWebImageDownloader.h
SDWebImage/SDWebImageDownloader.m
SDWebImage/SDWebImageDownloaderConfig.h
SDWebImage/SDWebImageDownloaderConfig.m
SDWebImage/SDWebImageDownloaderOperation.h
SDWebImage/SDWebImageDownloaderOperation.m
SDWebImage/UIImage+ForceDecode.h
Tests/Tests/SDWebImageTestDownloadOperation.h

This merge request fixes / reffers to the following issues: #1927
This is about that `decompressImages` feature. We all know that what `decompressImages` will do. It actually call `sd_decodedImageWithImage:` in the background, to draw the image from Image/IO on the bitmap context, this can help to force decode the image. Then when we set this `UIImage` on the `UIImageView`, it does not cause any lag or blocking on the main queue to wait for `Core Animation` firstly decode it.
This options is good for performance, and it seems that most of application use this well. However, due to the force decode process, this will consume more memory, especially for huge images. It's a trade-off between Time & Space.
In previous SDWebImage, we have a option to enable/disable this feature. We have these: …

Use `SDWebImageAvoidDecodeImage` to allow user to control force decode feature for individual image request

---

SDWebImage.xcodeproj/project.pbxproj
SDWebImage/SDWebImageCacheKeyFilter.h
SDWebImage/SDWebImageCacheKeyFilter.m
SDWebImage/SDWebImageCacheSerializer.h
SDWebImage/SDWebImageCacheSerializer.m
SDWebImage/SDWebImageDefine.h
SDWebImage/SDWebImageDefine.m
SDWebImage/SDWebImageDownloaderRequestModifier.h
SDWebImage/SDWebImageManager.h
SDWebImage/SDWebImageManager.m
WebImage/SDWebImage.h

This PR is base on the same requirement like #2261. In 4.x, we have no `context` argument for each individual image request. Which means the `SDWebImageManager` is the central control and management for any requests. This is good for some cases, but it's not always the best choice.
However, in the real world application, this cause many issue. Assume you use `shared manager` with some URLs which need special key mapping, or need to encode downloaded image to the other format. You can not always put all the logic into a single block in shared manager, which make your code massive and hard to maintain.
You have one choice, to create another `SDWebImageManager` instance, setup all things (Cache, Downloader, cache filter block, …

Refactor custom cache serializer & headers filter for request level

---

SDWebImage.xcodeproj/project.pbxproj
SDWebImage/SDDiskCache.h
SDWebImage/SDDiskCache.m
SDWebImage/SDImageCache.h
SDWebImage/SDImageCache.m
SDWebImage/SDImageCacheConfig.h
SDWebImage/SDImageCacheConfig.m
SDWebImage/SDMemoryCache.h
SDWebImage/SDMemoryCache.m
Tests/SDWebImage Tests.xcodeproj/project.pbxproj
Tests/Tests/SDImageCacheTests.m
Tests/Tests/SDWebImageTestCache.h
Tests/Tests/SDWebImageTestCache.m
WebImage/SDWebImage.h

This merge request fixes / reffers to the following issues: #1355 #1912
This PR is original part of #2195. But since that PR contains too many changes, I seperate the custom memory & disk cache to this one.
Our `SDImageCache` works for most cases. But it's tied to `UIImage` and it's not customable at all. From some issues about cache, we can find that some people want to implement a LRU-cache algorithm for memory cache and disk cache for performance. Or have their own way to handle detailed information such as error. However, we can not easily do this unless we open the memory cache and disk cache impl to user. This need we to introduce the protobol and let user provide their desired cache such as YYCache by writing a category to conform the protocol. This can make our cache more …

Refactor cache - Support custom memory cache & disk cache

---

SDWebImage/SDImageCacheConfig.h
SDWebImage/SDImageCacheConfig.m
SDWebImage/SDWebImageDownloaderConfig.h
SDWebImage/SDWebImageDownloaderConfig.m

You can modify the property of config, but not the override the default config instance itself.
This merge request fixes / reffers to the following issues: #2282 
@bpoplauschi Maybe this is the more suitable design for config instance.
The `default config` one is readonly, which use a `dispatch_once` to create its initial value. You can only modify the property on `config` level.
The downloader & cache instance's `config` property is using `copy`. Which will keep the already created instance not accidentally get effected by later config changes to the `default config`. It's the common design like NSURLSession.

Fix the default download config & cache config to readonly

---

SDWebImage.xcodeproj/project.pbxproj
SDWebImage/SDWebImageCompat.h
SDWebImage/SDWebImageCompat.m
SDWebImage/SDWebImageDownloader.m
SDWebImage/SDWebImageDownloaderOperation.m
SDWebImage/SDWebImageError.h
SDWebImage/SDWebImageError.m
SDWebImage/SDWebImageManager.m
SDWebImage/UIView+WebCache.m
WebImage/SDWebImage.h

###Reason
This is the re-orgnization of our `NSError` error code from our framework. Since there are many many error information, but at previous version we just through a arbitrary NSError, which the error code is not correct (Some different errors share the same error code -1, and some same error contains different error code 0...).
This will cause it hard to let developer find the actual reason of error. And it's hard to process something based on the error information (For example, If the url is nil, I want to use a extra log for this. But it's hard to seperate nil url error from others)
We can create a new files contains all the error information, use `NS_ERROR_ENUM` to provide a common error code, and it's also …

Refactor error code

---

Examples/SDWebImage Demo/MasterViewController.m
SDWebImage.xcodeproj/project.pbxproj
SDWebImage/SDImageCache.h
SDWebImage/SDImageCache.m
SDWebImage/SDWebImageCache.h
SDWebImage/SDWebImageCache.m
SDWebImage/SDWebImageCachesManager.h
SDWebImage/SDWebImageCachesManager.m
SDWebImage/SDWebImageManager.h
SDWebImage/SDWebImageManager.m
Tests/Tests/SDAnimatedImageTest.m
Tests/Tests/SDImageCacheTests.m
Tests/Tests/SDWebImageManagerTests.m
Tests/Tests/SDWebImagePrefetcherTests.m
WebImage/SDWebImage.h

This merge request fixes / reffers to the following issues: #2195 
This PR is the part of original #2195. Which introduce the ability to custom web cache (Which means the cache is used for `SDWebImageManager`). It does not need user to provide a full functional cache system, but only the basic function and custom logic for the image loading system.
#2195 itself now will focus on only memory & disk cache customization for `SDImageCache` class.
Though we can custom `SDMemoryCache` or `SDDiskCache`. We may introduce more and more hack logic such as that `SDWebImageDownloaderOptions` for specify user. Maybe we can beyond this to make cache more extensible. We pass the information such as `context` and `options` to user, they decide what to do.
So this is why I introduce an another abstact …

Refactor cache - Support custom web cache

---

SDWebImage/SDWebImageCodersManager.h
SDWebImage/SDWebImageCodersManager.m

Use lock and immutable object to keep `addCoder`, `removeCoder` thread-safe.
This merge request fixes / reffers to the following issues: #1484 #2249 
This is the solution to keep thread-safe for coders manager. We use a `immutable` array to keep coders. For each `SDWebImageCoder` protocol method, we firstly grab the current coders array with lock guard, then enumerate on the reverse order (Because it's a priority queue, the last index should have the highest priority). And modify method like `addCoder:` and `removeCoder:` need a full lock to mutableCopy the coders and set it.
This can get avoid of GCD queue, and we do not need a extra `reversed` mutable array to keep priority queue. Just use the `reversedEnumerator`.

Fix the thread-safe issue for coders manager.

---

Examples/SDWebImage Demo/MasterViewController.m
SDWebImage.xcodeproj/project.pbxproj
SDWebImage/SDWebImageDownloader.h
SDWebImage/SDWebImageDownloader.m
SDWebImage/SDWebImageDownloaderOperation.m
SDWebImage/SDWebImageLoader.h
SDWebImage/SDWebImageLoader.m
SDWebImage/SDWebImageLoadersManager.h
SDWebImage/SDWebImageLoadersManager.m
SDWebImage/SDWebImageManager.h
SDWebImage/SDWebImageManager.m
Tests/SDWebImage Tests.xcodeproj/project.pbxproj
Tests/Tests/SDWebImageDownloaderTests.m
Tests/Tests/SDWebImageManagerTests.m
Tests/Tests/SDWebImageTestLoader.h
Tests/Tests/SDWebImageTestLoader.m
WebImage/SDWebImage.h

This merge request fixes / reffers to the following issues: #1970 #906 #1702 #697 
Though our project `SDWebImage`'s fundamental function is to load the image from network, cache and render in the views. Things become more and more complicated and many user may have different use case
For example, some user may use third-party cloud service such as FireBase, which provide their SDKs to retrive the image or data, so they can not be communicated with SDWebImage's total function easily without hacking. Many user also wants to load the file URL, Photos library as well, which may be a really helpful feature for beginning user. Since we can change things in 5.x, maybe we can make a more abstract layer to allow user to provide their own implementation of image loading system. But also keep the …

Feature custom image loader - Supports loader protocol

---

SDWebImage.xcodeproj/project.pbxproj
SDWebImage/SDImageCache.h
SDWebImage/SDImageCache.m
SDWebImage/SDImageCacheDefine.h
SDWebImage/SDImageCacheDefine.m
SDWebImage/SDImageCachesManager.h
SDWebImage/SDImageCachesManager.m
SDWebImage/SDWebImageManager.h
SDWebImage/SDWebImageManager.m
Tests/Tests/SDImageCacheTests.m
WebImage/SDWebImage.h

Without all `Web` prefix
Renaming all `SDWebImageCache` -> `SDImageCache`. `SDWebImageCachesManager` -> `SDImageCachesManager`
This may be my fault. Because previously I treat this `SDWebImageCache` protocol, as a `bridge` methods collection just for `SDWebImageManager` but not common usage. And currently it's actually only be used for `manager` instance though our hole framework. So I add the prefix `Web` there.
But it seems that cache is not related to Web network request. Maybe we can just remove all `Web` prefix, let user to choose to use the protocol for anything other than `WebManager`.

Fix the custom cache protocol naming

---

SDWebImage/SDImageCache.m
SDWebImage/SDImageCacheConfig.h
SDWebImage/SDImageCacheConfig.m

Which allow user to specify the correct namespace prefix by their own
This merge request fixes / reffers to the following issues: https://github.com/rs/SDWebImage/commit/a6bdba724e0ab0a8445aa23164845a6f1db054f1
In the previous renaming, we change the default image cache's prefix of namespace from `com.hackemist.SDWebImageCache.` to `com.hackemist.SDImageCache.`. However, we does not notice this will also cause the previous version of SDWebImage user will lost their cache folder because the we always `prefix` the namespace from the cache initializer arg.
We'd better provide a config for this instead of hard-coded the string into the implementation files. It's easy to do this, just using the `defaultCacheConfig` and provide a new property contains the prefix string. We recommend to use the …

Add the ability to custom the cache namespace prefix

---

SDWebImage/SDWebImageDefine.h
SDWebImage/SDWebImageDownloader.h
SDWebImage/SDWebImageDownloaderOperation.m
SDWebImage/SDWebImageError.h
SDWebImage/SDWebImageError.m
SDWebImage/SDWebImageManager.m

Our manager's implementation of that entry method `loadImageWithURL:options:context:progress:completed` seems contains too much logic. Especailly after we introduce the `Custom Cache` & `Custom Loader` protocol.
But recentlly I'm doing something about Photos framework loader. Photos framework 's best practice is to load the image without cache because they are all in the local disk files.
We alrady have a `SDWebImageFromCacheOnly` to only load image from cache. However, there are no equivalent options like `SDWebImageFromLoaderOnly`. If you don't want any cache query, you have no ways to do it from our current API for this.
However, if I want to implement this feauture (Since this will not break API). I will find it really …

Refactor manager logic - Also suppoort ignore cache query

---

SDWebImage/SDImageCache.h

`-[SDImageCache storeImageDataToDisk:forKey:]` when call it from the `ioQueue`, will deadlock
There are some problems in this description
Or using marco like SDWebImageCompat avoid deadlocks
```
#ifndef dispatch_queue_sync_safe
#define dispatch_queue_sync_safe(queue, block)\
if (strcmp(dispatch_queue_get_label(DISPATCH_CURRENT_QUEUE_LABEL), dispatch_queue_get_label(queue)) == 0) {\
block();\
} else {\
dispatch_sync(queue, block);\
}
#endif
```

Fix function storeImageDataToDisk description

---

SDWebImage/SDWebImageImageIOCoder.m

This is the bug in early version of Image/IO framework, but now it's already been fixed and duplicated process impact performance
This merge request fixes / reffers to the following issues: #1481
There seems a hack code to fix the issue about that `Workaround for iOS anamorphic image`. Which draw the image during progressive image decoding from `CGImageSourceCreateImageAtIndex`, into a bitmap context to `stretch` the full height. The original code is from [here](https://cocoaintheshell.whine.fr/2011/05/progressive-images-download-imageio/)
However, this fix seems only useful for the early version of iOS firmware and Image/IO framework. During my test, Image/IO works well for iOS 8 and above. The returned image always and already contains transparent space to fill the unfinished height of …

Remove the duplicated process to force decode (draw on bitmap context) in Image/IO's progressive decoding.

---

Examples/SDWebImage Demo/DetailViewController.m
Examples/SDWebImage OSX Demo/ViewController.m
SDWebImage/SDWebImageDefine.h
SDWebImage/SDWebImageDownloader.h
SDWebImage/SDWebImageDownloader.m
SDWebImage/SDWebImageDownloaderOperation.m
SDWebImage/SDWebImageLoader.h
SDWebImage/SDWebImageManager.h
SDWebImage/SDWebImageManager.m
SDWebImage/UIView+WebCache.h
Tests/Tests/SDAnimatedImageTest.m
Tests/Tests/SDWebImageDownloaderTests.m

This merge request fixes / reffers to the following issues: 
I don't know whether this renaming is quite suitable. (Change options will break current API...Make user hard to migrate..I think users are our treasure)
But since now we have `SDWebImageLoader` protocol. And I'm build Photos framework extension using SDWebImage this feature. I accidentally run into this `ProgressiveDownload` options. I think we'd better renaming `SDWebImageProgressiveDownload` into `SDWebImageProgressiveLoad`. Which is more clear. And after change, that `SDWebImageDownloaderProgressiveDownload` downloader options will also express more clearly....
The [Photos framework extension](https://github.com/dreampiggy/SDWebImage-Photos) is almost done. Which currently point to 5.x branch of SD. That framework's naming …

Renaming progressive load

---

SDWebImage.xcodeproj/project.pbxproj
SDWebImage/NSImage+Compatibility.m
SDWebImage/SDAnimatedImage.m
SDWebImage/SDImageCache.m
SDWebImage/SDImageCacheDefine.m
SDWebImage/SDImageCoderHelper.h
SDWebImage/SDImageCoderHelper.m
SDWebImage/SDImageFrame.h
SDWebImage/SDImageFrame.m
SDWebImage/SDWebImageAPNGCoder.m
SDWebImage/SDWebImageCoder.h
SDWebImage/SDWebImageGIFCoder.m
SDWebImage/SDWebImageImageIOCoder.m
SDWebImage/SDWebImageLoader.m
SDWebImage/UIImage+ForceDecode.m
SDWebImage/WebP/SDWebImageWebPCoder.m
WebImage/SDWebImage.h

This merge request fixes / reffers to the following issues: #2291 
Renaming `SDWebImageFrame` to `SDImageFrame`.
Renaming `SDWebImageCoderHelper` to `SDImageCoderHelper`.
These class should obey the naming rule. 
> No Web-Cache manager related, and no `NSURL` related class should named without `Web` prefix. Class which represent something about framework itself should prefix hole `SDWebImage` even if not image related.

Renaming SDWebImageFrame & SDWebImageCoderHelper

---

SDWebImage/SDWebImageImageIOCoder.m
Tests/Tests/SDWebImageDecoderTests.m

This merge request fixes / reffers to the following issues: #2271  
This PR is cherry-picked from #2271, which already merged in 5.x branch. This fix the extra decoding cost to check EXIF orientation.
Tested with iOS 7 device as well, now `+[UIImage imageWithData:]` can parse the EXIF orientation to image orientation, no need to manually check and using `+[UIImage imageWithCGImage:scale:orientation:]`

Remove the extra calculation of image orientation for ImageIO coder

---

SDWebImage/SDImageCache.h
SDWebImage/SDImageCache.m
SDWebImage/SDWebImageDefine.h

This can help for web cache manager to avoid flashing during cell reusing.
This merge request fixes / reffers to the following issues: #2255
This PR is original from the #2255. Which provide the advanced control for cache query behavior, including whether we should query memory/disk cache synchronously/asynchronously.
This feature is not useful for most people, however, for some use case who need to ensure image is load from disk without any flashing, they may consider to use `SDImageCacheQueryDiskDataSync`. For user who need the image data to decide to render, such as our old solution `FLAnimatedImageView`, they may decide to use `SDImageCacheQueryMemoryData` or `SDImageCacheQueryMemoryDataSync`.
This actual can be a refactory for our current `SDWebImageQueryDataWhenInMemory` & …

Add options to specify query cache sync/async behavior

---

SDWebImage/SDWebImageTransition.h
SDWebImage/SDWebImageTransition.m

This merge request fixes / reffers to the following issues: #2310 
We introduce [image transition](https://github.com/rs/SDWebImage/wiki/Advanced-Usage#image-transition-430) feature from 4.3. Now some user suggest that we should allow user interaction during image transition animation. See #2310
For example, if we don't allow user interaction, during cell scrolling and you touch the cell to enter new page, this touch will be ignoed. Though you can manually set `UIViewAnimationOptionAllowUserInteraction`, but since it's a **convenient method** and most of people using image transition for tableView cell. I agree to set this options as default one.
So we just add all convenient image transition with the `UIViewAnimationOptionAllowUserInteraction` options. Simple changes :)

Add `UIViewAnimationOptionAllowUserInteraction` as default options for convenient image transition

---

SDWebImage/SDWebImageWebPCoder.m

Detect the current CGImage color mode, covert the all other case to RGB888/RGBA8888 using vImage
This merge request fixes / reffers to the following issues: #2311 
This MR is cherry-picked from #2311. Which fix the WebP encoding feature for non-RGBA8888 image.
For more detail information, see #2311

Fix WebP Encoding only works for RGBA8888 CGImage but not other color mode

---

SDWebImage/NSImage+Compatibility.m
SDWebImage/SDAnimatedImageView.m

This PR fix the image orientation during progressive decoding & SDAnimatedImage on the macOS :)
This will not add to milestone because it's just a bugfix during new feature development for 5.x

Fix the progressive decoding bug on macOS. Including image orientation & SDAnimatedimageView

---

SDWebImage/UIImage+WebCache.m

This PR fix the 5.x development bug that `UIImage+WebCache` category header files mark this available for iOS/tvOS/watchOS/macOS. But the implementation files does not cover watchOS. So there will be a runtime exception when using. Still stupid bug...:)

Fix that watchOS UIImage+WebCache does not mark as available and cause crash

---

SDWebImage/SDWebImageManager.m

This merge request reffers to the following issues: https://github.com/rs/SDWebImage/issues/2267
Replace `@synchronized` with `pthread_mutex_t` & `dispatch_semaphore_t` in `SDWebImageManager` to improve lock performance.
Two locks are updated:
1. For `failedURLs`, `dispatch_semaphore_t` is used, just likes the case in `SDWebImageDownloader`.
2. For `runningOperations`, `pthread_mutex_t` is used instead, since it requires recursiveness, which is not support by `dispatch_semaphore_t` .

Replace @synchronized with dispatch_semaphore_t in SDWebImageManager

---

SDWebImage/FLAnimatedImage/FLAnimatedImageView+WebCache.h
SDWebImage/FLAnimatedImage/FLAnimatedImageView+WebCache.m

It makes users to set optimal frame cache size of FLAnimatedImage after image load.
This merge request fixes / reffers to the following issues: #2308 
Thir PR is original from #2308. Seems some user need the extra options to feed `FLAnimatedImage`'s initializer.
This solution is kept compatibility in 4.x. In 5.x, this will using `SDWebImageContext` solution instead of imageView level config. And `FLAnimatedImage` plugin code will move to another repo called [SDWebImageFLPlugin](https://github.com/dreampiggy/SDWebImageFLPlugin).

Add optimalFrameCacheSize && predrawingEnabled options for FLAnimatedImage

---

Examples/SDWebImage Watch Demo Extension/InterfaceController.m
SDWebImage/SDWebImageCompat.h
SDWebImage/UIImageView+WebCache.h
SDWebImage/UIImageView+WebCache.m
SDWebImage/UIView+WebCache.h
SDWebImage/UIView+WebCache.m
SDWebImage/UIView+WebCacheOperation.h
SDWebImage/UIView+WebCacheOperation.m

This merge request fixes / reffers to the following issues: #2331 #1070
This PR is cherry-picked from the #2331. Which is already been merged in 5.x branch. However, since this feature is not a API-breaking change, and it's not hard to merge to 4.x as well. So I think we can adopt it to 4.x.
And, after some consideration, I suggest that the next version we can upgrade a minor version, to 4.4.0. Why do so, may because next version we contains 3 feature PR (#2308, #2281 and this one), we also change a little behavior from previous version (#2315), and many historical bugfix. Some changes may not so obvious, but may impact the user usage. So I guess a minor upgrade version should be more acceptable to follow sem-version.

Add the support for watchOS to use View Category method (sd_setImageWithURL:) on WKInterfaceImage

---

SDWebImage/SDWebImageWebPCoder.m

Using the correct bitmapInfo to avoid `CGImageCreate` failed when the WebP image contains no alpha channel
This merge request fixes / reffers to the following issues: #2347 
Fix the WebP (including Animated WebP) decoding issue for non-alpha channel image. This is because that the wrong arg using in `CGImageCreate` method to create bitmap image. It's not been founded because the previous iOS realease seems not cause any issue. Only happend on iOS 12.
However, that `CGBitmapContextCreate` does not support RGB888 on iOS (only on macOS). So we'd better using RGBX8888 as usual to create a non-alpha channel bitmap context.
PS: For non-alpha image, using 3-channel `RGB888` can save 1/4 memory usage than using a 4-channel `RGBX8888`, so we'd better using that unless the API does not support.

Fix that WebP (including Animated WebP) decoding issue on iOS 12.

---

SDWebImage.xcodeproj/project.pbxproj
SDWebImage/FLAnimatedImage/FLAnimatedImageView+WebCache.h
SDWebImage/FLAnimatedImage/FLAnimatedImageView+WebCache.m
SDWebImage/MapKit/MKAnnotationView+WebCache.h
SDWebImage/MapKit/MKAnnotationView+WebCache.m
SDWebImage/NSButton+WebCache.h
SDWebImage/NSButton+WebCache.m
SDWebImage/SDAnimatedImageView+WebCache.h
SDWebImage/SDAnimatedImageView+WebCache.m
SDWebImage/SDImageLoader.h
SDWebImage/SDImageLoader.m
SDWebImage/SDImageLoadersManager.h
SDWebImage/SDImageLoadersManager.m
SDWebImage/SDWebImageDownloader.h
SDWebImage/SDWebImageDownloader.m
SDWebImage/SDWebImageDownloaderOperation.m
SDWebImage/SDWebImageManager.h
SDWebImage/SDWebImageManager.m
SDWebImage/UIButton+WebCache.h
SDWebImage/UIButton+WebCache.m
SDWebImage/UIImageView+HighlightedWebCache.h
SDWebImage/UIImageView+HighlightedWebCache.m
SDWebImage/UIImageView+WebCache.h
SDWebImage/UIImageView+WebCache.m
SDWebImage/UIView+WebCache.h
SDWebImage/UIView+WebCache.m
Tests/Tests/SDWebImageDownloaderTests.m
Tests/Tests/SDWebImageTestLoader.h
Tests/Tests/SDWebImageTestLoader.m
WebImage/SDWebImage.h

This merge request fixes / reffers to the following issues: #2291 
Maybe the final renaming. 😅 
Renaming all `SDWebImageLoader` protocol and related class naming, to `SDImageLoader`.
This also remove the `SDWebImageDownloader.h` header in `SDWebImageManager`. Since we can custom loader/cache, we'd better only expose the protocol, but not the acutal class, which cause more dependency. (The implementation does not get effected)
This `SDWebImageLoader` is introduced in 5.x, so it's not a API break change to 4.x user.

Renaming image loader

---

SDWebImage/UIImage+GIF.h
SDWebImage/UIImage+GIF.m
SDWebImage/UIImage+MultiFormat.h
SDWebImage/UIImage+MultiFormat.m
SDWebImage/WebP/UIImage+WebP.h
SDWebImage/WebP/UIImage+WebP.m
Tests/Tests/SDCategoriesTests.m

Simplify the usage and remove the extra method which is not used so common.
This PR is a refactory for our convenience category `UIImage+MultiFormat`.
Since SDWebImage 4.2, we introduce custom image coder feature and move all the core decoding/encoding code into `SDImageCoder`. So actually these method is just a simple wrapper.
We can now put it further and sync the coder option with more easier-use API for convenience.
The `UIImage+WebP` and `UIImage+GIF` category, however, it's just a special image format type, which is not really good to use. So just keep it as simple and no extra control. If user need detailed control about decoding/encoding, check `UIImage+MultiFormat` or use `SDImageCoder` directly
```swift
extension …
```

Refactor the UIImage+MultiFormat and GIF/WebP category

---

SDWebImage/SDWebImageDefine.h
SDWebImage/SDWebImageDefine.m
SDWebImage/SDWebImageManager.m

This replace the previous `SDWebImageCacheMemoryOnly` option, which is not so accurate and lack of detail control for cache behavior.
Current `SDWebImageCacheMemoryOnly` options is good for some big images, or tempory image which is no need to store in the disk cache.
However, there are still some people including me, hope to totally disable cache storage for some of images. For example, when query the image from Photos Library plugin, we don't want to store the image into disk cache or memory cache at all. Because the cost to load the image again is quite cheap.
We already done something like Custom Cache and allow user to sepcify 4 type of store cache behavior : **store disk only**, **store memory only**, **store memory and …

Add the `SDWebImageContextStoreCacheType` context option to specify target cache type when the image is downloaded by manager and will store to cache

---

SDWebImage/SDImageCache.m
SDWebImage/SDImageCacheConfig.h
SDWebImage/SDImageCacheConfig.m

* ☑ I have read and understood the [CONTRIBUTING guide](https://github.com/rs/SDWebImage/blob/master/.github/CONTRIBUTING.md)
* ☑ I have read the [Documentation](http://cocoadocs.org/docsets/SDWebImage/)
* ☑ I have searched for a similar pull request in the [project](https://github.com/rs/SDWebImage/pulls) and found one : #940 (closed)
* ☑ I have updated this branch with the latest master to avoid conflicts (via merge from master or rebase)
* ☑ I have updated the documentation (if necessary)
* ☑ I have run the lint and it passes (`pod lib lint`)
This merge request fixes / reffers to the following issues: https://github.com/rs/SDWebImage/issues/2356
According to https://github.com/rs/SDWebImage/issues/2356 issue, I would like to be able to change clear cache setting. 
I added the ability …

Enable to change clear cache option

---

SDWebImage/MapKit/MKAnnotationView+WebCache.h
SDWebImage/MapKit/MKAnnotationView+WebCache.m
SDWebImage/NSButton+WebCache.h
SDWebImage/NSButton+WebCache.m
SDWebImage/SDAnimatedImageView+WebCache.h
SDWebImage/SDAnimatedImageView+WebCache.m
SDWebImage/UIButton+WebCache.h
SDWebImage/UIButton+WebCache.m
SDWebImage/UIImageView+HighlightedWebCache.h
SDWebImage/UIImageView+HighlightedWebCache.m
SDWebImage/UIImageView+WebCache.h
SDWebImage/UIImageView+WebCache.m

This just a little improvement for all View Category about the `context` arg. This fix the issue during #2189 development and no extra API-break was introduced.
In 5.x, we introduce a `SDWebImageContextOption` arg, to pass any object or value that a `enum` can not hold (poor of Objective-C enum). Previouslly I just add one arg into the final method, however, we can add one more convenient method, which take `url`, `placeholderImage`, `options`, `context` these 4 arg and so that our user can type less word to use the context feature :)

Add one convenient method to pass context arg without completed block for all View Category

---

SDWebImage/UIImage+Transform.m

This just a little enhancement to use BGRA8888 instead of ARGB8888 on macOS's compatibility method `SDGraphicsBeginImageContextWithOptions`.
Apple Docs:
> If the opaque parameter is YES, the alpha channel is ignored and the bitmap is treated as fully opaque (kCGImageAlphaNoneSkipFirst | kCGBitmapByteOrder32Host). Otherwise, each pixel uses a premultipled ARGB format (kCGImageAlphaPremultipliedFirst | kCGBitmapByteOrder32Host).

Fix that UIImage+Transform on macOS to use BGRA8888 instead of ARGB8888, as Apple's doc

---

SDWebImage.xcodeproj/project.pbxproj
SDWebImage/NSImage+Compatibility.h
SDWebImage/SDAnimatedImage.m
SDWebImage/SDAnimatedImageView.h
SDWebImage/SDAnimatedImageView.m
SDWebImage/SDImageAPNGCoder.m
SDWebImage/SDImageCache.m
SDWebImage/SDImageCacheDefine.m
SDWebImage/SDImageCoderHelper.m
SDWebImage/SDImageCodersManager.m
SDWebImage/SDImageFrame.h
SDWebImage/SDImageGIFCoder.m
SDWebImage/SDImageLoader.m
SDWebImage/SDWebImageDefine.h
SDWebImage/SDWebImageDefine.m
SDWebImage/SDWebImageManager.m
SDWebImage/UIImage+Metadata.h
SDWebImage/UIImage+Metadata.m
SDWebImage/UIImage+Transform.m
SDWebImage/WebP/SDImageWebPCoder.m
WebImage/SDWebImage.h

This PR, renaming the new category during 5.x development called `UIImage+WebCache`, to the correct naming called `UIImage+Metadata`.
WebCache are concept about image loading, but not for these image meta information related properties. So this should be renamed.
This PR does not cause any further API-breaking from 4.x to 5.x, beucase this category does not appear in 4.x.

Renaming UIImage+WebCache to the correct naming UIImage+Metadata, make clear of the category usage

---

SDWebImage/SDImageLoadersManager.m
SDWebImage/SDWebImagePrefetcher.h

Fix SDImageLoaderManager that only load image when loader can handle url

---

Examples/SDWebImage Demo/LaunchScreen.storyboard
README.md
SDWebImage/SDImageCoderHelper.m
SDWebImage/SDImageIOCoder.m
SDWebImage/SDWebImageCompat.h
SDWebImage/SDWebImageTransition.h

In the previous #2147 , we upgrade our min Xcode version to Xcode 8, as well as the min deployment target version for iOS & macOS.
At that time, we plan SDWebImage 5.x first beta release just before the WWDC 2018. However, now we're already back of that time.
And now, according to [App Store Submit Rule](https://developer.apple.com/news/?id=05072018a/). All the new or upgrade version for Apps **MUST** link iOS 11 SDK & Xcode 9. So it's time to drop Xcode 8.0 support.
> Starting July 2018, all iOS app updates submitted to the App Store must be built with the iOS 11 SDK and must support the Super Retina display of iPhone X.
Since Xcode tool is developer toolchain, for developers, we should use the latest version of toolchain. …

Follow App Store submit rule, upgrade the min Xcode version to Xcode 9.0. Using `@available` and `API_AVAILABLE` to check API availability

---

SDWebImage/SDWebImageDownloader.h
SDWebImage/SDWebImageDownloader.m

Fix crash when assign request property of SDWebImageDownloadToken

---

SDWebImage/SDImageCache.m
SDWebImage/SDImageCacheConfig.h
SDWebImage/SDImageCacheConfig.m

This merge request fixes / reffers to the following issues: #2377 
In the previous #2228 , we introduce a secondary weak memory cache for `SDImageCache`. Which may solve #791 case that a `UIImage` instance is hold by other alive instance by strong reference, however, when we purge the memory cache, we can not investigate this and cause re-query disk cahce or re-download from network. 
I think that feature's aim is correct and it actually solve this problem. However, this behavior should be controlled by user but not hidden in the implementation detail. Because a weak maptable which may delay intance dealloc time at race time (See [this blog](http://cocoamine.net/blog/2013/12/13/nsmaptable-and-zeroing-weak-references/)). And a extra lock to keep thread-safe which may a little impact the …

Add option to enable or disable weak memory cache for SDImageCache

---

SDWebImage/FLAnimatedImage/FLAnimatedImageView+WebCache.h
SDWebImage/FLAnimatedImage/FLAnimatedImageView+WebCache.m
SDWebImage/SDImageCacheConfig.h

This merge request fixes / reffers to the following issues: #2377 
This PR provide a control for `FLAnimatedImageView+WebCache`, which allow user to decide whether to use memory cache for associated `FLAnimatedImage` instance on UIImage object for memory cache storage. The related PR is #2181 
Since `FLAnimatedImage` is not so **Lightweight** as normal static `UIImage`, because it also hold a `internal cache`, and bind `compressed GIF data`, `poster image`, these two property, maybe also memory consuming. So it's better to provide a control for this behavior. For example, if user just use some small GIF and use a UITableView cell which only 10 FLAnimatedImageView can visible on screen at same time, they do not need to cache it at all.

Add cache control for FLAnimatedImage, this allow user to disable memory cache for associated FLAnimatedImage instance

---

SDWebImage/SDWebImageManager.m

Reason:
We need to remove operation, so let's replace it with `NSSet`.

Replace runningOperations of SDWebImageManager from Array to Set

---

SDWebImage/UIView+WebCacheOperation.m

`sd_imageLoadOperationForKey` added in `5.x`, let's add nil check. The same issue as #2386 .

Fix nullable key when get image load operation

---

SDWebImage/NSData+ImageContentType.h
SDWebImage/NSData+ImageContentType.m
SDWebImage/SDWebImageCodersManager.m
SDWebImage/SDWebImageCompat.m
SDWebImage/SDWebImageGIFCoder.m
SDWebImage/SDWebImageImageIOCoder.m
SDWebImage/SDWebImageWebPCoder.m
SDWebImage/UIImage+MultiFormat.h
SDWebImage/UIImage+MultiFormat.m

This merge request fixes / reffers to the following issues: #2374 
This PR add a `sd_imageFormat` property to UIImage category, which store the original compressed image data format (because UIImage will lost this information after created).
This feature is useful to fix #2374 , because we need to detect that if `image.sd_imageFormat == SDImageFormatGIF` to query cache again. However, except that, this property can be really useful for many aspects. Including extra process for image transformer (base on type to do something like a `GIF` mark).. So I think introduce this API is adoptable.
Change is quite simple, each `SDWebImageCoder` decode method shuold store the image format information, and some common method which create new image based on CGImage should also keep this information not …

Keep the information about image's original compressed format, for API which only contains image but not image data to process extra logic

---

SDWebImage/SDImageCache.h
SDWebImage/SDImageCache.m

This merge request fixes / reffers to the following issues: #2374 
This PR add one sync version API `diskImageDataForKey:` on `SDImageCache`.
Sometimes we need to directly parse the image data instead of let the decoding process happend. So we need the raw image data. Current API seems can't solve this.
This can help to solve #2374 , which need to detect the original image foramt is GIF, and try to query disk cache to get the raw image data and get `FLAnimatedImage` instance. Except this, this may also be helpful for use case when we need directly transfer the image data (for example, store data to Photos library). So I think maybe this is adoptable.

Add one sync API for SDImageCache to directly get the image data from disk instead of image instance

---

SDWebImage/SDImageAPNGCoder.m
SDWebImage/SDImageCoderHelper.m
SDWebImage/SDImageGIFCoder.m
SDWebImage/SDImageIOCoder.m

We shouldn't use `__bridge_transfer`, it would transfer ownership, e.x. We use `kCGImagePropertyGIFDictionary` in multiple places, if `kCGImagePropertyGIFDictionary` is not a `const CFStringRef`, it would leads to crash. Fortunately, it is, so we are not crash, because `CFRelease` would do nothing when `ref` is constant. But Let's keep the correct way.

Replace __bridge_transfer with __bridge when convert from CFStringRef to NSString

---

SDWebImage/NSData+ImageContentType.h
SDWebImage/NSData+ImageContentType.m
SDWebImage/SDImageAPNGCoder.m
SDWebImage/SDImageCoderHelper.m
SDWebImage/SDImageGIFCoder.m
SDWebImage/SDImageIOCoder.m
Tests/Tests/SDCategoriesTests.m

Renaming Rename `sd_UTTypeFromSDImageFormat` to `sd_UTTypeFromImageFormat`. Since that `SDImageFormat` 's `SD` does not needed in the selector naming. It's just a prefix.
This renaming does not affect our Swift user, since both of these generated Swift API is `open class func sd_UTType(from format: SDImageFormat) -> CFString`.

Rename `sd_UTTypeFromSDImageFormat` to `sd_UTTypeFromImageFormat`

---

SDWebImage/NSData+ImageContentType.h
SDWebImage/SDImageCoder.h

Since SDWebImge 4.2, we have custom coder, which can refactor our architecture to allow new image format support by using [coder plugins](https://github.com/rs/SDWebImage/wiki/Advanced-Usage#custom-coder-420). This can make SDWebImage core lib more clear, without maintain the dependency of specify image format.
From the design part, since the coder plugin handle the image decoding / encoding format, SDWebImage core lib should not assume or dependent how much of plugins are registered and the detailed implementation of plugin. However, for current coder plugin protocol define, seems we have one type that still bind to SDWebImage repo itself, but not allow custom coder plugin to extern. This is the type `SDImaegFormat`. …

Change SDImageFormat to use `NS_TYPED_EXTENSIBLE_ENUM` instead of fixed enum, to allow custom coder plugin extern the define

---

SDWebImage/FLAnimatedImage/FLAnimatedImageView+WebCache.m

We help FLAnimatedImage framework to fix their issue :)
This merge request fixes / reffers to the following issues: #2402 #1317
This PR, fix a long-history issue, cause not by SDWebImage framework itself, but the third-party library FLAnimatedImage.
The upstream bugfix PR is https://github.com/Flipboard/FLAnimatedImage/pull/215. However, maybe this PR will take long time to be merged in, and some user may still face this issue, we have to fix (actually, `hack`) this issue by our own hand :)
See #2402 for the issue, demo and solution here. I just don't duplicate things twice 😴

Fix the bug when FLAnimatedImageView firstly show one EXIF rotation JPEG `UIImage`, later animated GIF `FLAnimatedImage` will also be rotated

---

SDWebImage/SDImageCacheDefine.m
SDWebImage/SDImageCoder.h
SDWebImage/SDImageCoder.m
SDWebImage/SDImageLoader.m

This is a solution for #2404 . `SDWebImageContext` contains all the extra information through view category, cache, manager API, but it's not accessable from the custom coder plugin.
It's not surprise because in my mind, a decoder, should only consider about the image & image data, or anything related to the decoding option (Like animation or not, scale factor).
But however, if some custom coder plugin user, who want do some business logic related process, during image decoding. They have no choice to know the context. So I guess, maybe we can open this possibility.
Actually, this feature request, is from [SDWebImageFLPlugin's PR](https://github.com/SDWebImage/SDWebImageFLPlugin/pull/2), which will create a …

Add SDImageCoderWebImageContext coder option, which allow custom coder plugin, to receive the context option from top-level API

---

SDWebImage/NSData+ImageContentType.h
SDWebImage/SDImageCoder.h

This merge request fixes / reffers to the following issues: #2400 
It seems that after #2400 change the `enum` with `NS_TYPED_ENUM`, the Swift API that use `SDImageFomat` as a arg that may also been changed, which is not as expected. 😕 
I check the [SE-0005 Better Translation of Objective-C APIs Into Swift](https://github.com/apple/swift-evolution/blob/master/proposals/0005-objective-c-name-translation.md). Swift 3 will ommit when the **method name** && **type name** contains same word. For example, **-(BOOL) canEncodeTo`Format`:(SDImage`Format`)format** this API. Since both **method name** and **type name** contains `format` word, the generated API may looks `canEncode(to:)`. 
Using enum will actually make it recognized as `SDImageFormat` **type name**. But however, It seems that a …

Fix that using `NS_TYPED_ENUM` on `SDImageFormat` cause the existing Swift API naming changed

---

SDWebImage/SDImageCacheDefine.m
SDWebImage/SDImageLoader.m
SDWebImage/SDWebImageDownloader.m

There is a mistake that the 3 options in `SDWebImageDownloader` does not correctly been set.
+ `SDWebImageAvoidDecodeImage`
+ `SDWebImageDecodeFirstFrameOnly`
+ `SDWebImagePreloadAllFrames`
This PR also fix the warning which shadow the local variable of `options`

Fix that downloader options about image decoding is not correctly set

---

SDWebImage/SDWebImageDownloader.m
Tests/Tests/SDWebImageDownloaderTests.m

remove addProgressCallback, add createDownloaderOperationWithUrl

---

SDWebImage/SDWebImageDownloader.m
SDWebImage/SDWebImageDownloaderConfig.h
SDWebImage/SDWebImageDownloaderConfig.m
SDWebImage/SDWebImageDownloaderOperation.h
SDWebImage/SDWebImageDownloaderOperation.m
Tests/Tests/SDWebImageDownloaderTests.m
Tests/Tests/SDWebImageTestDownloadOperation.h

This merge request fixes / reffers to the following issues: #2199
See my last comment on #2199.
Our current downloader, will callback your progressBlock whenever it receive the `URLSession:dataTask:didReceiveData:` delegate method. And then do a progressive image decoding. This rate is not controllable, and after #2199 been merged, this speed become more frequent because of the progressive decoding now does not block delegate queue (so that URLSession can delivery more delegate call in session queue)
But however, when the network speed is lower, this will cause we submit progressBlock and the progressive decoding task  too frequently. And if our decoding code is not performent enough, this will consume much more CPU. So it wil cause we waste too much of time on the progressBlock business …

Feature minimum progress interval

---

SDWebImage/SDMemoryCache.m

This is a bug that during when I'm solving the merge conflict from master to 5.x branch. The `shouldUseWeakMemoryCache` property does not do anything. So this PR fix it.

Fix that `shouldUseWeakMemoryCache` code was lost during merge conflict

---

Examples/SDWebImage Demo/MasterViewController.m
SDWebImage/NSData+ImageContentType.h
SDWebImage/NSData+ImageContentType.m
SDWebImage/SDWebImageImageIOCoder.m

Fix the current hard-coded system version checking with Image/IO source uttypes checking
This merge request fixes / reffers to the following issues: #2081
It seems that in the last of 2017. We introduce `SDImageFormatHEIC`. At that time, the iPhone simulator does not works well on the heif image decoding. So we do some heif decoding compatibility check based on system version, platform and simulator. But now, since Xcode 9.3, iPhone Simulator can now successfully rendering HEIF images, that check seems will cause a wrong result. And I think hard-coded the result (For example, we hard-coded watchOS does not support HEIF) is not a good idea.
Another issue, HEIF actually contains 6 brands of structural format. Such as this image: https://nokiatech.github.io/heif/content/images/ski_jump_1440x9 …

Add SDImageFormatHEIF represent mif1 && msf1 brands

---

README.md

It's time to say goodby to `versioneye`. It has [shut down](https://blog.versioneye.com/2017/10/19/versioneye-sunset-process/).

Remove versioneye from README

---

SDWebImage/SDWebImageDownloader.m

Let's tell the server what we are. Server maybe forbidden us if he think it's not the valid request.
Don't needs to reinventing the wheel, borrow snippet from [AFNetWorking](https://github.com/AFNetworking/AFNetworking/blob/a24b4896bb6e62f73b4dbc7ccf9f11f1a8720f11/AFNetworking/AFURLRequestSerialization.m#L220-L238).
Fixed #2408 .

Add default HTTP User-Agent for specific system

---

SDWebImage/SDDiskCache.h
SDWebImage/SDDiskCache.m
SDWebImage/SDImageCache.m
Tests/Tests/SDImageCacheTests.m

This merge request fixes / reffers to the following issues: #2412 
The original is from #2412 
This is a migration for 4.x user of SDWebImage, because we change the default cache path from `Library/Caches/default/com.hackemist.SDWebImageCache.default` to `Library/Caches/default/com.hackemist.SDImageCache.default`
This change base on the #2412, and add one test for this migration.
And I polish the new API in `SDDiskCache` class, to make it also possible for common usage.
@zhongwuzw @bpoplauschi

Feature disk cache migration from 4.x

---

SDWebImage/SDWebImageDownloader.h
SDWebImage/SDWebImageDownloader.m
SDWebImage/UIView+WebCacheOperation.m

Make download receive response notification only dispatch to specific observer
Currently, we add observer when create `SDWebImageDownloadToken`, when post `SDWebImageDownloadReceiveResponseNotification`, every observer would receive notification, we use `downloadOperation == self.downloadOperation` to filter its wanted notification. It's not necessary, e.x. Let's assume we have 10 `downloadToken`, each download would be post notification once, so notification center would dispatch selector at most (1 + 2 + 3 + ..... + 10) = 55 times in main thread. After my `PR`, we only dispatch 10 times.

Make download receive response notification only dispatch to specific observer

---

SDWebImage/SDDiskCache.h
SDWebImage/SDDiskCache.m

Fix cache migration when dstPath intermediate directories not exist

---

SDWebImage/SDAnimatedImageView.m

When the coder was updated, currentData may not be the same instance as previousdData. We should check the that current data is appended by previous data
This PR fix a race condition, for that 5.0 SDAnimatedImageView progressive animated image rendering. (See [Animatied Image - Rendering](https://github.com/rs/SDWebImage/wiki/Advanced-Usage#rendering))
Because of current implementation detail of `SDAnimatedImage` architecture, each `SDAnimatedImage` hold a decoder, the `SDAnimatedImage.animatedImageData` is just a proxy to call decoder's data). For progressive animation support, each progressive image during same request is created with the request-level decoder for performance. Here is a race condition that during …

Fix a race condition during progressive animation load in SDAnimatedImageView

---

SDWebImage/SDWebImageIndicator.m
SDWebImage/UIView+WebCache.m

This merge request fixes / reffers to the following issues: 
A silly mistake. The `NSProgressIndicator` macOS, its `doubleValue` property, is hundred percented. Which means the `doubleValue == 100` represent 100%.
However, `UIProgressView` on UIKit, its `progress` property is the raw value. Which means `progress == 1` represent 100%.
So this just fix this. Also some little performance changes for progressBlock.

Fix the bug that progress indicator on macOS stop at 1% but not 100% when download finished

---

SDWebImage/SDWebImageDownloaderConfig.h
SDWebImage/SDWebImageDownloaderOperation.h
SDWebImage/SDWebImageDownloaderOperation.m
Tests/Tests/SDWebImageDownloaderTests.m

This merge request fixes / reffers to the following issues: #2430
This bug was introduced in #2415 .
Fix the behavior that `minimumProgressInterval` property, should not ignore the final status (when download bytes >= excepted bytes and download get finished). Even we set `minimumProgressInterval` to 1.0, when download progress reached 100%, we should callback at least once. When `minimumProgressInterval` to 0.51, we should callback twice.
Also update the comments and test to ensure this behavior.

Fix that the minimumProgressInterval should always callback the final finished progress but not ignore it

---

Tests/Tests/SDCategoriesTests.m
Tests/Tests/SDTestCase.h
Tests/Tests/SDTestCase.m

The original remote GIF image for `testFLAnimatedImageViewSetImageWithURL` is down. So now the all new Travis-CI test failed. We'd update a new resource to let it pass (it's from 5.x).

Fix the test case testFLAnimatedImageViewSetImageWithURL because of remote resource is not available

---

SDWebImage/SDWebImageManager.m
Tests/Tests/SDWebImageManagerTests.m

Another serious bug, that previouslly not be found. The cache key filter context arg are been parsed as cache serilizer (These two are totally different...)
It really important that we should always write test case to avoid this silly mistake, again :)

Fix the bug that `SDWebImageContextCacheKeyFilter` wrongly be used as cache serializer and cause crash

---

SDWebImage/SDAnimatedImage.h
SDWebImage/SDDiskCache.h
SDWebImage/SDDiskCache.m
SDWebImage/SDImageCoder.h
SDWebImage/SDImageTransformer.h
SDWebImage/SDWebImageDownloaderOperation.h
SDWebImage/SDWebImageIndicator.h
Tests/Tests/SDWebImageTestCache.m

This PR is a API refinement. We want to make our API more easier to use for both Objective-C side and Swift side. Current many of our protocol method, use the raw getter method, instead of declare a readonly property. The generated Swift API will also be declared as function.
However, according to the Apple's API adoption, for the single getter variable (Which the implementation mostlly use a actual store property instead), it's encouraged to use property instead, so that the user can use consistently wherever I treate the instance as a actual instance of some class, or instance of the protocol.
```swift
let coder: SDImageGIFCoder = SDImageGIFCoder()
let coder2: SDAnimatedImageCoder = SDImageGIFCoder()
let frameCount = …
```

Adopt all the protocol APIs which contains getter value to use property instead, to make the API easy to use or Swift user

---

SDWebImage/SDDiskCache.m

Keep resource key the same as `cacheContentDateKey`, because if `cacheContentDateKey` is `NSURLContentAccessDateKey`, we can not get `NSURLContentModificationDateKey` value when we do secondly clean step.
```
NSArray<NSString *> *resourceKeys = @[NSURLIsDirectoryKey, cacheContentDateKey, NSURLTotalFileAllocatedSizeKey];
```

Fix resource key invalid when clean cached disk file

---

SDWebImage/SDDiskCache.m
SDWebImage/SDImageCacheConfig.h

* [] I have updated this branch with the latest master to avoid conflicts (via merge from master or rebase)
Add no expiration file support of disk cache, if user set a negative value of `maxCacheAge`, we would not do expiration check and remove any expiration file.

Add no expiration file support of disk cache

---

SDWebImage/SDAnimatedImage.h
SDWebImage/SDAnimatedImage.m
SDWebImage/SDAnimatedImageView.h
SDWebImage/SDImageCacheDefine.m
SDWebImage/SDImageCoder.h
SDWebImage/SDImageLoader.m
SDWebImage/SDWebImageDefine.h
SDWebImage/SDWebImageManager.m

This merge request fixes / reffers to the following issues: 
In the previous changes on #2405, we introduce one new coder options for all the normal decoding methods, like `decodedImageWithData:options:`. However, since we supports animation class, which just call the `initWithData:scale:` on the `UIImage` super method. So that the coder options is missed.
It's normally OK, because the animation decoding only considerate about the scale factor and image data, now. However, this is not extensible, and it now break the consitence between normal static image decoding && animation image decoding.
So, I think we should introduce this coder options arg available for animation class as well.
Quite straightforward, we don't use the `initWithData:scale:` method for animation decoding now, we pass …

Add one initializer with extra arg for custom animated image class to use possible coder options, to make it extensible

---

SDWebImage/MapKit/MKAnnotationView+WebCache.m
SDWebImage/NSButton+WebCache.m
SDWebImage/UIButton+WebCache.m
SDWebImage/UIImageView+HighlightedWebCache.m
SDWebImage/UIView+WebCache.h
SDWebImage/UIView+WebCache.m
Tests/Tests/SDWebCacheCategoriesTests.m

This PR, enhance our `SDSetImagBlock`, to provide more args for advacend usage.
Currentlly, there are 4 blocks about image, in our View Category.
+ `SDExternalCompletionBlock`: image, error, cacheType, imageURL
+ `SDInternalCompletionBlock`: image, imageData, error, cacheType, finished, imageURL
+ `SDWebImageTransitionPreparesBlock`: view, image, imageData, cacheType, imageURL
+ `SDSetImageBlock`: image, imageData
It seems that some user need extra context to process their business set-image logic, after image was queried or downloaded. The last one `SDSetImageBlock`, however, does not contains the `cacheType, imageURL` context, make it not so customizable for advacend usage.
For exmaple, when introduce the `cacheType`, we …

Feature set image block extra args

---

SDWebImage/SDAnimatedImageView.m

A code robustness protect. 
Normally this can not happen for built-in `SDAnimatedImageView` progressive loading, because when the image data is nil, we don't return a valid image instance. However, it may be triggered if you use some other implementations (I write a local test and found this issue).
Just add protect for this to avoid `-[NSData rangeOfData:options:range:]` throw the exception when data is nil.

Add protect when custom animated image class image data is nil during progressive animation check

---

SDWebImage/SDAnimatedImageView.m

Currently, we decode animated image JIT by default, we have `frameBuffer` to save `frame`, but actually, for the most time, we would decode image from `imageSource` every time we need to render each index, so let's prevent this re-decoded things when we already have cached frame.
I simply test [dogflops](http://assets.sbnation.com/assets/2512203/dogflops.gif) git from demo, it has 78 frames, after using cache, it would reduce 43 decode times when display.

Decrease animated decode times when cache enable

---

SDWebImage/SDImageAPNGCoder.m
SDWebImage/SDImageGIFCoder.m

`kCGImageSourceShouldCache` is only valid when creating an image from image source, image source would not treat this option. Only `kCGImageSourceTypeIdentifierHint` can pass to options when creating image source. Please see [Documents](https://developer.apple.com/documentation/imageio/kcgimagesourceshouldcache)

Remove kCGImageSourceShouldCache option when creating image source

---

SDWebImage/SDAnimatedImage.m
SDWebImage/SDAnimatedImageView.m
SDWebImage/SDImageCodersManager.m
SDWebImage/SDImageLoadersManager.m
SDWebImage/SDMemoryCache.m
SDWebImage/SDWebImageCompat.h
SDWebImage/SDWebImageDownloader.m
SDWebImage/SDWebImageDownloaderOperation.m
SDWebImage/SDWebImageManager.m

Remove `LOCKBLOCK` with paired macro instead to make it easy to debug
In the f8fe886, we move all the previous implementation defined `LOCK` && `UNLOCK` macro to the common header `SDWebImageCompat.h`.
However, this header is exposed to all the public API header. People who has their own defined `LOCK` macro, may override (or be overrided by us) these macro define and cause compile issue. (Well, what C do :))
So let us rename it with the `SD_LOCK` && `SD_UNLOCK` prefix to avoid this.
That `LOCKBLOCK`, actually is not so convience because when debugging the code, that macro expansion will cause all the debugger hard to step into the line. Use `SD_LOCK` && `SD_UNLOCK` pair instead.

Renaming the `LOCK`, `UNLOCK` with SD prefix to avoid overriding user-defined macro

---

CHANGELOG.md
Docs/ManualInstallation.md
Docs/SDWebImage-4.0-Migration-guide.md
README.md
SDWebImage.podspec
SDWebImage/FLAnimatedImage/FLAnimatedImageView+WebCache.m
SDWebImage/SDImageCache.m

Update urls based on [88d3e28](https://github.com/SDWebImage/SDWebImage/commit/f9d05d921e71827f48b63cf38e28a8b1111bf6c7)

Update url after framework transferred

---

.github/stale.yml

- Stale bot is already installed
- This PR will enable it
- Proposed config: 
- issues
- 30 days of inactivity mark as `Stale`, another 7 without response and the bot will auto-close. 
- prs
- 60 days of inactivity mark as `Stale`, another 7 without response and the bot will auto-close. 
- marking an issue/pr with `important` label will make the bot skip it
- Note: any change like comment, label, ... will make the bot remove `Stale` label and give us another 30 days
CC @SDWebImage/collaborators

Added Stale bot config

---

SDWebImage/SDImageCache.m

Fixes based on discussion in #2444 .

Fix extention long length of file name

---

SDWebImage/SDWebImageDownloader.h
SDWebImage/SDWebImageDownloader.m

The change based on two reasons:
1. Use `SD_LOCK` would not causes additional performance cost, in original code, we use `atomic` property, it uses `LOCK` internal every time we call getter or setter, and we do some copy operation, it's also unnecessary.
2. Using `atomic` property has potential issue of data corruption, even if setter or getter of `HTTPHeaders` is thread safe, but three line of code below is not safe, let's assume two thread call it concurrently, both thread 1 and thread 2 already executes [1] and [2], now would call [3], if thread 1 do first, then thread 2 call later, we can see only thread 2 works to the final `HTTPHeaders`, the operation of thread 1 lost.
```objc
NSMutableDictionary *mutableHTTPHeaders = …
```

Replace atomic property with SD_LOCK

---

SDWebImage/UIImage+MultiFormat.h

We should keep previous naming `sd_imageData(as:)` from 4.x, it should not be a API break changes.
This merge request fixes / reffers to the following issues: #2400 #2413 
It seems that since we change `SDImageFormat` from enum to `NS_TYPED_EXTENSIBLE_ENUM`, cause some Swift API naming changed by accident. These current API naming is OK.
In #2413 I fix some, but today when I try to migrate a 4.x project into 5.x, I found that this API was also been changed by accident. We should recovery them with correct API for Swift user before 5.0.0 release.
+ `sd_imageData(as imageFormat: SDImageFormat) -> Data?` => `sd_imageData(asFormat imageFormat: SDImageFormat) -> Data?`

Fix the accident changes of Swift API naming for `sd_imageDataAsFormat:`

---

SDWebImage.xcodeproj/project.pbxproj
SDWebImage/SDImageGraphics.h
SDWebImage/SDImageGraphics.m
SDWebImage/UIImage+Transform.m
WebImage/SDWebImage.h

😅 Current we have some cross-platform helper method, like these `SDGraphics *` method to create and render bitmap context for images. Those methods are really useful for our image transform implementation cross UIKit/AppKit.
Currently we hide them tied to the `UIImage+Transform` as static method, however, some coder plugin author wants to use them as well. And other modules like `SDImageCoderHelper` may also use some of them to simply code. Instead of each one duplicate a copy of these method, I think since these method are for really common usage, and does not cause too much of maintain issue. It's a good idea to expose them.
I put all of them into a single files (like `UIGraphics.h), to make it modular to use. Our PDF coder …

Expose the graphics helper method for coder plugin author and fix scale issue

---

SDWebImage/FLAnimatedImage/FLAnimatedImageView+WebCache.m
SDWebImage/UIView+WebCache.h
SDWebImage/UIView+WebCache.m

This merge request fixes / reffers to the following issues: #2404
Since we still need the FLAnimatedImage hack code, because the user complain about the first time create`FLAnimatedImage` instance will block the main queue. And the solution is #2404 to create it on the global queue.
Because this is a compatible hack code, I think we should not introduce too much of thing for this. I provide a much simple solution, but make it works the same effect without any performance lost and still use the GCD, which is much stable.
PS: To say, I think this performance issue should be reported to the https://github.com/Flipboard/FLAnimatedImage team, to allow user to skip that for-in loop using `CGImageSoureCreateImageAtIndex`, which will cause a full decoding process and consume CPU. The correct way …

Revert the hack code for FLAnimatedImage compatible, because of the FLAnimatedImage initializer method block main queue.

---

SDWebImage/SDImageGraphics.m

This merge request fixes / reffers to the following issues: #2523 
A code mistake, which cause recursive call. Currently this method seems have no test case coverage. Only that `SDGraphicsBeginImageContextWithOptions` is covered. Need we add one ?

Fix the `SDGraphicsBeginImageContext` method recursive call issue

---

SDWebImage/SDImageCache.m

Fix wrong image cache type when disk and memory cache missed

---

Configs/Module-Shared.xcconfig

This merge request fixes / reffers to the following issues: #2494 
@bpoplauschi Those xcconfig project refactor contains issue. The `ENABLE_BITCODE` must be set `NO` in macOS. You can also check previous Xcode configuration in GUI.
This break usage of current Legacy Build System. The New Build System can build because they ignore this wrong config. But the New Build Systrem contains some small issue in producation from many environment. We shuold support both of them. (Don't need to specify global workspace setting, user can use `xcodebuild` to dynamic specify which build system should be used.)

Fix that macOS does not support bitcode, current xcconfig cause build issue on Legacy Build System

---

README.md
SDWebImage.podspec

Fixes #2547 .
`CocoaPods` 1.5.0 support swift static library, refer to the [guide](http://blog.cocoapods.org/CocoaPods-1.5.0/), we can add 'DEFINES_MODULE' => 'YES' to `pod_target_xcconfig`.

Let SD can be imported using static library by CocoaPods

---

SDWebImage/SDImageCache.m

Fix crash when NSMapTable empty keys

---

SDWebImage/SDWebImageDownloaderOperation.m

Yeah, background download would never valid, because we mark task end immediately after create.

Fix background download

---

SDWebImage.xcodeproj/project.pbxproj
SDWebImage/FLAnimatedImage/FLAnimatedImageView+WebCache.m
SDWebImage/SDImageCache.h
SDWebImage/SDImageCache.m
SDWebImage/UIImage+CacheMemoryCost.h
SDWebImage/UIImage+CacheMemoryCost.m
WebImage/SDWebImage.h

Same as #2485 , sync to `4.x`.

Fix memory cache image cost miscalculation for 4.x

---

SDWebImage/SDAnimatedImage.m
SDWebImage/SDImageCacheConfig.h
SDWebImage/UIImage+MemoryCacheCost.h
SDWebImage/UIImage+MemoryCacheCost.m

See #2537 's propose.
See #2537's solution.
Use a catagory property to image memory cache cost value. The getter method return the default calculation rule. The setter method (optional) can specify a temporary value for custom value instead.
```objectivec
@interface UIImage (CacheCost)
/**
The memory cache cost for specify image used by image cache. The cost function is the bytes size held in memory.
For `UIImage`, this method return the single frame bytes size when `image.images` is nil for static image. Retuen full bytes per frame * frame count when `image.images` is not nil for animated image.
For `NSImage`, this method return the single frame bytes size because `NSImage` does not store all frames in memory.
For any other …
```

Use the memory bytes size, instead of pixel size to calculate the memory cost function

---

SDWebImage/SDWebImageDownloader.m

Fix race condition when `isFinished` is NO but `isCancelled` is `YES`.
```
- (void)cancelInternal {
if (self.isFinished) return;
[super cancel];
if (self.dataTask) {
[self.dataTask cancel];
........
// As we cancelled the task, its callback won't be called and thus won't
// maintain the isFinished and isExecuting flags.
if (self.isExecuting) self.executing = NO;
if (!self.isFinished) self.finished = YES;
}
[self reset];
}
```

Fix race condition for creation of download operation when isCancelled is YES but isFinished is NO

---

SDWebImage/SDWebImageManager.m

Fixes #2578 .
#2578  breaks the failed block url processing logical. We don't need to do this, if user wants custom, use delegate instead.

Revert failed block processing logic

---

SDWebImage/SDWebImageWebPCoder.m

Fixes #2585 .
1. Add `WebPDemuxReleaseChunkIterator` for `iter`.
2. Add flags check for ICCP.
3. Use `dataWithBytesNoCopy` instead.
4. Satisfy `Create Rule` for function naming.

Fix potential memory leaks for ICCP && optimize ICCP handler

---

SDWebImage/SDWebImageDownloaderOperation.m
SDWebImage/SDWebImageWebPCoder.m

Current WebP coder in the master branch for 4.x version contains Bug. It ignore the user-config for `shouldDecompressImages`, and always do pre-draw for static WebP images. Not all the user use this feature because it's a trade-off between CPU && RAM.
Instead, it need to share the same logic as normal PNG (via `SDWebImageIOCoder`).
The 5.x WebP coder [SDWebImageWebPCoder](https://github.com/SDWebImage/SDWebImageWebPCoder/blob/master/SDWebImageWebPCoder/Classes/SDImageWebPCoder.m#L134-L148) already fix this issue. But I'm sorry that I did not sync back that changes into 4.x branch.

Fix that WebP decoder in master branch, does not consider the global `shouldDecompressImages` config and always do pre-draw for static WebP images.

---

SDWebImage/SDWebImageDownloader.m

Related `PR`, #2562 ,#2554
After #2574 merged, we can merge this to add the priority feature for operation creation.

Prioritize SDWebImageDownloaderHighPriority if operation already exists

---

SDWebImage/FLAnimatedImage/FLAnimatedImageView+WebCache.m

This merge request fixes / reffers to the following issues: #2486 
@zhongwuzw I think maybe you want this. In 4.x, we can not change the image cost function from pixels count into bytes size.
But actually, since you point out that current memory cost calculation for aniamted image contains issue. We can just focus on to fix those, instead of change too much of thing un-related.
In 5.x, we can totally do refactory and use bytes size for cost function, then using the new protocol method for animated image solution.

Fix the current image cost (pixels) for FLAnimatedImage

---

SDWebImage/FLAnimatedImage/FLAnimatedImageView+WebCache.m
SDWebImage/UIView+WebCache.h
SDWebImage/UIView+WebCache.m
Tests/Tests/SDCategoriesTests.m

This merge request fixes / reffers to the following issues: #2572 #2563
This is another taste of #2572, which does not introduce a private context object, but introduce a private API in `UIView+WebCache.h`, to solve the issue of #2563

Fix the FLAnimatedImage compatible code issue by introduce a private API

---

README.md
SDWebImage.podspec

This merge request fixes / reffers to the following issues: #2601 
See #2601 and #2549 . We turn on the `DEFINES_MODULE` in the Podspec, to mark our SDWebImage as modular framework. Which the aim is to help Swift user, to use SDWebImage as staic framework without the usage of `use_frameworks!`.
However, there are some compatible issue about Xcode and CocoaPods. Some user reply that this break the their project build. And I think it's related to this [CocoaPods #7584 issue](https://github.com/CocoaPods/CocoaPods/issues/7584) and here is one [demo project](https://github.com/dreampiggy/CocoaPodsXCAssetsIssue).
We can not always wait for CocoaPods to fix this issue. It break current some of users usage. So, instead of define the framework as modular framework in Podspec. I prefer to let the …

Revert modular framework

---

SDWebImage/SDImageAPNGCoder.m
SDWebImage/SDImageGIFCoder.m

Revert issue in #2602 .
@dreampiggy From yours [comment](https://github.com/SDWebImage/SDWebImage/pull/2602/files#r251355124), you said `UIAniamtedImage` always return `nil` when call `CGImage`, I check it and found it returns the first `UIImage`'s `CGImage`, which means `frames.firstObject.image.CGImage` equals to `image.CGImage`.

Remove unnecessary CGImage check when encode first frame

---

SDWebImage/SDWebImageDownloaderOperation.m

Fixes #2592 
`image.images` is `nil` if image is GIF, if we don't add this check, in case options have `SDWebImageDownloaderScaleDownLargeImages`, things may go wrong.

Fix shouldDecode check when image format is GIF

---

SDWebImage.podspec

We already use the dependency of FL && libwebp Pods, these build configurations does not do anything
This merge request fixes / refers to the following issues: #2619 
Current SDWebImage's podspec, contains the build settings for `USER_HEADER_SEARCH_PATH`. However, this option does not do anything useful. Because we already add dependency for `FLAnimatedImage`,  the header search path is already here. (I guess this may because of historical issue which use FL/libwebp git submodules, which is only used for Manual Install user, but does not help for CocoaPods. They are separate build dependency).
Remove these can also fix the CocoaPods 1.6.0 warning:
> Can't merge pod_target_xcconfig for pod targets: ["GIF", "WebP"]. Singular build setting USER_HEADER_SEARCH_PATHS has different values.
The …

Fix the unused user header search path warning for CocoaPods 1.6.0.

---

SDWebImage/SDWebImageWebPCoder.m

This merge request fixes / refers to the following issues: #2618 #2585 
See #2618. And the reproduce WebP URL: http://carben.b0.upaiyun.com/Images/1510913905.png!/format/webp
After I reproduce the issue, I finally found this issue is related to the code
```objective-c
NSData *profileData = [NSData dataWithBytesNoCopy:(void *)chunk_iter.chunk.bytes length:chunk_iter.chunk.size freeWhenDone:NO];
```
However, the `CGColorSpaceCreateWithICCProfile` does not do a copy of your byte pointer. So, when the WebP decoder dealloc, the chunk iter will cleanup, the ICC profile data pointer become a dangling pointer and cause crash. This cause a **use-after-free** issue.
@zhongwuzw To say, I think last time when we review the code due to performance issue, we should take more careful. At first I use the …

Fix that WebP with custom ICC Profile will randomly crash, because `CGColorSpaceCreateWithICCProfile` does not copy the ICC data pointer

---

SDWebImage/SDWebImageDownloaderOperation.m

Before any agreement in #2477 , we can nil imageData in advance to free memory, try to decrease memory consumption. Related issue #2620 .

Nil imageData before decode process to free memory

---

SDWebImage.podspec

which can fix some rare WebP issues
This merge request fixes / refers to the following issues: #2431
See #2431 
Our current 4.x branch's WebP subspec, use the libwebp dependency like this.
```ruby
webp.dependency 'libwebp', '~> 0.5'
```
However, since libwebp already bumped version to 1.0 (current latest is 1.0.2), which fix a lots of bugs of WebP decoding && performance. Some of our user and the people from my company want to upgrade to libwebp 1.0. However, current dependency resolve cause we could not upgrade the version.
So, let's update the dependency to use a looser limit of libwebp. I check the code, the libwebp 1.0 is API-compatible with 0.6.1, so it's safe to upgrade.

Update the libwebp dependency to support using 1.0 version and above

---

SDWebImage/SDWebImageWebPCoder.m

This merge request fixes / refers to the following issues: #2626
See #2626
In the 4.4.5 version, we add support to load WebP images' ICC Profile. However, current code seems does not check whether the ICC Profile color space is RGB. When using the color space other than RGB (such as Monochrome, CMYK), the `CGImageCreate` call will fail, so this cause the decoding failed.
So, we must do filter of the ICC Profile's color space before using. To ensure we only use RGB color mode to feed the `CGImageCreate` built-in API.

Fix the issue when WebP contains the ICC Profile with colorSpace other than RGB, which cause the CGImageCreate failed

---

SDWebImage/SDImageTransformer.m
Tests/Tests/SDImageTransformerTests.m

SD 5.0 introduce a feature called [Image Transformer](https://github.com/SDWebImage/SDWebImage/wiki/Advanced-Usage#image-transformer-50), which allows user to transform the decoded image bitmap and save it to a seperate cache.
However, current 5.0.0-beta5, the cache key generated from the transformer, does not match what the comment here:
```
`image.png` |> flip(YES,NO) |> rotate(pi/4,YES) => 'image-SDImageFlippingTransformer(1,0)-SDImageRotationTransformer(0.78539816339,1).png'
```
Instead, it only appending the transformer key one by one, and this result the final cache key like this
```
`image.png` |> flip(YES,NO) |> rotate(pi/4,YES) => `image.png-SDImageFlippingTransformer(1,0)-SDImageRotationTransformer(0.78539816339,1)` …
```

Fix the current transformer cache key generating rules, try to keep the image file extension

---

SDWebImage/SDWebImageDownloader.m

Simplify assign downloaderOperation's minimumProgressInterval code, had passed by my repo travis ci.

simplify assign downloaderOperation's minimumProgressInterval code

---

SDWebImage/SDWebImagePrefetcher.m

Break strong retain cycle for prefetch block.  Related #2631 .

Break strong retain cycle for prefetch block

---

SDWebImage/Private/SDAsyncBlockOperation.m
SDWebImage/SDWebImagePrefetcher.m

In #2631 , we imported operation queue to manage prefetch operation, but it has bugs, leads prefetch operation inconsistency with load operation, which can result in operation queue hang up or operation cancellable invalid.

Fix prefetch hung up

---

SDWebImage/SDImageLoader.h
SDWebImage/SDImageLoadersManager.m
SDWebImage/SDWebImageDownloader.m
SDWebImage/SDWebImageManager.m
Tests/Tests/SDWebImageDownloaderTests.m
Tests/Tests/SDWebImageTestLoader.m

This merge request fixes / refers to the following issues: https://github.com/SDWebImage/SDWebImagePhotosPlugin/issues/5
Current during 5.0 development, we introduced a new protocol, called `SDImageLoaderProtocol`. To provide the function for advanced user to customize the image downloader. Wiki page [here](https://github.com/SDWebImage/SDWebImage/wiki/Advanced-Usage#custom-loader-50)
This is the feature from other popurlar image framework like [Kingfisher](https://github.com/onevcat/Kingfisher/blob/master/Sources/General/ImageSource/ImageDataProvider.swift) or [LKImageKit](https://github.com/Tencent/LKImageKit/blob/master/LKImageKit/Core/Manager/LKImageLoaderManager.h).
Our SDWebImage group also provide a PhotosKit loader, to load the Photos Library assets using the same API of SD. See : …

Rename the SDImageLoaderProtocol method naming to avoid the Selector conflict with SDWebImageManager and cause misunderstanding usage

---

SDWebImage/SDAnimatedImageView.m

when SDAnimatedImageView dealloc, displayLinkContext in the async block will be a bad pointer.
Add __weak to the pointer, make sure it won't create a bad access.

Fix a crash, when SDAnimatedImageView dealloc, displayLinkContext in the async block will be a bad pointer

---

SDWebImage/SDAnimatedImageView.m
Tests/Tests/SDAnimatedImageTest.m

This is original from FL and it's proved to be a of FL itself, but not what UIKit/AppKit behavior.
The `SDAnimatedImageView` implementation, here is a strange hack for `intrinsicContentSize`.
Actually, this code is original from [FLAnimatedImage](https://github.com/Flipboard/FLAnimatedImage/blob/master/FLAnimatedImage/FLAnimatedImageView.m#L199-L214) here. At that time I didn't check whether this is true of false.
But today, during my revisit of 5.0 main feature's functions, I found that this strange hack is useless.
This is the bug of FLAnimatedImage itself, but not what UIKit/AppKit behavior issue. Even without this code, our `SDAnimatedImageView.intrinsicContentSize` works great and return the animated image's size.
So, …

Remove the unused hack of intrinsicContentSize for SDAnimatedImageView

---

SDWebImage/SDAnimatedImageView.m

This PR fix two small issue specify for macOS platform.
1.The `CVDisplayLink` previouslly using the main display. This is OK for most cases.
But when macOS user connect a external display with 120Hz refresh rate and set its as current display, the rendering aniamtion will be slower than expected. The better way, we can call `CVDisplayLinkCreateWithActiveCGDisplays`, to get the current available display's refresh rate. See: https://developer.apple.com/library/archive/qa/qa1385/_index.html
(Typcially this does not cause issue, because most of animated image, the frame duration is larger than 16ms, which is 60Hz)
2.Update the comments of the `imageViewLayer`. This is acutally a fix specify for macOS. Because macOS's layer-backed …

Bugfix macOS related small improvement for SDAnimatedImageView

---

SDWebImage/SDImageCachesManager.h
SDWebImage/SDImageCachesManager.m
SDWebImage/SDImageCodersManager.h
SDWebImage/SDImageCodersManager.m
SDWebImage/SDImageLoadersManager.h
SDWebImage/SDImageLoadersManager.m
Tests/Tests/SDImageCacheTests.m

Update the test cases and documents about this behavior.
This merge request fixes / refers to the following issues: #841 
During my detailed reviewing of 5.0's new feature, I found this `SDImageCachesManager`, does not keep thread-safe unlike `SDImageLoadersManager`. And it does not apply a default value unlike `SDImageLoadersManager`.
These two `SDImageCachesManager` and `SDImageLoadersManager` are the similar class, to support multiple cacehs and multiple downloaders. They should have the same design and concept. So this fix it.
Does not effect the API, only the implementation.

Fix the thread safe issue of caches manager and specify the default caches array value.

---

SDWebImage/SDWebImageManager.m

This merge request fixes / refers to the following issues: #2582 #2623 
See the #2582 comments. Current these code checking the codes, listed in [URL Loading System Error Codes](https://developer.apple.com/documentation/foundation/1508628-url_loading_system_error_codes), but without checking the Error Domain.
This is actually wrong code, See Apple's [Error Handling Programming Guide](https://developer.apple.com/library/archive/documentation/Cocoa/Conceptual/ErrorHandlingCocoa/ErrorObjectsDomains/ErrorObjectsDomains.html).
> Domains serve several useful purposes. They give Cocoa programs a way to identify the OS X subsystem that is detecting an error. They also help to prevent collisions between error codes from different subsystems with the same numeric value.
So, current checking the …

Filter the error domain with NSURLErrorDomain before checking the URL Error Codes

---

SDWebImage/SDWebImageDownloader.h
SDWebImage/SDWebImageDownloader.m
SDWebImage/SDWebImageDownloaderOperation.h
SDWebImage/SDWebImageDownloaderOperation.m

One is in downloader, another is in download operation...
Actually, this does not cause big issue during compile. However, to make it correct and for better generated documentation. We should use the single one declaration.

Fix that `SDWebImageDownloadStartNotification` declare twice in header files

---

SDWebImage/SDWebImageManager.m

This reverts commit 40abbd648d8f788ba385c2c090eeb6a596dffe7a.
Revert #2648 , it break the processing logic when domain is not `NSURLErrorDomain`.

Revert "Filter the error domain with NSURLErrorDomain before checking the URL Error Codes

---

SDWebImage/Private/SDImageCachesManagerOperation.m

Fixes thread-safe issue, CachesManager support concurrency read-write.

Fix caches manager operation thread safe issue

---

SDWebImage/SDImageLoader.h
SDWebImage/SDImageLoadersManager.m
SDWebImage/SDWebImageDownloader.m
SDWebImage/SDWebImageManager.m
Tests/Tests/SDWebImageTestLoader.m

In 4.x, we will blocking any error during network downloading, including the `invalidURL` as well as `badImageData`(image pixel is 0).
Since this is already used in applications, and it's a suitable logic, add check the specify error domain and codes as well.

Fix the black list error domain should filter specify SDWebImageErrorDomain codes which is indeed un-recoverable

---

Docs/ManualInstallation.md
SDWebImage.xcodeproj/project.pbxproj

Now, `SDWebImage` use configuration scripts when user want to archive `Static Libraries` in SDWebImage project, which is unnecessary. If we want to generate `Static Libraries`, we can choose `Static-Library` directly in `Mach-O type` of  `Build Settings`. Xcode will help us manage the directory structure of files, and it is easy to bring issues when manage the directory structure of files by configure scripts in the future.
I also found the documentation `ManualInstallation` that is too old, Since 5.0 is release, We should update the 'Manual Installation Guide' documentation.

Delete prepare shell when archive static library and update manual installation doc.

---

SDWebImage/SDImageCacheConfig.h

This pull request fixes a typo in SDImageCacheConfig maxDiskAge property description

Fixes typo in SDImageCacheConfig maxDiskAge info

---

Examples/SDWebImage OSX Demo/ViewController.m
SDWebImage/SDAnimatedImageView.m
Tests/Tests/SDAnimatedImageTest.m

This merge request fixes / refers to the following issues: #2705 
See #2705 for bug description.
There is one solution #2704 , but it does not help for animated NSImage. This one do the correct way for this problem.
AppKit's Layer-backed view, have a method to let you implements, the [wantsUpdateLayer](https://developer.apple.com/documentation/appkit/nsview/1483461-wantsupdatelayer).
Unlike the UIKit's `UIImageView`, `NSImageView`, by default, does not using any layer-backed, and it using **a optimize policy** to detect the whether to refresh the layer or not. The policy is that NSImageView will using a subview's layer for actual rendering. See the comments there:
> // Layer-backed NSImageView optionally optimize to use a subview to do actual layer rendering.
> // When the optimization is …

Fix the bug of SDAnimatedImageView, which can not render the normal NSImage (including animated image) at all. Only `SDAnimatedImage` can be rendered

---

SDWebImage/SDAnimatedImage.m
SDWebImage/SDImageAPNGCoder.m
SDWebImage/SDImageCacheDefine.m
SDWebImage/SDImageCoderHelper.m
SDWebImage/SDImageGIFCoder.m
SDWebImage/SDImageIOCoder.m
SDWebImage/SDImageLoader.m
SDWebImage/SDWebImageDefine.m
SDWebImage/UIImage+MultiFormat.m

It does not change any logic in the code, Just to make the code  in a pithy style！

Replace if judge with MAX() function in scale less than 1

---

Configs/App-Shared.xcconfig
Configs/Module-Shared.xcconfig
Configs/Test-Shared.xcconfig
SDWebImage.podspec
SDWebImage/MapKit/MKAnnotationView+WebCache.m
SDWebImage/NSButton+WebCache.m
SDWebImage/Private/SDImageAssetManager.m
SDWebImage/Private/SDImageCachesManagerOperation.m
SDWebImage/SDAnimatedImageView.m
SDWebImage/SDImageCachesManager.m
SDWebImage/SDImageCodersManager.m
SDWebImage/SDImageLoadersManager.m
SDWebImage/SDMemoryCache.m
SDWebImage/SDWebImageDownloader.m
SDWebImage/SDWebImageDownloaderOperation.m
SDWebImage/SDWebImageManager.m
SDWebImage/SDWebImagePrefetcher.m
SDWebImage/UIButton+WebCache.m
SDWebImage/UIImageView+HighlightedWebCache.m
SDWebImage/UIView+WebCache.m
WebImage/SDWebImage-Prefix.pch

This merge request fixes / refers to the following issues: #2646 #2683 
Seems someone found that the prefix header files contains issues related to project.
> Actually, I think this will not cause issue. That #2683 is the bad install issue, which does not use Xcode to embed code, and they ignore the `HEADER_SEARCH_PATH` config. Until oneday the `GCC_PREFIX_HEADER` xcconfig option is deprecated (current not), it's still the only way to help us to avoid written import one by one in project implementation files only.
But since changing this is not hard. So let me just replace this.

Replace the private prefix header files with the manually import for each implementation files

---

SDWebImage/SDAnimatedImageView.m
Tests/Tests/SDAnimatedImageTest.m

This merge request fixes / refers to the following issues: #2727 
This PR fix the issue of #2727 . I can translate that issue:
Before this PR, this code will cause crash
```objective-c
SDAnimatedImage *image = [SDAnimatedImage imageWithData:[self testAPNGPData]];
SDAnimatedImageView *imageView = [[SDAnimatedImageView alloc] initWithImage:image];
// Crash here
```
The crash because, the UIKit's method [UIImageView initWithImage:](https://developer.apple.com/documentation/uikit/uiimageview/1621062-initwithimage?language=objc), will implictlly call `setImage:`, which will skip our `commonInit` method to setup the dispatch queue and semaphore. So the next code logic will cause crash.

Fix that SDAnimatedImageView initWithImage will skip the initialize logic and crash

---

SDWebImage/SDImageCache.m

… loaded from cache.
first time, load from internet, it is a thumbnail imageview.
```objc
[imageView sd_setImageWithURL:[NSURL URLWithString:url]
placeholderImage:nil
options:SDWebImageDecodeFirstFrameOnly];
```
second time, load the same image from loader, it is a detail imageview.
```objc
[imageView sd_setImageWithURL:[NSURL URLWithString:url]
placeholderImage:nil
options:SDWebImageFromLoaderOnly];
```
and when thumbnail imageview load the image using `SDWebImageDecodeFirstFrameOnly` on next time, SDWebImage will give it an animated image, it should be a static image.

fix issues: SDWebImageDecodeFirstFrameOnly flag is ignored when image loaded from cache

---

SDWebImage/UIButton+WebCache.m
Tests/Tests/SDImageTransformerTests.m
Tests/Tests/SDWebCacheCategoriesTests.m

Test cases are actually used in UIKIt && AppKit environment, So it doesn't need  macro judgment!

Fix get button background image operation key bug

---

SDWebImage/SDImageAPNGCoder.m
SDWebImage/SDImageGIFCoder.m

This merge request fixes / refers to the following issues: #2738
See #2738. This log is from Image/IO, when the [CGImageDestinationCreateWithData]() `count` arg is passed with 0 instead of 1.
```
2019-05-29 12:47:41.447767+0800 SDWebImage iOS Demo[33116:4568883] CGImageDestinationCreateWithData:3088: *** ERROR: CGImageDestinationCreateWithData: invalid capacity (0)
```
The warning seems from iOS 12+, but sadly, our Test scheme, and Example, disable the `NSLog` function totally. So this does not catch any attention during development. I'll suggest to remove those `OS_ACTIVITY_MODE = disable` in another PR.

Fix that `CGImageDestinationCreateWithData` 0 count arg will log a warning

---

Examples/SDWebImage Demo.xcodeproj/xcshareddata/xcschemes/SDWebImage OSX Demo.xcscheme
Examples/SDWebImage Demo.xcodeproj/xcshareddata/xcschemes/SDWebImage TV Demo.xcscheme
Examples/SDWebImage Demo.xcodeproj/xcshareddata/xcschemes/SDWebImage Watch Demo.xcscheme
Examples/SDWebImage Demo.xcodeproj/xcshareddata/xcschemes/SDWebImage iOS Demo.xcscheme
Examples/SDWebImage Demo/MasterViewController.m
Examples/SDWebImage TV Demo/ViewController.m
Tests/SDWebImage Tests.xcodeproj/xcshareddata/xcschemes/Tests.xcscheme
Tests/Tests/SDWebImageManagerTests.m

This merge request fixes / refers to the following issues: #2739 
The NSLog issue is because of `OS_ACTIVITY_MODE`. From iOS 11+, all the `NSLog` is just pass to [os_log](https://developer.apple.com/documentation/os/os_log). This will hide all the logs from both System framework as well as our Demo app. I guess this changes is from the [stackoverflow](https://stackoverflow.com/questions/37800790/hide-strange-unwanted-xcode-logs). It works in Xcode 8 + iOS 10, but now, this will disable all `NSLog`, it's not a good idea.
For a framework development, system framework will log errors if we misuse the APIs. I don't think hide the log is a good idea. Instead, we should turn it on (The default option in Xcode), so if we face some strange log, we can find it easily.
This PR, also fix the Demo …

Fix the example NSLog issue, and replace the unavailable test image dataset

---

Examples/SDWebImage Demo/MasterViewController.m
Examples/SDWebImage OSX Demo/ViewController.m
Examples/SDWebImage TV Demo/ViewController.m
Examples/SDWebImage Watch Demo Extension/InterfaceController.m

Fix CI issue.
This is because of CocoaPods 1.7.1. And the WebPCoder, which use the `#import <SDWebImage/SDWebImage.h>` inside the umbrella headers.
To fix this, one options is to enable `CLANG_ALLOW_NON_MODULAR_INCLUDES_IN_FRAMEWORK_MODULES`. See [clang warnings](https://clang.llvm.org/docs/DiagnosticsReference.html#wnon-modular-include-in-framework-module)
Another is to fix each of umbrella headers which import the `<SDWebImageWebPCoder/XX.h>` to `<SDWebImageWebPCoder/SDWebImageWebPCoder.h>`. It may need recursive downstream changes. 
This time I choose the second one.

Fix the Demo WebP coder import issue when enable modular headers

---

.travis.yml
SDWebImage.xcodeproj/project.pbxproj

This merge request fixes / refers to the following issues: https://github.com/DylanVann/react-native-fast-image/issues/468
Our SDWebImage static library target, does not allows the integrated project (which use as a Xcode subproject), to archive the final application. Xcode will mark the archived product as invalid product because it contains extra headers.
See more about this in https://github.com/DylanVann/react-native-fast-image/issues/468. 
Note: This issue does not appear for framework target (both Static framework or Dynamic framework)
Seems from the Xcode 10, the previous used `Headers` build phase, will cause the Static Library target's headers, been copied into the integrated Application target's final product. (The same folder level as `Applications/XXX.app`).
This cause the …

Fix the Static Library target issue of headers, which cause the integrated application failed to Archive because of copied headers

---

SDWebImage/UIImageView+WebCache.m

* [ x] I have read and understood the [CONTRIBUTING guide](https://github.com/rs/SDWebImage/blob/master/.github/CONTRIBUTING.md)
* [x ] I have read the [Documentation](http://cocoadocs.org/docsets/SDWebImage/)
* [ x] I have searched for a similar pull request in the [project](https://github.com/rs/SDWebImage/pulls) and found none
* [x ] I have updated this branch with the latest master to avoid conflicts (via merge from master or rebase)
* [x ] I have added the required tests to prove the fix/feature I am adding
* [ x] I have updated the documentation (if necessary)
This backwards-compatible change fixes SDWebImage so it will compile under Xcode 11.
...

fix compatability for Xcode 11

---

SDWebImage/SDAnimatedImageRep.m

Now, we use the self-created CGImageSource instance instead of super class implementation detail. This is more suitable instead of using this ivar marked as Private.
Though this change may reduce performance a little, but since object always processed under global queue, so this does not trigger issue.

Fix the SDAnimatedImageRep which use the deprecated API and cause compile issue on Xcode 11

---

SDWebImage/SDAnimatedImageRep.m

This merge request fixes / refers to the following issues: #2745 
This self created `CGImageSourceRef` should be released when instance is dealloced.
Also a little code style format.

Fix the potential leak for SDAnimatedImageRep image source

---

SDWebImage.xcodeproj/project.pbxproj
SDWebImage/SDWebImageManager.h
SDWebImage/SDWebImageManager.m
SDWebImage/SDWebImageOptionsProcessor.h
SDWebImage/SDWebImageOptionsProcessor.m
Tests/Tests/SDWebImageManagerTests.m
WebImage/SDWebImage.h

This merge request fixes / refers to the following issues: #2719
This PR implements the feature request of #2719. Which request for a both global control as well as per-image-request control for `SDWebImageOptions` and `SDWebImageContext`.
Now, people can use a options processor, to control which final options for current image request should use.
It have a `URL` as well as the `SDWebImageContext` to detect context between different image request, make it most suitable for complicated logic, better than just a default options. Compared with our friends' similar feature [KingfisherManager.defaultOptions](https://github.com/onevcat/Kingfisher/blob/5.5.0/Sources/General/KingfisherManager.swift#L70-L75)
For example, for the user feedback #2679 , we can write like this:
```objective-c …
```

Supports global control on options and context for individual image request

---

Examples/SDWebImage OSX Demo/ViewController.m
SDWebImage/SDWebImageIndicator.h
SDWebImage/SDWebImageIndicator.m

iOS 13 and macOS 10.14 come with the dark mode supports. See WWDC session: [Implementing Dark Mode on iOS](https://developer.apple.com/videos/play/wwdc2019/214/)
Here in the session, the old [UIActivityIndicatorViewStyleWhite/WhiteLarge/Gray](https://developer.apple.com/documentation/uikit/uiactivityindicatorviewstyle?language=objc) has been deprecated. And does not change its color based on system appearance mode.
So, we can introduce the new API by following UIKit's new API. The `large` property translate to `UIActivityIndicatorViewStyleLarge`, the `medium` class property translate to `UIActivityIndicatorViewStyleMedium`.
For macOS, these property translate to `NSControlSize` with `regular` and `small`.
To supports this iOS 13 …

Feature supports dynamic style indicator for iOS 13, fix indicator color on macOS 10.14+

---

SDWebImage/SDWebImageDefine.h
SDWebImage/SDWebImageDefine.m
SDWebImage/SDWebImageManager.m
Tests/Tests/SDWebImageManagerTests.m

This merge request fixes / reffers to the following issues: #2542 
This is enhacement for current 5.0.0 feature [Image Transformer](https://github.com/SDWebImage/SDWebImage/wiki/Advanced-Usage#image-transformer-50). It's from the feature request from the user #2542 
To achieve that feature, we actually need to implements two different parts.
1. **How we store the original image into cache using transformer**
2. **How we query the original image from cache using transformer without downloading**
Actually, both of these two can be seperfated into different PRs. It's better to check, test and merge.
This phase 1 only care about the question 1. And here is the solution.
Before I start to implements this feature, I reference some image framworks with the same feature. For example, …

Supports store original image to cache for transformer

---

SDWebImage/SDWebImageManager.m

This merge request fixes / refers to the following issues: #2759 
The Xcode 11 version Clang Static Analyzer report this warning because of `nullable pass to nonnull`. However, this `-[NSMutableDictionary addEntriesFromDictionary:]` is safe to call with nil. So this just fix for warning. The old version can still keep since this does not cause any runtime crash issue.

Fix the Clang Static Analysis warning of `addEntriesFromDictionary:` API

---

SDWebImage/UIView+WebCache.h
SDWebImage/UIView+WebCache.m

Instead, let users to use KVO and trigger the creation, improve the performance and fix potential issue for most of common usage.
This merge request fixes / refers to the following issues: #2755 
The [Image Progress](https://github.com/SDWebImage/SDWebImage/wiki/Advanced-Usage#image-progress-430) feature was introduced in v4.3, which is aim for advanced user to use a single `NSProgress` object to observe the loading progress, instead of the default progressBlock. Because `NSProgress` supports many method such as hierarchy.
However, since most of users does not use this API, and our current implementation, always create the `NSProgress` instance for any View Category loading, which may impact the performance a little.
I think we can just disable the auto-create logic. If users need KVO, …

Change that the `sd_imageProgress` property to not auto-create instance by framework

---

.gitignore
.travis.yml
Package.swift

This merge request fixes / refers to the following issues: #2751
Xcode 11 introduce the support for Swift Package Manager (SwiftPM). Today I check the SwiftPM's documentation, it supports for not only Swift files, but also the C/C++ files.
So, since SDWebImage is written in Objective-C, it should be supported. And I did this. The `Package.swift` is like the `Podfile`, a rule to define the compile and target. See the full documentation for [Package.swift syntax](https://github.com/apple/swift-package-manager/blob/master/Documentation/PackageDescription.md)
See the screenshot for usage under Xcode 11 Beta, and using [Accio](https://github.com/JamitLabs/Accio) to integrate with iOS project target.

Add support for Swift Package Manager

---

SDWebImage/SDWebImageDownloader.m
Tests/Tests/SDWebImageDownloaderTests.m

If requested by the header `Accept: image/*` (current default value), some servers may not be able to respond normally. (HTTP Code : 406)
So, I think it's better to change the default value.
https://developer.mozilla.org/en-US/docs/Web/HTTP/Content_negotiation/List_of_default_Accept_values#Values_for_an_image
As you can see above, the default value for Safari is `*/*`.
Please review it positively.

Change the default value of accept request header

---

SDWebImage/SDImageCache.h
SDWebImage/SDImageCache.m
Tests/Tests/SDImageCacheTests.m

This merge request fixes / refers to the following issues: #2766 
From 5.0, our SDImageCache have refactory to support customization. It has two level of customization
+ [Custom Image Cache](https://github.com/SDWebImage/SDWebImage/wiki/Advanced-Usage#cache-protocol)
+ [Custom Memory/Disk Cache class](https://github.com/SDWebImage/SDWebImage/wiki/Advanced-Usage#memory-cache)
However, there are some feedback about the second case, the `SDMemoryCache` protocol is OK, but if they have their own class, and have method or property beyond `SDMemoryCache`, they'll be sucked here. Because we have no public API to get the instance of memory cache class.
And our LRU Cache implementation #2766 will provide some custom properties (not existing on `SDImageCacheConfig`, it's tied to LRU Cache itself). …

Expose the memoryCache and diskCache object on `SDImageCache`, Make it useful for user who have custom property beyond `SDImageCacheConfig`

---

SDWebImage.xcodeproj/project.pbxproj
SDWebImage.xcodeproj/xcshareddata/xcschemes/SDWebImage XCFramework.xcscheme

This merge request fixes / refers to the following issues: #2762 
See WWDC Session: https://developer.apple.com/videos/play/wwdc2019/416/
Xcode Release Notes: [New Features - XCFramework](https://developer.apple.com/documentation/xcode_release_notes/xcode_11_beta_2_release_notes#3318304)
Xcode 11 supports a new frameworks format, `xcframework`. Which is like a bundle for all platforms and architecture. This can help for integration user, to just use one file. This can solve the tied steps tocollect 7 different frameworks, zip and unzip them for users, provide a notes to let users distinguish which framework is for which platform && CPU architecture, etc.
I think it's a good way for users to use framework. So we can provide a build script to help create one.
This script is available on …

Provide a script target to directly build all SDWebImage framework and generate all in one XCFramework from Xcode 11

---

.github/ISSUE_TEMPLATE.md
Examples/SDWebImage Demo.xcodeproj/xcshareddata/xcschemes/SDWebImage OSX Demo.xcscheme
Examples/SDWebImage Demo.xcodeproj/xcshareddata/xcschemes/SDWebImage TV Demo.xcscheme
Examples/SDWebImage Demo.xcodeproj/xcshareddata/xcschemes/SDWebImage Watch Demo.xcscheme
Examples/SDWebImage Demo.xcodeproj/xcshareddata/xcschemes/SDWebImage iOS Demo.xcscheme
Examples/SDWebImage Demo/LaunchScreen.storyboard
Examples/SDWebImage OSX Demo/Base.lproj/Main.storyboard
Examples/SDWebImage TV Demo/Base.lproj/Main.storyboard
Examples/SDWebImage Watch Demo/Base.lproj/Interface.storyboard
README.md
SDWebImage.xcodeproj/xcshareddata/xcschemes/SDWebImage static.xcscheme
SDWebImage.xcodeproj/xcshareddata/xcschemes/SDWebImage.xcscheme
SDWebImage.xcodeproj/xcshareddata/xcschemes/SDWebImageMapKit.xcscheme
SDWebImage/SDWebImageIndicator.m
Tests/SDWebImage Tests.xcodeproj/project.pbxproj
Tests/SDWebImage Tests.xcodeproj/xcshareddata/xcschemes/Tests Mac.xcscheme
Tests/SDWebImage Tests.xcodeproj/xcshareddata/xcschemes/Tests.xcscheme

This merge request fixes / refers to the following issues: #2372 #2766 
See the similar PR #2372
Xcode 11 is now available via WWDC 2019. And Xcode 9 is 2 years ago.
According to App Store Submit Rule. All the new or upgrade version for Apps MUST link iOS 12 SDK & Xcode 10. So it's time to drop Xcode 9.0 support. See: https://developer.apple.com/news/?id=03202019a
> Starting March 27, 2019, all new apps and app updates for iPhone or iPad, including universal apps, must be built with the iOS 12.1 SDK or later and support iPhone XS Max or the 12.9-inch iPad Pro (3rd generation). Screenshots for these devices will also be required. All new apps and app updates for Apple Watch will need to be built with the watchOS 5.1 SDK or later and support Apple Watch Series 4.
Beside this, Xcode 10 bring …

Follow App Store submit rule, upgrade the minimum Xcode version to Xcode 10.0

---

SDWebImage/UIButton+WebCache.m

This merge request fixes / refers to the following issues: #2784 
This issue was introduced from 8236dee202485428fdd2347c0000d3d5d89bd3b2.
The issue will cause the convenient method `-[UIButton sd_setBackgroundImageWithURL:forState:placeholderImage:options:completed:` and `-[UIButton sd_setBackgroundImageWithURL:forState:placeholderImage:options:progress:completed:` does not pass the final option arg, and ignore the user input arg.

Fix the bug that UIButton setBackgroundImage convenient method does not pass the options arg to next function call

---

README.md

Update the readme due to we support both SwiftPM and XCFramework in v5.1.0.
Since this effect the way people install SDWebImage, we'd better update the readme about this.

Update the readme about Swift Package Manager and xcframework installation guide

---

SDWebImage/Core/SDImageCache.h
SDWebImage/Core/SDImageCache.m
SDWebImage/Core/SDImageCacheDefine.m
SDWebImage/Core/SDImageLoader.m
SDWebImage/Core/SDWebImageDefine.h
SDWebImage/Core/SDWebImageDownloader.h
SDWebImage/Core/SDWebImageDownloader.m
SDWebImage/Core/SDWebImageDownloaderOperation.m
Tests/Tests/SDImageCacheTests.m

This may help for some rare case that user always need the specify image subclass (SDAnimatedImage) for their imageView (SDAnimatedImageView) instead of the built in one.
For user, who mixed the `UIImageView` and `SDAnimatedImageView`, there is one case which may cause problem:
1. UIImageView query the `url1` which is GIF, get one `UIAnimatedImage`
2. SDAnimatedImageView then start to query `url1`, it hit the memory cache and get `UIAnimatedImage`
3. Now this `UIAnimatedImage` start to render on SDAnimatedImageView, which is not performent
This PR aim to solve this, which introduce a option. When the custom image class is not equal to queried image class (or downloaded one), we will reject this image and mark cache miss or …

Add a new option `SDWebImageMatchAnimatedImageClass`, to ensure we always match the custom image class instead of UIImage/NSImage class

---

SDWebImage/Core/NSImage+Compatibility.m
SDWebImage/Core/UIImage+ForceDecode.m
SDWebImage/Core/UIImage+Transform.m

Hello.
Thank you for your library.
I found out that in some *.m-files `nullable` and `nonnull` attributes are missing. I know that this is not an issue because these attributes are using in the corresponding headers files. I just want to keep the same code style for all files.

Add missing nullable and nonnull attributes

---

SDWebImage/Core/SDAnimatedImageView.h
SDWebImage/Core/SDAnimatedImageView.m
Tests/Tests/SDAnimatedImageTest.m

This merge request fixes / refers to the following issues: #2814 
This PR including the two new properties for `SDAnimatedIamge`
+ `clearBufferWhenStopped`: This will clear the internal frame buffer when animating stopped.
+ `resetFrameIndexWhenStopped`: This will reset the image view 's frame into 0 when animating stopped.
`clearBufferWhenStopped` is used to reduce the memory pressure for massive SDAnimatedImageView playing. Because when a imageView was disappear from screen (such as pop or push in list view), it stop the animation, but still keeping the internal buffer cache. This cache can be purged to reduce total usage. (The default value is NO, It's still useful, if you don't want to effect the frame rate or lag when the imageView appear again)
`resetFrameIndexWhenStopped` is used …

Support to clear frame buffer or reset frame index when stopped for SDAnimatedImageView

---

SDWebImage/Core/SDImageCacheDefine.m
SDWebImage/Core/SDImageLoader.m
SDWebImage/Core/SDWebImageDownloader.m
SDWebImage/Core/SDWebImageDownloaderOperation.m
SDWebImage/Core/SDWebImageManager.m
SDWebImage/Core/UIView+WebCache.m
SDWebImage/Private/SDInternalMacros.h

This merge request fixes / refers to the following issues: #2817 
See #2817 
This error check logic, is because of Objective-C's **BOOL** define in 32 bit device.
If you have question, you can check : http://sam.dods.co/blog/2014/02/01/checking-for-a-value-in-a-bit-mask/
In Objective-C, the BOOL is defined like this:
```c
#if (TARGET_OS_IPHONE && __LP64__)  ||  (__ARM_ARCH_7K__ >= 2)
#define OBJC_BOOL_IS_BOOL 1
typedef bool BOOL;
#else
#define OBJC_BOOL_IS_CHAR 1
typedef signed char BOOL; 
// BOOL is explicitly signed so @encode(BOOL) == "c" rather than "C" 
// even if -funsigned-char is used.
#endif
```
Which means, the 32 Bit BOOL is `signed char (-127, 127)`. The 64 Bit Bool is C++ `bool` (which has no overflow issue, see C++ standard …

Fix that some option mask check with local BOOL variable, error result on 32 bit device.

---

Examples/SDWebImage OSX Demo/ViewController.m
SDWebImage/Core/SDAnimatedImageView.m
Tests/Tests/SDAnimatedImageTest.m

This PR fix the issue of `SDAnimatedImageView`, which does not works for the NSImageView's super class properties [imageAlignment](https://developer.apple.com/documentation/appkit/nsimageview/1404963-imagealignment) and [imageScaling](https://developer.apple.com/documentation/appkit/nsimageview/1404956-imagescaling).
These two properties is common used for AppKit developer, and I think they should be supported to help migrate animation from NSImageView to SDAnimatedImageView.
The bug issue is because of previous SDAnimatedImageView implementation for layer rendering. At that time, I use the `self.layer` to render the frame CGImage on it. This works for normal cases, however, it does not support the layout behavior of …

Fix the macOS that SDAnimatedImageView does not works for imageScaling and imageAlignment properties

---

SDWebImage/Core/SDWebImageDownloaderOperation.m

… in CFNetwork.framework. We just fix this without import ) but not available in MacOS
...

Fix macOS 10.10 symbol definition of NSURLSessionTaskPriorityHigh

---

SDWebImage/Core/SDAnimatedImageRep.h
SDWebImage/Core/SDAnimatedImageRep.m
Tests/Tests/SDImageCoderTests.m

This merge request fixes / refers to the following issues: #2846 #2155
See #2155.
This fix the macOS's GIF loop count behavior. When the GIF compressed data does not have any loop count extension metadata.
The standard is here: http://www6.uniovi.es/gifanim/gifabout.htm

Fix the macOS SDAnimatedImageRep to match Netscape standard of GIF loop count, which should use 1 when there are no loop count information

---

Examples/SDWebImage Demo/MasterViewController.m
SDWebImage/Core/SDImageCodersManager.h
SDWebImage/Core/SDImageCodersManager.m
SDWebImage/Core/SDImageHEICCoder.h

This merge request fixes / refers to the following issues: #2849
Current HEIC decoding speed for Image/IO is really slow, and when using in the `UIImageView`, it may block the main UI Thread for seconds level time. 
Since HEIC animated image is really rare on the Internet, maybe we can just remove this from the default coder list, to invesigate future performance enhancement from Apple.
Note the static HEIC decoding does not get effected, because `SDImageIOCoder` support this as well.

Revert animated heic coder from default coder list due to Apple's performance issue

---

SDWebImage/Core/SDWebImageDownloader.m
SDWebImage/Core/SDWebImageManager.m

This merge request fixes / refers to the following issues: #2855 
See #2855 for detailed reason.
This PR change the `strong` retain from `SDWebImageDownloadToken -> ... -> user's completionBlock`, which can let user to retain the token inside their completion without weak-strong-dance.

Make the SDWebImageDownloadToken to not retain the completion block so that user don't need weak-strong dance

---

SDWebImage/Core/SDAnimatedImageView.m
SDWebImage/Core/SDDiskCache.m
SDWebImage/Core/SDWebImageIndicator.m

This merge request fixes / refers to the following issues: Fix #2859
Just for fixing the warnings. All of them can not been solved with new API changes, reason:
+ `CC_MD5`
We can not change the algorithm to generate filename. This is a major break. And I don't think it's a deprecated, it's like a advice. Even Apple remove the `CC_MD5` method, we still need to write our own MD5 hash algorithm, this can not been changed.
+ `UIActivityIndicatorViewStyleWhite`
We can not change this. Because unlike Apple done for dark mode. If the user use `.whiteLarge` indicator, it's always white and large, whatever in dark / light mode (Read our documentation). It's different from Apple's design. But actually, these symbols can been removed in SDWebImage 6.0.0.
For the automatically dark mode support, use …

Fix warnings when deployment target version set to iOS 13+

---

SDWebImage/Core/SDImageAPNGCoder.m

use previous deployment target macro check instead of runtime firmware version check
This merge request fixes / refers to the following issues: #2862 
This fix the regression of that #2862

Revert the change for APNG constants fix for iOS 8 devices which cause crash

---

SDWebImage.xcodeproj/project.pbxproj
SDWebImage/Core/SDWebImageDefine.h
SDWebImage/Core/SDWebImageDefine.m
SDWebImage/Core/SDWebImageDownloader.h
SDWebImage/Core/SDWebImageDownloader.m
SDWebImage/Core/SDWebImageDownloaderDecryptor.h
SDWebImage/Core/SDWebImageDownloaderDecryptor.m
SDWebImage/Core/SDWebImageDownloaderOperation.m
SDWebImage/Core/SDWebImageDownloaderRequestModifier.h
SDWebImage/Core/SDWebImageDownloaderResponseModifier.h
SDWebImage/Core/SDWebImageDownloaderResponseModifier.m
SDWebImage/Core/SDWebImageError.h
Tests/Tests/SDWebImageDownloaderTests.m
WebImage/SDWebImage.h

This merge request fixes / refers to the following issues: #2254 #2809
See the Feature Request draft: #2809
This PR implements the draft, with a new protocol `SDWebImageDownloaderResponseModifier`. Support to both modify the downloaded data, as well as HTTP Response (new from draft).
The data decryptor protocol, now with the `URLResponse` input arg. This change it's because for real application, sometimes you need the HTTP response from server, like HTTP MIME-Type, to detect which algorithm to use, and the HTTP response header have also have [Content-Encoding](https://developer.mozilla.org/zh-CN/docs/Web/HTTP/Headers/Content-Encoding) file, to let Client choose the algorithm.
I think add this one can make it possible for further usage, like complicated algorithm such as AES, or even …

Feature response modifier data decrypter

---

SDWebImage.xcodeproj/project.pbxproj
SDWebImage/Core/SDAnimatedImageView.m
SDWebImage/Private/SDDisplayLink.h
SDWebImage/Private/SDDisplayLink.m

This merge request fixes / refers to the following issues: #2861 
This PR refactory the current `CADisplayLink`, `CVDisplayLink` usage with a cross-platform implementation `SDDisplayLink`. With watchOS support. This class is in private header (since it's not suitable for public usage)
Use `CADisplayLink` on iOS/tvOS, `CVDisplayLink` on macOS, `NSTimer` on watchOS

Refactory animated player phase 1 - cross-platform display link implementation

---

SDWebImage/Core/SDAnimatedImageView.m

This merge request fixes / refers to the following issues: https://github.com/SDWebImage/SDWebImageSwiftUI/pull/30
This strange check will cause the following code does not work as expected. It's better to remove this one, which match the exisiting SDAniamtedImageView on iOS/tvOS behavior.
Example:
```swift
let animatedImage: SDAnimatedImage
view.animates = false //  User may use a Binding Value to toggle to this false value
view.image = animatedImage
view.animates = true // This does not start animation totally on macOS
```
Same code below works on iOS/tvOS, which is not a good design across these platforms with the same meaning API.
```swift
let animatedImage: SDAnimatedImage
view.stopAnimating() //  User may use a Binding Value to toggle to this false value
view.image = animatedImage …
```

Fix SDAnimatedImage on macOS use extra aniamtes property check, which is not intuitive and cause extra setup before usage

---

SDWebImage/Core/UIView+WebCache.m

See example layout:
This stackoverflow answer explain the issue and solution is better: https://stackoverflow.com/questions/4681176/how-to-align-a-subview-to-the-center-of-a-parent-nsview

Fix macOS SDWebImageIndicator center layout issue when indicator was initialized with 0 frame

---

SDWebImage/Private/SDDisplayLink.m
Tests/Tests/SDUtilsTests.m

This merge request fixes / refers to the following issues: #2873 #2867 
Fix `SDDisplayLink` initial value issues. Which should check for 0 division. Added test case for display link.

Fix the SDDisplayLink issue of default value, add test cases

---

.travis.yml
Configs/Module-Shared.xcconfig
Podfile
Tests/SDWebImage Tests.xcodeproj/project.pbxproj
Tests/SDWebImage Tests.xcodeproj/xcshareddata/xcschemes/Tests Mac.xcscheme
Tests/SDWebImage Tests.xcodeproj/xcshareddata/xcschemes/Tests TV.xcscheme
Tests/SDWebImage Tests.xcodeproj/xcshareddata/xcschemes/Tests iOS.xcscheme
Tests/Tests TV/Info.plist
Tests/Tests/SDWebImageDownloaderTests.m
Tests/Tests/en.lproj/InfoPlist.strings
codecov.yml

Currently we have test cases on iOS && macOS. Though tvOS is based on UIKit, it still has somthing different compared to iOS code. So a test case is better. Which may consume 2 more minutes on CI, but it's valuable.
Apple Watch, sadly have no any Unit Test support on Xcode. So we can not add watchOS unit test and coverage report. Hope for future Xcode to support this. Once it's supported, we can add watchOS unit test as well.

Test: Add tvOS platform into core test case

---

Examples/SDWebImage Demo/DetailViewController.m
Examples/SDWebImage OSX Demo/ViewController.m
Examples/SDWebImage Watch Demo Extension/InterfaceController.m
Examples/SDWebImage Watch Demo/Base.lproj/Interface.storyboard
SDWebImage.xcodeproj/project.pbxproj
SDWebImage/Core/SDAnimatedImage.h
SDWebImage/Core/SDAnimatedImage.m
SDWebImage/Core/SDAnimatedImagePlayer.h
SDWebImage/Core/SDAnimatedImagePlayer.m
SDWebImage/Core/SDAnimatedImageView.h
SDWebImage/Core/SDAnimatedImageView.m
SDWebImage/Private/SDDeviceHelper.h
SDWebImage/Private/SDDeviceHelper.m
Tests/Tests/SDAnimatedImageTest.m
Tests/Tests/SDUtilsTests.m
WebImage/SDWebImage.h

This merge request fixes / refers to the following issues: #2867 #2861
Feature Proposal see #2861.
This is the real implementation of that refactory, now we can use `SDAnimatedImagePlayer` to support more common usage, for example:
+ WatchKit support: See the updated WatchKit demo with that player, with better performance than WKInterfaceImage
+ SwiftUI: See [SDWebImageSwiftUI](https://github.com/SDWebImage/SDWebImageSwiftUI))
+ Thread safe: Yes, this animated player is now thread-safe to use, not like that `SDAnimartedImageView` which force main queue
During this refactory, there are also a solution change for our current `Progressive Animated Loading`.
Now, the animated player directly get the coder, such as `SDImageGIFCoder`, so that it don't need previously check of image data (That's …

Refactory AnimatedImageView with player backend, supports more rendering target like WatchKit/SwiftUI 

---

Podfile
SDWebImage/Core/SDAnimatedImagePlayer.h
SDWebImage/Core/SDAnimatedImagePlayer.m
SDWebImage/Core/SDAnimatedImageView.h
SDWebImage/Core/SDAnimatedImageView.m

The play rate currently supports like this:
+ `1.0` means the normal speed.
+ `0.0` means stopping the animation.
+ `0.0-1.0` means the slow speed.
+ `> 1.0` means the fast speed.
+ `< 0.0` is not supported currently and stop animation. (may support reverse playback in the future)
Demo:
[video.mp4.zip](https://github.com/SDWebImage/SDWebImage/files/3809697/video.mp4.zip)

Feature supports to control the AnimatedImage View/Player 's play rate

---

SDWebImage/Core/SDAnimatedImageView.h
SDWebImage/Core/SDAnimatedImageView.m
SDWebImage/Private/SDDisplayLink.m

This runloop mode can use used for the use case above. We can do this better for our Mac SDWebImage user.
Demo video:
[video2.mp4.zip](https://github.com/SDWebImage/SDWebImage/files/3810007/video2.mp4.zip)

Support the runloop mode control for macOS.  Which can be useful when user want to pause animation when drag the mouse, or presenting modal window

---

SDWebImage/Core/SDAnimatedImagePlayer.m
SDWebImage/Core/SDAnimatedImageView.m
Tests/Tests/SDAnimatedImageTest.m

This 5.3.0 version upgrade change this behavior protect. Which break https://github.com/SDWebImage/SDWebImageSwiftUI usage.
Actually, we can add some protect code here, when Image View not visible, do not consume extra CPU to do animating logic.

Fix the case even when Animated Image View is not visible, user calll startAnimating can still do animation

---

SDWebImage/Core/SDMemoryCache.h
SDWebImage/Core/SDMemoryCache.m

Adds a needed `self.delegate = nil` line to `dealloc` in SDMemoryCache. This is the NSCacheDelegate from the superclass.
The only thing on this delegate protocol is `cache:willEvictObject:`, which is really helpful for debugging.  I found that when setting a delegate on SDMemoryCache, I'd get a crash in dealloc and this fixes it.

Support using NSCache delegate with SDMemoryCache default implementation

---

SDWebImage.xcodeproj/project.pbxproj
SDWebImage/Core/SDImageCoderHelper.m
SDWebImage/Core/SDWebImageDefine.m
SDWebImage/Core/SDWebImageManager.m
SDWebImage/Private/SDAssociatedObject.h
SDWebImage/Private/SDAssociatedObject.m

This can help to sync the status. For example, some information (like format, extended object) will lose during the force decoding, or scaled with image key. These information is useful to process, and should be keep.
Using a global function can ensure we always get the correct value on.

Using one global function to ensure we always sync all the UIImage category assocaited object status correctly inside our framework

---

SDWebImage/Core/SDWebImageDefine.m
SDWebImage/Core/SDWebImageDownloader.m

This fix #2890. The reason just as the line 236.
> When we reuse the download operation to attach more callbacks, there may be thread safe issue because the getter of callbacks may in another queue (decoding queue or delegate queue)
> So we lock the operation here, and in `SDWebImageDownloaderOperation`, we use `@synchonzied (self)`, to ensure the thread safe between these two classes.

Fix the thread safe issue with Downloader and DownloaderOperation during cancel

---

SDWebImage.xcodeproj/project.pbxproj
SDWebImage/Core/SDGraphicsImageRenderer.h
SDWebImage/Core/SDGraphicsImageRenderer.m
SDWebImage/Core/SDImageCoderHelper.m
SDWebImage/Core/SDImageGraphics.h
SDWebImage/Core/UIImage+Transform.m
Tests/Tests/SDImageTransformerTests.m
Tests/Tests/SDUtilsTests.m
WebImage/SDWebImage.h

[UIGraphicsImageRenderer](https://developer.apple.com/documentation/uikit/uigraphicsimagerenderer?language=objc) was introduced in iOS 10+, it's a replacement for current [UIGraphicsBeginImageContext](https://developer.apple.com/documentation/uikit/1623922-uigraphicsbeginimagecontext?language=objc).
See related talk in [WWDC 2018 - Image and Graphics Best Practices](https://developer.apple.com/videos/play/wwdc2018/219/).
The UIGraphicsImageRenderer contains a smart feature, it does not use `CGBitmapContextCreate` for a fixed bitmap format (like ARGB8888, which always use 4 channels). Instead, it use a block-based API. It detect your draw code to choose which bitmap format to use. For example, if you draw a RGB CGImage on it, …

Performance - Using UIGraphicsImageRenderer on iOS 10+, save memory when image bitmap is RGB(-25%) or Grayscale(-75%)

---

SDWebImage/Core/SDWebImageDownloader.m

This merge request fixes / refers to the following issues: #2910 
5.4.0 patch release.

Fix the issue that "There may be no complete callback when download the picture of the local path"

---

SDWebImage/SDWebImageDownloader.m
Tests/SDWebImage Tests.xcodeproj/project.pbxproj

This merge request fixes / refers to the following issues: #2910 
4.x branch.

[4.x] Fix the issue that "There may be no complete callback when download the picture of the local path"

---

SDWebImage/Core/SDDiskCache.m
SDWebImage/Core/SDImageCacheConfig.h

This PR add two extra date
+ `Creation Date`: Update only once, the creation date
+ `Change Date`: Any modification on file attribute, like naming, xattr (our `sd_extendedObject`), will update this value

Support to use the creation date and the change date to determine the disk cache expire date compare

---

SDWebImage/Core/NSImage+Compatibility.h
SDWebImage/Core/NSImage+Compatibility.m
SDWebImage/Core/UIImage+Transform.m
Tests/Tests/SDImageTransformerTests.m

Current all methods in `UIImage+Transform`, does not works on the CIImage based UIImage/NSImage (which `.CIImage` returns nonnil, but `.CGImage` returns nil)
This PR support all CIImage, with the correspond Core Image method (not just convert it into CGImage, because it's slower).

Support all transformer method on CIImage based UIImage/NSImage

---

SDWebImage/Core/SDAnimatedImage.h
SDWebImage/Core/SDAnimatedImage.m

This merge request fixes / refers to the following issues: #2923
See #2923 and https://github.com/SDWebImage/SDWebImageWebPCoder/issues/29 to know the reason. 
One solution, is to return nil when the frame count <= 1. However, I found this may break some users' usage. See our own code `SDWebImageMatchAnimatedImageClass` which assume the init success, or the [SDWebImageSwiftUI](https://github.com/SDWebImage/SDWebImageSwiftUI)'s `AnimatedImage` struct, which use only `SDAnimatedImage`.
So, I this instead of return a nil value, return a valid `SDAnimatedImage` instance, but without the keep of `SDAnimatedImageCoder` is a better idea. Which can both reduce RAM usage and keep the compatible for users.

SDAnimatedImage now only keep the animated coder when frame count >=1 , else we wil behave like UIImage to save RAM usage

---

SDWebImage/Core/SDAnimatedImage.m
SDWebImage/Core/UIImage+Transform.m
Tests/Tests/SDImageTransformerTests.m

See W3C Standard: https://www.w3.org/TR/SVG11/filters.html#feGaussianBlurElement
The gaussian blur should use 3 times box convolve, which the box size should be equal to the following fomula:
```
let d = floor(s * 3*sqrt(2*pi)/4 + 0.5)
```
But however, currrent we calculate with this fomula instead, which is wrong:
```
let d = floor((s * 3*sqrt(2*pi)/4 + 0.5) / 2)
```
+ Wrong One: React Native iOS: https://github.com/facebook/react-native/blob/master/Libraries/Image/RCTImageBlurUtils.m#L48
+ Correct One: Google Chrome for iOS: https://chromium.googlesource.com/chromium/src.git/+/81.0.4028.1/ios/chrome/browser/ui/util/uikit_ui_util.mm#363

Fix gaussian blur radius bug

---

SDWebImage/Core/SDAnimatedImageView.m
Tests/Tests/SDAnimatedImageTest.m

See this bug behavior from v5.3.0 - v5.5.0
[Progressive Animation Bug.zip](https://github.com/SDWebImage/SDWebImage/files/4080091/Progressive.Animation.Bug.zip)

Fix the SDAnimatedImageView's progressive animation bug, which reset the frame index to 0 each time new frames available

---

SDWebImage/Core/SDAnimatedImageView.m

Should setup the player's property

Fix the issue that `maxBufferSize` property does not correctlly works for `SDAnimatedImageView`

---

Examples/SDWebImage Demo/MasterViewController.m
SDWebImage/Core/SDWebImageDownloader.h
SDWebImage/Core/SDWebImageDownloader.m
SDWebImage/Core/SDWebImageDownloaderOperation.h
SDWebImage/Core/SDWebImageDownloaderOperation.m
SDWebImage/Core/UIView+WebCache.h
Tests/Tests/SDWebImageDownloaderTests.m

This merge request fixes / refers to the following issues: #2929
Added API:
+ `SDWebImageDownloaderOperation.metrics`
+ `SDWebImageDownloadToken.metrics`
+ `SDWebImageDownloader` now conforms to `URLSession:task:didFinishCollectingMetrics:`
+ `UIView.sd_latestOperationKey`, expose this API to help user to avoid `NSStringFromClass`
This API is used for metrics collection. For user who want this, the better way is to subclass `SDWebImageDownloaderOperation`, or using the NSNotification to observe the `SDWebImageDownloaderOperation` finished and get the property.
Using the API availibity to ensure this does not cause runtime issue on iOS 10-.

Added the URLSessionTaskMetrics support for downloader && operation, which can be used for network metrics

---

Package.swift
SDWebImage/MapKit/MKAnnotationView+WebCache.m

This merge request fixes / refers to the following issues: #2941 
I didn't upgrade to macOS Catalina 10.15.2 yet so I can not use Xcode 11.4 to test, can anyone help me to have a try ? @kylebrowning  @RyuX51 @maundytime @kiliankoe
You can change to use the dependency with the folk repo in Xcode 11.4 Package dependency
This based on the reply from Swift Forum: https://forums.swift.org/t/any-changes-to-spm-5-2-with-xcode-11-4-beta2-pure-objective-c-project-which-contains-multiple-targets-now-fail-to-integrate/34101/6

Try to fix the issue caused by Swift PM 5.2, the `sources` DSL only matches the individual source files, but not folder

---

SDWebImage/Core/SDWebImageDownloaderOperation.m
SDWebImage/Core/SDWebImageError.h
SDWebImage/Core/SDWebImageManager.m

This merge request fixes / refers to the following issues: #2943 
Some people find it a little confusing when receive the NSError reporeted by SDWebImage domain, so this time we can complete the localized description to point out the error reason.

Complete all the SDWebImage error code with the localized description, make it easy for debugging

---

SDWebImage/Core/SDWebImageDownloaderOperation.m

This merge request fixes / refers to the following issues: #2692 
This issue was catched by the unit testing report, see this:
https://travis-ci.org/SDWebImage/SDWebImage/builds/657128509?utm_medium=notification&utm_source=github_status
This issue is introduced in #2692

Fix the rare case when call `SDWebImageDownloaderOperation.cancel`, the completion block may callback twice

---

SDWebImage/Core/SDImageCache.h
SDWebImage/Core/SDImageCache.m
Tests/Tests/SDImageCacheTests.m
Tests/Tests/SDWebImageDownloaderTests.m

This merge request fixes / refers to the following issues: #2952 
Firstly check SDAnimatedImage, then check sd_imageFormat

Add a better check to handle the cases when call `storeImage` without  imageData

---

SDWebImage/Core/SDImageCacheDefine.m
SDWebImage/Core/SDImageLoader.m
SDWebImage/Core/SDWebImageDefine.h
SDWebImage/Core/SDWebImageDefine.m
SDWebImage/Core/SDWebImageManager.m
SDWebImage/Core/UIView+WebCache.m

In histroy, we have a context option from 4.x, the `SDWebImageContextCustomManager`.
This options previouslly used for advanced customazation because 4.x have no control like 5.x's context option about transformer, cache serializer. They have to create a dummy manager instance.
But, this design is little suck for user who want to simply change a property, like provide a custom loader to load Photos URL via [SDWebImagePhotosPlugin](https://github.com/SDWebImage/SDWebImagePhotosPlugin). The readme here point it out you should do like this:
```objective-c
// Assign loader to custom manager
SDWebImageManager *manager = [[SDWebImageManager alloc] initWithCache:SDImageCache.sharedImageCache loader:SDImagePhotosLoader.sharedLoader]; …
```

Feature add context option for cache, loader and coder, deprecated SDWebImageContextCustomManager

---

SDWebImage/Core/SDWebImageDownloader.m
SDWebImage/Private/SDAsyncBlockOperation.h
SDWebImage/Private/SDDeviceHelper.h
SDWebImage/Private/SDDisplayLink.h
SDWebImage/Private/SDFileAttributeHelper.h
SDWebImage/Private/SDFileAttributeHelper.m
SDWebImage/Private/SDImageAssetManager.h
SDWebImage/Private/SDImageCachesManagerOperation.h
SDWebImage/Private/SDWeakProxy.h

@kinarobin This PR seems be Missed during the 5.6.0.
The NSNotification remove observer should be added for iOS 8.0~9.0, or it will receive notification even object is dealloced and crassh.

Fix the NotificationCenter does not remove the observer and little private header garden

---

SDWebImage/Core/SDWebImageDownloaderOperation.m

The solution 3 for #2477. The difference from this and the solution 1 #2478 is that this one does not block the `progerssBlock` callback ratio.
This one can keep this behavior beside to fix the too frequently progressive decoding process:
> `progressive decoding && normal decoding for the same url, the progressBlock callback times should be equal.`

Keep the progressive decoding process only exist one per image download. Cancel the unused progressive decoding when full pixel data is available.

---

SDWebImage/Core/SDImageCache.h
SDWebImage/Core/SDImageCache.m
SDWebImage/Core/SDImageCacheDefine.h
SDWebImage/Core/SDImageCachesManager.m
SDWebImage/Core/SDWebImageDefine.h
SDWebImage/Core/SDWebImageDefine.m
SDWebImage/Core/SDWebImageManager.m
Tests/Tests/SDImageCacheTests.m
Tests/Tests/SDWebImageDownloaderTests.m
Tests/Tests/SDWebImageManagerTests.m
Tests/Tests/SDWebImageTestCache.h
Tests/Tests/SDWebImageTestCache.m
Tests/Tests/SDWebImageTestLoader.h
Tests/Tests/SDWebImageTestLoader.m

This PR supports the user, to specify where to query cache from:
+ Memory Cache Only
+ Disk Cache Only
+ Both (Default)
This is useful for cases when we want to do some prefetch only for memory cache (because it's fast and sync), but not want to access to disk cache.

Added new query cache type support, including the SDImageCache API and context option

---

WebImage/SDWebImage.h

This merge request fixes / refers to the following issues: #2969 
The compiler will synthesize the `${FrameworkName}VersionNumber` and `${FrameworkName}VersionString` symbol, so this naming should match SDWebImage.
@iamlion

Fix the issue for Carthage/SwiftPM framework version symbols, this should match the framework name SDWebImage, or will get a link error when used

---

SDWebImage/Core/SDImageCoder.h
SDWebImage/Core/SDImageCoder.m
SDWebImage/Core/SDImageIOAnimatedCoder.m
SDWebImage/Core/SDImageIOCoder.m
Tests/Tests/SDImageCoderTests.m

This PR introduce 3 options for Image Encoding (works both on Animated Image as well as possible Vector Image).
+ Thumbnail Encoding (Max Pixel Size): Allows you to limit the encoded image pixel size, Image/IO have [kCGImageDestinationImageMaxPixelSize](https://developer.apple.com/documentation/imageio/kcgimagedestinationimagemaxpixelsize)
+ Max Encoded File Size: This used for JPEG/HEIF format which can limit the output size. It looks like the `compressionQuality`, but you don't need to guess which quality to use, provide your desired file size and encoder calculate the quality for you.
+ Specify the background color , when encode image contains alpha into a image format which does not support alpha, like JPEG. Image/IO have …

Feature supports encoding options like max file size, max pixel size, as well as background color when using JPEG for alpha image 

---

SDWebImage/Core/NSData+ImageContentType.h
SDWebImage/Core/NSData+ImageContentType.m
Tests/Tests/SDCategoriesTests.m

The original code comes from me 😅 , see https://github.com/SDWebImage/SDWebImage/blame/c1df782869955cc505a9304637599c606ba04477/SDWebImage/NSData+ImageContentType.m
However, at that time, maybe I think all the UTI type we can handle is limited, and no externel Image Decoder support as current SDWebImage 5.0's design. So I hardcode that PNG for backup.
This design cause issue now, because we have custom decoder, example, the AVIF decoder: [SDWebImageAVIFCoder](https://github.com/SDWebImage/SDWebImageAVIFCoder). When user accidently pass the `SDImageFormatAVIF` into this `sd_UTTypeFromImageFormat:` method, a `PNG` will returned. And when he encode again, it will cause failsure.
So, instead, a better way to solve this problem, …

Change the behavior to return the abstract type for unknown image format, this  can solve the accident issue for custom coder who provide a new format

---

SDWebImage/Core/SDAnimatedImageView.m

This code maybe wrong coding style, the `A = B = C` will actually is not correct. Mabye this is caused by some code refactory typo.
This does not effect the runtime behavior, just source code warning.

Fix the wrong value assignment for SDAnimatedImageView code on macOS, warning

---

SDWebImage/Core/SDWebImageManager.m

* [] I have added the required tests to prove the fix/feature I am adding
See https://github.com/SDWebImage/SDWebImage/issues/2975.

Don't copy attributes from originalImage to transformedImage when caching transformedImage

---

SDWebImage/Core/SDAnimatedImagePlayer.m

This does not work as expected:

Fix that when first play animated image and use maxBufferSize to 0, the calculation does not works (The CGImage is nil)

---

SDWebImage.xcodeproj/project.pbxproj
SDWebImage/Core/SDImageTransformer.m
SDWebImage/Core/UIImage+Transform.m
SDWebImage/Private/NSBezierPath+SDRoundedCorners.h
SDWebImage/Private/NSBezierPath+SDRoundedCorners.m
SDWebImage/Private/UIColor+SDHexString.h
SDWebImage/Private/UIColor+SDHexString.m
Tests/Tests/SDImageCoderTests.m
Tests/Tests/SDImageTransformerTests.m
Tests/Tests/SDUtilsTests.m

This merge request fixes / refers to the following issues: #2979 #2978 #2833 
This close #2979, close #2978 close #2833

Rename the private header `UIColor+HexString` and `NSBezierPath+SDRoundedCorners` with SD prefix, to avoid the conflict when using CocoaPods

---

SDWebImage/Core/SDImageCoder.h
SDWebImage/Core/SDImageCoder.m
SDWebImage/Core/SDImageIOAnimatedCoder.m
SDWebImage/Core/SDImageIOCoder.m
Tests/Tests/SDImageCoderTests.m

This merge request fixes / refers to the following issues: #
This introduce the feature to allow user to embed a thumbnail image into some format, like JPEG/HEIF/AVIF. Their data container can host multiple thumbnails.
User request: https://github.com/SDWebImage/SDWebImageHEIFCoder/commit/32d0e9a6d2a87eea5dcc85ce7388418693d0afd4

Feature: Encoding options supports embed thumbnail (works for JPEG/HEIF/AVIF)

---

SDWebImage/Core/UIView+WebCache.m
Tests/Tests/SDWebCacheCategoriesTests.m

This PR change two things:
1. `.setImageOperationKey` now pass through from upstream to downstream even user don't specify the value. The operation key can be a hint for other component, like `cache`, `downloader` to identify where the operation came from
2. `.customManager` should be stripped after used, because this can have potential retain cycle issue.

Feature pass the set operation key into context option from upstream. Fix the potential retain cycle if user use custom manager

---

SDWebImage/Core/SDWebImageDownloaderDecryptor.h
SDWebImage/Core/SDWebImageDownloaderRequestModifier.h
SDWebImage/Core/SDWebImageDownloaderRequestModifier.m
SDWebImage/Core/SDWebImageDownloaderResponseModifier.h
SDWebImage/Core/SDWebImageDownloaderResponseModifier.m
Tests/Tests/SDWebImageDownloaderTests.m

Don't need to repeat the code...
See user request from https://github.com/SDWebImage/SDWebImageSwiftUI/issues/99
Currently user have to write verbose code to provide HTTP header/method/body:
```swift
[.downloadRequestModifier: SDWebImageDownloaderRequestModifier {
var request = $0
request.setValue("MyValue", forHTTPHeaderField: "MyHeader")
return request
}]
```
Now we can use 
```swift
[.downloadRequestModifier: SDWebImageDownloaderHTTPRequestModifier(headers: ["Foo": "Bar"])
```
Though it's still ugly, but more simple than previus version :)
This API on Swift in SDWebImage 6.0, will have a more Swify one, like
```swift
[.download(.requestModifier(.headers(["Foo": "Bar"])))]
```
Note:
The naming maybe need to contains the …

Add the convenient request/response modifier, which provide HTTP header directly

---

SDWebImage.xcodeproj/project.pbxproj
SDWebImage/Core/SDWebImageTransition.h
SDWebImage/Core/SDWebImageTransition.m
SDWebImage/Core/UIView+WebCache.m
SDWebImage/Private/SDWebImageTransitionInternal.h

This is useful for macOS user who want to easily use transition. Most users don't have custom timing function use cases.
The `timingFunction` API will be removed in 6.0.0

Added the convenient transition options for macOS user. Deprecate the old timingFunction, which can use System API to achieve

---

SDWebImage.xcodeproj/project.pbxproj
SDWebImage/Core/SDWebImageOperation.m
SDWebImage/Core/SDWebImagePrefetcher.m
SDWebImage/Private/SDAsyncBlockOperation.m
Tests/Tests/SDWebImageDownloaderTests.m

This merge request fixes / refers to the following issues: #2998 
This silly problem introduced in #2645 , but until today that #2998 mentioned this.
The Objective-C protobol conforms use a Category declaration, but without any implementation files, so compiler will not tell the original Class (`NSOperation`) conforms protocol (`SDWebImageOperation`) here.
Also, this fix some thread-safe issue from the Foundation, the NSOperation subclass should use the correct way to override the `isFinished` and `isExecuting`

Fix the issue that NSOperation conforms to `SDWebImageOperation` check failed. And fix the SDAsyncBlockOperation cancel logic

---

SDWebImage/Core/SDWebImageError.h
SDWebImage/Core/SDWebImageManager.h
SDWebImage/Core/SDWebImageManager.m

The feature to support removal of black list can solve the use case that some URL may have some extra condition to un-block, like the server recovery back after some retry. (Not always have to use `.retryFailed`)
The error code can makes it easy to investigate the issue, and produce a localized error report.

Mark the black list formal error code, support remove the failed URL from black list

---

SDWebImage/Core/SDWebImageDownloaderOperation.m

This merge request fixes / refers to the following issues: #3004 
This close #3004. @kinarobin @rahulbbit 
Some user will get misunderstanding for currrent error description: `Downloaded image decode failed`.
So this PR distinguish the `image is nil, decode failed` and `image width or heigh is 0, not enough pixels`.

Polish the error description between image decode failed and image size is 0

---

SDWebImage.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
SDWebImage/Core/SDAnimatedImageView.h
SDWebImage/Core/SDAnimatedImageView.m
Tests/Tests/SDAnimatedImageTest.m

Sometimes we set up a GIF and don't want it to play right away, so we need to add a control
Added autoplay control property to AnimatedImageView (autoPlayAnimatedImage)
(reference YYAnimatedImageView)

Added autoplay control property to AnimatedImageView (autoPlayAnimatedImage)

---

SDWebImage/Core/SDImageIOCoder.m

This is not the documented behavior
The current `SDImageCoderEncodeMaxPixelSize` when size is larger than image itself size, for example, 10000*10000, will cause a upscale to that size. This is not what the designed behavior.
This is because `kCGImageDestinationImageMaxPixelSize` does not have a limit to the size. We need do soemthing like SDWebImageWebPCoder

Fix the issue that ImageIO max pixel size larger than image size will cause a upscale

---

.travis.yml

Travis finally supports macOS Catalina. See: https://changelog.travis-ci.com/xcode-11-4-1-is-now-available-149423

Update the Travis-CI to use Catalina and enable macCatalyst test case

---

SDWebImage/Core/SDAnimatedImagePlayer.m
Tests/Tests/SDAnimatedImageTest.m

Sometimes I need to choose a specific image from the animation - last one, in non animated state case. Current version returns nil image in animationFrameHandler, which is not what I expect.

SDAnimatedImagePlayer seek returning nil image fix

---

SDWebImage/Core/SDWebImageDownloaderRequestModifier.m

NSURLRequest.HTTPMethod should not be nil, the default value should be `GET`. Or, when request some specify HTTP URL contains 302 redirect, a runtime crash will occurs.
See screenshot here: https://github.com/DylanVann/react-native-fast-image/pull/691#issuecomment-639413527
The react-native-fast-image PR already test this behavior.
@kinarobin

Fix the issue that the NSURLRequest method should not be nil, which may cause Crash

---

SDWebImage/Core/SDImageIOAnimatedCoder.m

This change is based on https://github.com/SDWebImage/SDWebImage/pull/3015, which fix the issue of `maxPixelSize`logic check in SDImageIOCoder.m. However, for other coder like HEICCoder that used SDImageIOAnimatedCoder as base class, the issue is not resolved. So I fix it and hope to ship the fix on 5.8.2

Fix the `maxPixelSize` logic issue will cause a upscale in SDImageIOAnimatedCoder

---

SDWebImage/Core/SDAnimatedImageView.m

This merge request fixes / refers to the following issues: #3040
This solve #3040 
UIKit some internal behavior changes and we should always update the render layer if we have no `currentFrame`

Fix the issue that SDAnimatedImageView can not render static image on iOS 14.

---

SDWebImage/Core/SDAnimatedImageView.m

This merge request fixes / refers to the following issues: #3043 
In the #3043, we apply a hot-patch to use CALayer.contents for rendering static images. However, that breaks the vector images which UIImageView supports.
For example, previouslly, we can render SVG/PDF images in dynamic sizes via [SVGCoder](https://github.com/SDWebImage/SDWebImageSVGCoder) and [PDFCoder](https://github.com/SDWebImage/SDWebImagePDFCoder). That #3043 breaks this after v5.8.2 version.
Should call super method if need for best compatibility. This is the best solution to keep function.

Fix the issue of iOS 14 vector image rendering on SDAnimatedImageView

---

SDWebImage/Core/SDImageIOAnimatedCoder.m

See issue report from Gitter:
No actual solution, but let's have a try.

Try to copy the local NSMutableDictionary before calling CGImageSourceCreateImageAtIndex, try to solve the rare crash inside ImageIO call stack.

---

SDWebImage/Core/UIView+WebCache.h
SDWebImage/Core/UIView+WebCache.m
Tests/Tests/SDWebCacheCategoriesTests.m

Fix #3011 
Using `sd_latestOperationKey` to identify whether the image loading has been canceled. If so, it is unnecessary to set an image to view.

Fix race condition when use transition but canceling an operation

---

SDWebImage/Core/SDImageCache.h
SDWebImage/Core/SDImageCache.m
Tests/Tests/SDImageCacheTests.m
Tests/Tests/SDImageCoderTests.m

This merge request fixes / refers to the following issues: close #3050
This PR solve the feature request from #3050.
If you want to change the shared image cache's path, use like this:
```objective-c
- (void)applicationDidFinishLaunching:(NSNotification *)aNotification {
// Insert code here to initialize your application
SDImageCache.defaultImageCacheDirectory = [NSFileManager.defaultManager containerURLForSecurityApplicationGroupIdentifier:@"my.app.group.id"];
}
```

Supports the user to customize the default disk cache directory, which can be used to share cache for App && App Extension

---

SDWebImage/Core/SDImageCoderHelper.h
SDWebImage/Core/SDImageCoderHelper.m
Tests/Tests/SDImageCoderTests.m

This merge request fixes / refers to the following issues: close #3056 
This add the protect code when the tile rectangle is too small to create (The rectangle height less than 1).
However, because we have a hack protect code which does not allows you pass `limitBytes` arg to less than 1MB.
Which means, to hit this race condition, your original full image's pixel width should be larger than **87381**. Not possible in real world :)
Calculation:
Assume limitBytes passed 1MB (1024*1024 Bytes);
Assume tile height use 1 pixel
Assume bytes per pixel use 4 (RGBA)
`width = 1024 * 1024(bytes) / 4(bytes per pixel) / 3(tile count) / 1(tile height) = 87381.333333`

Add the support to pass small bytes to `decodedAndScaledDownLargeImage`, which always scale down (at least 1x1 pixel) but not return the original size

---

SDWebImage/Core/SDWebImageTransition.m

[SDWebImageTransition] Fix: `duration` is not used in the convenience initializers.

[SDWebImageTransition] Fix: `duration` is not used in convenience initializers.

---

SDWebImage/Core/SDAnimatedImage.m

Allow overriding default coders for known image format
The coder in the end of coders should has the highest priority.

Fix coder priority in SDAnimatedImage

---

Tests/Tests/SDAnimatedImageTest.m

Test case for coder priority in SDAnimatedImage

---

SDWebImage/Core/UIView+WebCache.m
Tests/Tests/SDWebCacheCategoriesTests.m

This merge request fixes / refers to the following issues: [3107](https://github.com/SDWebImage/SDWebImage/issues/3107)
Please see the [issue description here](https://github.com/SDWebImage/SDWebImage/issues/3107). Note that I have successfully written a test case that will fail in the production release of SDWebImage, version 5.9.3, but passes with my fix applied.
(FYI -- the failing tests in Travis as of 10/14/2020 are in the Apple TV part of the code - which I did not touch - and these failing tests also fail on my local machine when I run the tests against the tip of master.)

Fix race condition when using transitions that are canceled and then switched to a new transition or load operation

---

SDWebImage/Core/SDImageCache.m
Tests/Tests/SDImageCacheTests.m

This merge request fixes / refers to the following issues: ... 
#3104  should not affect the way which the disk image is obtained.

Fixed the store cache type was specified to `SDImageCacheTypeDisk `  that no pictures were obtained when the disk had pictures

---

SDWebImage/Core/SDAnimatedImageView.h
SDWebImage/Core/SDAnimatedImageView.m
Tests/Tests/SDAnimatedImageTest.m

Add `animationImages` support when using `SDAnimatedImageView`.
...

Add animationImages support when using SDAnimatedImageView

---

SDWebImage/Core/SDAnimatedImagePlayer.m
SDWebImage/Core/SDImageCachesManager.m
SDWebImage/Core/SDImageCodersManager.m
SDWebImage/Core/SDImageLoadersManager.m
SDWebImage/Core/SDMemoryCache.m
SDWebImage/Core/SDWebImageDownloader.m
SDWebImage/Core/SDWebImageManager.m
SDWebImage/Core/SDWebImagePrefetcher.m
SDWebImage/Private/SDImageAssetManager.m
SDWebImage/Private/SDImageCachesManagerOperation.m
SDWebImage/Private/SDInternalMacros.h

dispatch_semaphore is not always a good solution for locking, especially on `NSMutableArray/MutableDictionary` lock for add/remove operation.
And semaphore will cause the QoS inverse, see: https://mp.weixin.qq.com/s/GXhQDQj0cu2pFTBUUb9S5w
So, instead, we'll always perfer the latest os_unfair_lock: https://developer.apple.com/documentation/os/synchronization
At first I want to use `pthread_mutex`, however, I found that mutex will cause the thread into sleep, and have a heavy cost for basic opereration our SDK's usage (that `NSMutableArray/MutableDictionary` lock).
For this task, the deprecated `OSSpinLock` is still the best choice.
Benchmark here: ![](https://cloud.githubusercontent.com/assets/1570382/16460024/17a2491c-3e2e-11e6 …

Replace all current dispatch_semaphore usage into the os_unfair_lock, use OSSpinLock for lower firmware

---

Configs/Module-Shared.xcconfig
Examples/SDWebImage Demo/SDWebImage Demo-Prefix.pch
Package.swift
Podfile
README.md
SDWebImage.podspec
SDWebImage/Core/SDImageAPNGCoder.m
SDWebImage/Core/SDImageHEICCoder.m
SDWebImage/Core/SDWebImageDownloaderOperation.m
SDWebImage/Core/SDWebImageIndicator.m
Tests/Tests/SDWebImageDownloaderTests.m

This follows Apple's App Store submit rule, and user request from the dependency. Similar to last year's #2372 
> Starting April 2020, all new apps and app updates will need to be built with the iOS 13 SDK and support the all-screen design of iPhone XS Max or later.
See: https://developer.apple.com/news/?id=09102019a
Many issues and users complain about the current iOS 8+ deployment target version:
This close #3097
This close #3085
This close #3054 
Even some from other components (because WebPCoder or SwiftUI depends on this Core)
This close https://github.com/SDWebImage/SDWebImageSwiftUI/issues/140
This close https://github.com/SDWebImage/SDWebImageWebPCoder/pull/43
Previouslly I decide to release this on SDWebImage 6.0, but …

Bumped the min deployment target version to iOS 9, macOS 10.11. Bumped the min Xcode version to Xcode 11

---

SDWebImage/Core/SDWebImagePrefetcher.m
SDWebImage/Private/SDInternalMacros.h

If the deployment target was newer than the target that os_unfair_lock() became available deprecation warnings were generated for use of OSSpinLock. Now OSSpinLock isn't used if the deployment target is >= the OS version where os_unfair_lock() became available.
This merge request fixes / refers to the following issues: #3136
Fix deprecation warnings for OSSpinLock
If the deployment target was newer than the target that os_unfair_lock() became available deprecation warnings were generated for use of OSSpinLock. Now OSSpinLock isn't used if the deployment target is >= the OS version where os_unfair_lock() became available.
If you want to test this manually you can temporarily set the iOS Deployment target in the SDWebImage project to 11 or newer (and the same for the other OS targets) and …

Fix deprecation warnings for OSSpinLock

---

SDWebImage/Core/SDWebImageDownloaderOperation.m
Tests/Tests/SDWebImageDownloaderTests.m

This merge request fixes / refers to the following issues: #3141
This close #3141 
Now we do not relay on URLSession delegate timing, directly callback when cancelled.

Fix the race condition when user cancel the network loading will not trigger the completion block

---

SDWebImage/Core/SDWebImageDownloaderOperation.m

This merge request fixes / refers to the following issues: #3145
This may be the solution to clone #3145 #3106
I checked the Apple's NSOperation documentation, it does not talked about this exception:
https://developer.apple.com/library/archive/documentation/General/Conceptual/ConcurrencyProgrammingGuide/OperationObjects/OperationObjects.html#//apple_ref/doc/uid/TP40008091-CH101-SW38
But anyway, let's have a try.
> Exception Detail:
>

Fix the case that we setFinished=YES before NSOperation started. This may cause exception from Foundation

---

SDWebImage/Core/SDImageCache.m

Fixed the store cache type was specified to `SDImageCacheTypeDisk ` that pictures shouldn't cache to memory.

---

README.md

**This merge request fixes / refers to the following issues:** "any 3.x version up to 3.7.6" link in the README.md takes you to a 404 page. It seems like person who added that link forgot to include the `releases/` component in the URL.
This pull request fixes the "any 3.x version up to 3.7.6" in the README.md file.

Fix link to v3.7.6 in README.md

---

SDWebImage/Core/SDWebImageDownloaderOperation.m

- Did not add tests because it's super hard to test a memory pressure bug.
- Not necessary, IMO.
This is an attempt at addressing [Out of memory crashes immediately prior to decoding the image](https://github.com/SDWebImage/SDWebImage/issues/2353). I don't expect this to solve all of the cases of OoM crashes that would get reported to that thread, but it should address what looks to me to be the most common one (and is the one affecting my work).
There was previously a related work done to reduce memory usage of the SDWebImageDownloadOperation decoding work, [here](https://github.com/SDWebImage/SDWebImage/pull/2624). This is fine for reducing the amount of memory used during decoding, but the crashes I and others in that …

Don't unnecessarily copy image data in the Download Operation

---

SDWebImage/Core/SDImageLoader.h
SDWebImage/Core/SDImageLoader.m
SDWebImage/Core/SDWebImageDownloaderOperation.m
Tests/Tests/SDWebImageDownloaderTests.m
Tests/Tests/SDWebImageManagerTests.m

This PR polish current progressive decoding feature.
We using the progressive decoder only for the `progressBlock` callback and render. When all data downloaded, we destory the decoder and re-decode again using the full image decoding.
Now, when prorgessive decoder exist, we will always use the progressive decoder to decode the final image. This can save extra CPU usage and RAM peak.
Note: Now we will not provide the full image (last one during progressive decoding) inside the `progressBlock`, which looks like a bug (Progress means, not finished, but not the finished image)
Testing with GIF and APNGs, the progressive decoded final image produce the same visual effect as normal full decoding. So it's OK to use.

Increase progressive decoding performance by using the progressive decoder's result instead of re-decoding the full image data

---

SDWebImage/Core/SDImageCodersManager.m
SDWebImage/Core/SDImageIOAnimatedCoder.m
Tests/Tests/SDImageCoderTests.m

Don't encode/decode image when app will terminated

---

SDWebImage/Core/SDImageIOAnimatedCoder.m
SDWebImage/Core/SDImageIOCoder.m
SDWebImage/Private/SDImageIOAnimatedCoderInternal.h
Tests/Tests/SDImageCoderTests.m

This MR revert the #3149 .
That #3149 seems result something testing failure, because the `UIApplicationWillTerminateNotification` will been sent from XCTest, or some rare cases which we don't want.
And the fix, actually has no meanings for then End-User. Because it happens when your App killed. This does only effect the metrics or crash report framework.

Revert the "Don't encode/decode image when app will terminate"

---

SDWebImage/Core/SDWebImageDownloader.m
SDWebImage/Core/SDWebImageDownloaderOperation.m

This fix the NSException from URLSession in rare cases:
> Task created in a session that has been invalidated

Ensure the invalid URLSeesion will receive the cancel callback and does not trigger the any exception from framework

---

SDWebImage/Core/SDWebImageDownloaderOperation.h

Fix spelling error:   
tokent -> token

Fix spelling error in SDWebImageDownloaderOperation

---

SDWebImage/Core/SDWebImageManager.m

This is a bug that breaks current transformer function.
Seems related to #2360 refactory changes. Mistake code.

Fix the bug that when querying original cache miss, the download process will be skipped. This is not designed behavior.

---

Configs/Module-Shared.xcconfig
SDWebImage.xcodeproj/project.pbxproj
SDWebImage/Core/UIView+WebCache.m

Fix the warning, enable `APPLICATION_EXTENSION_API_ONLY` for all framework target

---

SDWebImage/Core/SDImageCache.m
Tests/Tests/SDImageCacheTests.m

Support `SDImageCacheDecodeFirstFrameOnly` and `SDImageCacheMatchAnimatedImageClass`
This may be a little related to #3230 . But not solve them all.
From the design of this framework, the `SDAnimatedImage` custom class, should provide the top level priority.
Which means:
+ If there are `SDAnimatedImage` custom class instance in memory cache: Always query and return it, whatever caller is `UIImageView` or `SDAnimatedImageView`
+ If there are `UIImage` not custom class instance in memory cache: If `matchesImageClass`, ignore it and override with new created one `SDAnimatedImage`.
This can ensure we always prefer the `SDAnimatedImage` over `UIImage`, so that we do not replace same instance once by another. (If we put `UIImage` …

Fix imageFromCacheForKey with options and context behavior, matching the async version one.

---

SDWebImage/Core/SDAnimatedImage.m
SDWebImage/Core/SDImageCoderHelper.m
SDWebImage/Core/UIImage+MemoryCacheCost.m
SDWebImage/Core/UIImage+Metadata.h
SDWebImage/Core/UIImage+Metadata.m
Tests/Tests/SDAnimatedImageTest.m
Tests/Tests/SDCategoriesTests.m
Tests/Tests/SDImageCoderTests.m

Also, Fix one issue when input UIAnimatedImage contains only 1 image
Fix test case from #3237 as well. Which NSImage does not have `images`.

Added `sd_imageFrameCount` convenient API for UIAinmatedImage/NSBitmapImageRep

---

SDWebImage/Core/SDWebImageDownloaderOperation.m

See: https://github.com/SDWebImage/SDWebImageSwiftUI/issues/153
When the server, like Nginx, set `ssl_verify_client` to optional, client side can optional provide the cert, so the line changes here should not always use `cancelAuthenticationChallenge` to cancel the request.
Instead, use the `performDefaultHandling` will allows this request and matches URLSessions' default implementation

Change the default delegate method to allows optional cert in SSL verify, matches URLSession's behavior

---

SDWebImage/Core/SDAnimatedImageRep.m

Recently I got `SDAnimatedImageRep` related crashes in my app when loading some specific animated webp images.
After spending some time diving deep into this issue, I found that `SDAnimatedImageRep` has wrong `copy` semantic and thus when copy operations performed on `NSImage`s with this type of backing source, the underlying `CGImageSourceRef` actually refers to released address space and thus crashes the whole app.
This pull request make `SDAnimatedImageRep` confirm to correct copy semantic. Since [ImageIO](https://developer.apple.com/documentation/imageio) provides no public API for direct copying of `CGImageSource` instances, a retain operation is performed on the underlying `CGImageSource` instance. Technically, two …

Make SDAnimatedImageRep confirms to correct copy semantic

---

SDWebImage/Core/SDImageCoderHelper.m

This merge request fixes / refers to the following issues:  fix https://github.com/SDWebImage/SDWebImage/issues/3311
When we calculate totalDuration in [SDImageCoderHelper animatedImageWithFrames:], we have a serious floating point error.
For example, when we calculate totalDuration using an APNG file ( frame.duration is 0.02, frameCount is 313)，the result is 5.947, which should actually be 6.25.
Floating-point errors are caused by:
- frameDuration = [delayTimeUnclampedProp doubleValue]; 169 in SDImageIOAnimatedCoder.m （Floating point machine error）
- totalDuration += duration; 65 in SDImageCoderHelper.m(totalDur
ation should be NSTimeInterval not NSUInteger, NSUInteger duration = frame.duration * 1000 Magnify the error)
Set totalDuration to NSTimeInterval and add directly to …

fix: Eliminates accumulated floating point errors.

---

SDWebImage/Core/SDImageCoderHelper.m
Tests/Tests/SDImageCoderTests.m

… the image completely due to the loss of precision.
This code is handling the rendering of the last tile if the height of the tile is not equally distributed to the height of the image.
SDImageCoderHelper:451
```
if( y == iterations - 1 && remainder ) {
float dify = destTile.size.height;
destTile.size.height = CGImageGetHeight( sourceTileImageRef ) * imageScale;
dify -= destTile.size.height;
// !!! Problems in this line !!!
destTile.origin.y += dify;
}
```
Since `sourceTile` is always divisible, there is no loss of precision.
SDImageCoderHelper:417
```
sourceTile.size.height = MAX(1, (int)(tileTotalPixels / sourceTile.size.width));
```
The last `sourceTile` always fills the image just right. 
So when rendering the last tile, …

Fix #3320 `decodedAndScaledDownImageWithImage` does not render the image completely

---

SDWebImage/Core/SDImageCache.m
Tests/Tests/SDWebCacheCategoriesTests.m

This merge request fixes / refers to the following issues: https://github.com/SDWebImage/SDWebImage/issues/3042
I expected that when I gave ```SDimageCacheQueryDiskDataSync``` with sd_setImage, the whole disk query process would be synchronous.
```
imageView.sd_setImage(
with: url,
options: [.queryDiskDataSync],
context: nil
)
```
However, internally, the completion was being called async. And it caused cell blink.
The reason is to perform the queryDiskBlock in ioQueue as shown below.
```
// Query in ioQueue to keep IO-safe
if (shouldQueryDiskSync) {
dispatch_sync(self.ioQueue, queryDiskBlock);
} else {
dispatch_async(self.ioQueue, queryDiskBlock);
}
```
And in the ioQueue, a completion was called with dispatch_main_asyc_safe, which was performed asynchronously.
(jumping to next runloop) …

Fix imageView blinks with option 'SDImageCacheQueryDiskDataSync'

---

.github/workflows/CI.yml
SDWebImage/Core/SDImageCoderHelper.m
Tests/SDWebImage Tests.xcodeproj/project.pbxproj
Tests/Tests/SDImageTransformerTests.m

See #3330.
This PR will prefer to use input CGImage's pixel format (if available) to create CGContext.
If failed, use the old BGRX8888 instead.
On iOS 15, seems always using BGRX8888 is not safe and will cause a black image after `CGContextDrawImage`
Test case need to update the Travis CI to always use the iOS 15+ simulator. Added test case `test21BMPImageCreateDecodedShouldNotBlank `

Workaround the iOS 15+ Force Decode may return black image because of CoreGraphics

---

Examples/SDWebImage OSX Demo/ViewController.m
SDWebImage/Core/SDImageCoderHelper.m
SDWebImage/Core/SDImageGraphics.m
SDWebImage/Core/UIImage+Transform.m
Tests/Tests/SDWebImageManagerTests.m

See #3330 and #3333.
The previous fix in #3332 is not good because user will face the log from CoreGraphics when input bitmap info (for example, RGB888) does not fit in Core Graphics limit. The log is annoying and no way to supress that.
The root case of this is Apple's bug. I've fired radar: FB9958017
Reproduce demo:
https://github.com/dreampiggy/CGContextDrawImageBug
Instead of hacking with Apple. I decide to minimize the effect.
1. For normal UIImage force decode
via `[SDImageCoderHelper decodedImageWithImage:]`, we prefer to use new [UIGraphicsImageRenderer](https://developer.apple.com/documentation/uikit/uigraphicsimagerenderer). Which translate the bitmap by UIKit itself, so we don't assume one. The image renderer was …

Workaround iOS 15+ force decode again using Image Renderer(preferred) and RGB888

---

SDWebImage/Core/SDGraphicsImageRenderer.m
SDWebImage/Core/SDImageGraphics.m
SDWebImage/Core/SDWebImageDefine.m
SDWebImage/Private/SDImageAssetManager.m

I got the following crash from our production app:
```
Incident Identifier: null
CrashReporter Key:   null
Hardware Model:      null
Code Type:           X86-64 (Native)
Parent Process:      ??? [1]
Date/Time:           2022-01-19 09:06:20.300 +0800
OS Version:          Mac OS X 10.11.6 (15G22010)
Report Version:      11
Exception Type:  EXC_CRASH
Exception Codes: 0x0000000000000000, 0x0000000000000000
Exception Note: EXC_CORPSE_NOTIFY
Triggered by Thread:  120
Application Specific Information:
abort() called
*** error for object 0x7ff2a3af1e50: double free
Thread 120 Crashed:
0   libsystem_kernel.dylib          0x00007fff87566f06 __pthread_kill + 10
1   libsystem_pthread.dylib         0x00007fff9124c4ec pthread_kill + 90
2 …
```

Fix a crash of accessing -[NSScreen backingScaleFactor] from background thread.

---

SDWebImage/Core/SDDiskCache.m

While experimenting with an app using SDWebImage today I noticed that SDWebImage is using the flavor of `+fileURLWithPath:` that doesn't specify whether or not the path is to a directory or a file. In this case we know that the path is to a file, and the version of `+fileURLWithPath:` where you specify `isDirectory` is faster and requires less i/o than the the one that doesn't.
I ran some light tests locally comparing the two versions of this method, the change this PR introduces is ~5x faster.
The overall magnitude of the speedup isn't tremendous, just fractions of milliseconds, but still it's a small improvement!

Small performance improvement to generating file URLs in SDDiskCache -setData:forKey:

---

.github/workflows/CI.yml

Restrict the GitHub token permissions only to the required ones; this way, even if the attackers will succeed in compromising your workflow, they won’t be able to do much.
- Included permissions for the action. https://github.com/ossf/scorecard/blob/main/docs/checks.md#token-permissions
https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#permissions
https://docs.github.com/en/actions/using-jobs/assigning-permissions-to-jobs
[Keeping your GitHub Actions and workflows secure Part 1: Preventing pwn requests](https://securitylab.github.com/research/github-actions-preventing-pwn-requests/)
Signed-off-by: naveen <172697+naveensrinivasan@users.noreply.github.com>

chore: Set permissions for GitHub actions

---

SDWebImage/Core/SDWebImageIndicator.m

This merge request fixes / refers to the following issues: #3352
Xcode 14 beta 1 broke compilation because there was no explicit include of `CoreImage` in `SDWebImageIndicator`. This was filed as #3352.

Fix #3352 Include necessary CoreImage import

---

SDWebImage/Core/SDImageIOAnimatedCoder.m
SDWebImage/Core/SDImageIOCoder.m
Tests/Tests/SDImageCoderTests.m

This fix the #3351.
Original image: 5250x3450
Provided PixelSize: 400x300
Result: 400x263

Fix the thumbnail pixel size calculation when preserveAspectRatio is true

---

SDWebImage/Core/SDImageIOAnimatedCoder.m
SDWebImage/Core/SDImageIOCoder.m
Tests/Tests/SDImageCoderTests.m

Allows user to provide size which one dimension is larger than image size size
Example - maxPixelSize: (200, 200), imageSize: (100, 400), result: (50, 200)
This logic error fix is from https://github.com/SDWebImage/SDWebImageWebPCoder/issues/64

Fix the encodeMaxPixelSize logic

---

SDWebImage/Core/SDImageCoderHelper.h
SDWebImage/Core/SDImageCoderHelper.m
Tests/Tests/SDImageCoderTests.m

The current WebP/HEIF/AVIF coder both copy paste the same code multiple times and have to fix one by one.
This PR introduce the API to avoid copy paste code and unify the logic.
Test case `test24ThatScaleSizeCalculation`
See https://github.com/SDWebImage/SDWebImageWebPCoder/issues/64

Added new API for custom coder better handling the thumbnail size

---

SDWebImage/Core/SDImageCache.m
SDWebImage/Core/SDImageCacheDefine.h
SDWebImage/Core/SDImageCacheDefine.m
SDWebImage/Core/SDImageIOAnimatedCoder.m
SDWebImage/Core/SDImageLoader.m
SDWebImage/Core/SDWebImageManager.m
SDWebImage/Core/UIImage+Metadata.h
SDWebImage/Core/UIImage+Metadata.m
SDWebImage/Private/SDAssociatedObject.m
Tests/Tests/SDWebImageManagerTests.m

See talk in #3360 
Current (5.10.0-5.12) SDWebImage's [Thumbnail Decoding](https://github.com/SDWebImage/SDWebImage/wiki/Advanced-Usage#thumbnail-decoding-550) feature does not work as expected, or can treat as bugs, including:
1. The thumbnail is always query and stored using the `Thumbnail-prefix` cache key, even if there are a full size image data in disk, it still need to download again and again. However, transformer image works as expected and will prefer full size data to do transforming without network.
2. The transformer image from full size disk cache, will always callback with `cacheType = none`, assume it from network. This is logic error.
3. The current `originalStoreCacheType` and `originalQueryCacheType` context …

Feature: Change thumbnail cache behavior as expected, share cache through different loading pipeline without extra download

---

SDWebImage/Core/SDImageCache.h
SDWebImage/Core/SDImageCache.m
SDWebImage/Core/SDWebImageDefine.h
SDWebImage/Core/SDWebImageOperation.h
SDWebImage/Core/UIView+WebCache.h
SDWebImage/Core/UIView+WebCache.m
SDWebImage/Core/UIView+WebCacheOperation.h
SDWebImage/Core/UIView+WebCacheOperation.m
Tests/Tests/SDWebCacheCategoriesTests.m

This PR use another way to solve the #3361 meet issue.
The root case of that problem is because of cache query cancel callback in async.
```
let imageView: UIImageView
imageView.sd_setImage(with: url, placeholderImage: placeholder1, options: .delayPlaceholder)
imageView.sd_cancelCurrentLoad()
imageView.sd_setImage(with: url, placeholderImage: placeholder2) // Actually, this will implicit call a cancel, because that operation key is the same
```
The imageView.image is set in this order:
1. imageView.image = placeholder2
2. imageView.image = placeholder1
3. imageView now rendering placeholder 1
4. Network finished, imageView.image = networkImage
The imageView.image is set in this order:
1. imageView.image = placeholder1
2. imageView.image = placeholder2
3. imageView now rendering …

Fix the case when user cancel the image loading for same URL in sequence cause placeholder mass

---

Examples/SDWebImage Demo.xcodeproj/xcshareddata/xcschemes/SDWebImage Watch Demo.xcscheme
SDWebImage/Core/SDWebImageManager.m

This merge request fixes / refers to the following issues: #3362
Fix the issue when thumbnail first and full size loading at the same time, the thumbnail image will write to memory with wrong key
The disk cache key is correct and does not get effected by this issue
The bug is introduced from #3362

Fix the issue when thumbnail and full size loading at the same time, the thumbnail image will write to memory with wrong key

---

SDWebImage/Core/UIImage+Transform.m
Tests/Tests/SDUtilsTests.m

This merge request fixes / refers to the following issues: `testSDGraphicsImageRenderer`
This fix the test cases for #3368

Fix sd_colorAtPoint and sd_colorsWithRect support for grayscale image (white and alpha)

---

SDWebImage/Core/SDImageCache.h
SDWebImage/Core/SDImageCoderHelper.h
SDWebImage/Core/SDImageCoderHelper.m
SDWebImage/Core/UIImage+ForceDecode.m
SDWebImage/Core/UIImage+Metadata.m

This merge request fixes / refers to the following issues: #3365 
This PR introduce new control enum to choose the force decoding solution.
The 5.13.0 #3340 is default, however, seems there are some performance regression.
So, instead this PR, we revert back the default solution as 5.12, and provide a user-control options to change the decode solution.
```objective-c
SDImageCoderHelper.defaultDecodeSolution = SDImageCoderDecodeSolutionUIKit; // Change the new way prefers iOS 15's new API
```

Added `SDImageCoder.defaultDecodeSolution` to control the force decode solution. Automatic by default

---

SDWebImage/Core/SDImageCache.m
SDWebImage/Core/SDWebImageManager.m
Tests/Tests/SDImageCacheTests.m
Tests/Tests/SDWebImageManagerTests.m

This merge request fixes / refers to the following issues: .
This fix the bug in #3374
The callback one is sync and another is async.
Test case added `test15CancelQueryShouldCallbackOnceInSync`
Feedback from: @anton-plebanovich

Fix the rare case when cancel an async disk cache query may cause twice callback

---

SDWebImage/Core/SDWebImageManager.m

This merge request fixes / refers to the following issues: #3393 
This fix the unbalanced of using lock (os_unfair_lock), which will cause crash

Fix the unbalanced lock which cause crash

---

SDWebImage/Core/SDAnimatedImageView.m

This merge request fixes / refers to the following issues: closing #3397
We should always provide a fallback solution to handle built-in NSImageView logic

Fix the switching from animated image rendering to static image does not works on macOS 11+

---

CHANGELOG.md
SDWebImage/Core/SDImageIOAnimatedCoder.m
SDWebImage/Core/SDImageIOCoder.m
SDWebImage/Private/SDImageIOAnimatedCoderInternal.h

This merge request fixes / refers to the following issues: #3273 https://github.com/onevcat/Kingfisher/issues/1844
From iOS 15+, `CGImageRef` internal data strcture has a filed called `_source`, which allows to retain the `CGImageSource` (via `CGImageSetImageSource/CGImageSourceGetImageSource`) instance.
This design used to support the API like [UIImage.imageByPreparingForDisplay](https://developer.apple.com/documentation/uikit/uiimage/3750834-imagebypreparingfordisplay?language=objc), which need the original image data like JPEG/HEIC for `CGImageDecompressor` to work.
For normal CGImage returned by CGImageSource, it's lazy and has no pointer to the original data. So Apple team decide to retain the CGImageSource itself, for just simple. (Learn more about what `CGImageDecompressor` do here …

Try to workaround iOS 15+ crash that CGImage retain the CGImageSource during animation image playing

---

.github/workflows/CI.yml
SDWebImage/Core/SDImageCoderHelper.m
SDWebImage/Core/SDImageIOAnimatedCoder.m
SDWebImage/Core/SDWebImageDefine.m
Tests/Tests/SDImageCacheTests.m

This merge request close #3407 
This PR add the same protect from https://github.com/SDWebImage/SDWebImageWebPCoder/pull/68 to the ImageIO Animated Decoder (like GIF/APNG)
This addition lock and performance cost only appies for incremental decoding, does not effect normal animation decoding. (Because Apple's ImageIO itself has lock internally, should)

Fix the potential out of bounds crash for ImageIO incremental animation decoding (like GIF)

---

Examples/SDWebImage Demo/MasterViewController.m
SDWebImage/Core/NSData+ImageContentType.h
SDWebImage/Core/NSData+ImageContentType.m
SDWebImage/Core/SDImageCacheDefine.m
SDWebImage/Core/SDImageCoder.h
SDWebImage/Core/SDImageCoder.m
SDWebImage/Core/SDImageIOAnimatedCoder.h
SDWebImage/Core/SDImageIOAnimatedCoder.m
SDWebImage/Core/SDImageIOCoder.m
SDWebImage/Core/SDWebImageDefine.h
SDWebImage/Core/SDWebImageDefine.m
SDWebImage/Private/SDImageIOAnimatedCoderInternal.h
Tests/SDWebImage Tests.xcodeproj/project.pbxproj
Tests/Tests/SDImageCoderTests.m

This is because file extension will cause ImageIO use different codec, which does not support all of them without context.
See sample file: 
SRW: https://img.photographyblog.com/reviews/samsung_nx10/sample_images/samsung_nx10_12.srw
NEF: https://res.cloudinary.com/dwpjzbyux/raw/upload/v1666474070/RawDemo/raw_vebed5.NEF
Apple's ImageIO decoder will use file extensions for some raw image check, because raw image like (NEF) may use the same encode structure like TIFF, the codec can not detech which one to parse without the caller's context.
1. If the image was loaded from SDWebImage (download by URL or from cache key), the `file extension` will passed to decoder, to use as hint
2. If there are no file extension in URL or cache key, …

Support use url.path or custom UTI hint passed to ImageIO, solve the TIFF/NEF/SRW raw image decoding with wrong size

---

SDWebImage/Core/SDImageCacheDefine.m
SDWebImage/Core/SDImageCoder.h
Tests/Tests/SDWebImageManagerTests.m

This merge request fix #3371
SDWebImage 5.13.2 introduce new `UIImage.sd_decodeOptions`, which retain the `SDWebImageContext`. However, it's dangerous. Because once you store a `SDImageCache` inside context options, this will cause retain cycle:
+ UIImage -> SDWebImageContextOptions -> SDImageCache -> SDMemoryCache(NSCache) -> UIImage
Now the SDImageCoderWebImageContext does not pass the built-in options, only custom options will be passed, and deprecated in 5.14.0

Quick fix the issue that UIImage.sd_decodeOptions cause retain cycle when pass custom cache in context option

---

SDWebImage/Core/SDImageCacheDefine.m
SDWebImage/Core/SDImageCoder.h
SDWebImage/Core/SDWebImageDefine.h
SDWebImage/Core/SDWebImageDefine.m
Tests/Tests/SDWebImageManagerTests.m

This can solve the retain cycle from the scratch, instead of hacking. See more in previous #3420 
And also, all the coders maintained by SDWebImage org and me, has already use the built-in coder options instead of custom web context option, this migration is not hard.
This PR is one the way to solve the issue that previous using hack in #3362 
From 5.14.0, if you request like below:
```swift
view.sd_setImage(with: url, options: [], context: [.thumnailPixelSize: CGSize(width: 100, height: 200)])
view.sd_setImage(with: url, options: [], context: [.thumnailPixelSize: CGSize(width: 101, height: 201)])
view.sd_setImage(with: url, options: [], context: [.thumnailPixelSize: CGSize(width: 102, height: 202)])
view.sd_setImage(with: …
```

Introduce SDWebImageContextImageDecodeOptions, deprecate SDImageCoderWebImageContext

---

SDWebImage/Core/SDImageCache.m
SDWebImage/Core/SDImageCacheDefine.h
SDWebImage/Core/SDImageCacheDefine.m
SDWebImage/Core/SDWebImageCacheSerializer.h
SDWebImage/Core/SDWebImageDefine.h
SDWebImage/Core/SDWebImageDownloader.m
SDWebImage/Core/SDWebImageDownloaderOperation.h
SDWebImage/Core/SDWebImageDownloaderOperation.m
SDWebImage/Core/SDWebImageManager.m
SDWebImage/Core/UIImage+Metadata.h
SDWebImage/Core/UIImage+Metadata.m
Tests/Tests/SDWebImageDownloaderTests.m
Tests/Tests/SDWebImageManagerTests.m
Tests/Tests/SDWebImageTestDownloadOperation.m

This merge request fixes / refers to the following issues: #3362 
This PR try to refactor current massive logic. **Because user may query the same URL multiple times, but with different thumbnail pixel size**.
Demo:
```swift
// assume url1 full size is 1000x1000 PNG
imageView1.sd_setImage(with: url1, options: [], context: [.imageThumbnailPixelSize: CGSize(width: 100, height: 100)])
imageView2.sd_setImage(with: url1, options: [], context: [.imageThumbnailPixelSize: CGSize(width: 200, height: 200)])
imageView3.sd_setImage(with: url1, options: [], context: [.imageThumbnailPixelSize: CGSize(width: 300, height: 300)])
imageView4.sd_setImage(with: url1, options: [], context: [.imageThumbnailPixelSize: CGSize(width: 400, height: 400)])
imageView5.sd_setImage(with: url1, options: [], context: …
```

Refactor the hack when multiple different thumbnail image requests called at the same time

---

SDWebImage/Core/SDImageCacheDefine.m
SDWebImage/Core/SDImageIOAnimatedCoder.m
SDWebImage/Core/SDImageIOCoder.m

This PR is additional for the https://github.com/SDWebImage/SDWebImage/pull/3419
This try to avoid the ImageIO's log about
> extractOptions:147: *** unknown hint identifier 'dyn.xxxxx'

Ignore the dynamic UTI type hint to avoid extra log

---

SDWebImage/Core/SDWebImageManager.m
Tests/Tests/SDWebImageManagerTests.m

This fix #3395
Bug effects from SDWebImage 5.13.0~5.13.4

Avoid store again when origin disk cache hit during Thumbnail or Transformer with smaller pixel size

---

SDWebImage/Core/SDAnimatedImageView.m
SDWebImage/Core/SDImageCache.m
SDWebImage/Core/SDImageCacheDefine.m
SDWebImage/Core/SDImageIOAnimatedCoder.m
SDWebImage/Core/SDImageLoader.m
SDWebImage/Core/SDWebImageDownloader.m
SDWebImage/Core/SDWebImageDownloaderConfig.m
SDWebImage/Core/SDWebImageManager.m
SDWebImage/Core/UIView+WebCacheOperation.m
Tests/Tests/SDWebImageDownloaderTests.m

Continue and close #3385 from @timonus, since there are more changes need to be changed
This effect API called with multiple times, for some one-time setup and important check, the conformsToProtocol is remained

Replace conformsToProtocol call with appropriate respondsToSelector check to improve performance

---

SDWebImage/Core/SDAnimatedImagePlayer.m
SDWebImage/Core/SDImageCoderHelper.h
SDWebImage/Core/SDWebImageDownloaderOperation.m

This merge request fixes #3433
Use NSOperation dependency to solve this issue

Fix the iOS 12 crash because the underlyingQueue is nil

---

SDWebImage/Core/SDImageIOAnimatedCoder.m
SDWebImage/Core/SDImageIOCoder.m
Tests/Tests/SDImageCoderTests.m

This close #3396
See #3396 
We no longer use ImageIO to decode PDF, seems they don't maintain that kSDCGImageSourceRasterizationDPI
Copy the code from SDWebImagePDFCoder
TODO: 
1. Upgrade [SDWebImagePDFCoder](https://github.com/SDWebImage/SDWebImagePDFCoder) to don't repeat code again, which need bump dependency and just call `SDImageIOCoder`'s API instead
2. Upgrade test case to use iOS 16 simulators

Use CoreGraphics to decode PDF instead of ImageIO to solve iOS 16's issue

---

SDWebImage/Core/SDImageCache.m
SDWebImage/Core/SDWebImageDownloaderOperation.m
SDWebImage/Core/SDWebImageManager.m
SDWebImage/Core/UIView+WebCache.m

This fix #3438 fix #3437 fix #3433 (see comments)
That `token` is not locked by the synchonized, so it's not thread safe.
Move block before sending to the main queue
This can avoid some life cycle issue and increase performance

Fix the missing lock for callbackTokens which may cause thread-safe issue

---

SDWebImage/Core/SDAnimatedImagePlayer.m

This bug may cause the https://github.com/SDWebImage/SDWebImageSwiftUI/issues/243
Because the `startPlaying` will trigger the frame change callback **in sync**, which violence the async main UI callback gurantee by SwiftUI. And it's really strange only the poster frame is called in sync, others callback in async

The poster image should not trigger a frameChange callback

---

SDWebImage/Core/SDImageCache.m
SDWebImage/Core/SDImageCacheConfig.h
SDWebImage/Core/SDImageCacheConfig.m
Tests/Tests/SDImageCacheTests.m

This merge request fixes / refers to the following issues: close #3456 
This PR add concurrent queue config for advanced user. The default value (serial) does not changed.

Added `ioQueueAttributes` to use concurrent or control QoS for image cache internal IO Queue

---

SDWebImage/Core/SDImageIOAnimatedCoder.m
SDWebImage/Core/SDImageIOCoder.m
SDWebImage/Private/SDImageIOAnimatedCoderInternal.h
Tests/Tests/SDImageCoderTests.m

This merge request fixes / refers to the following issues: #3425 
The lazyDecode logic effect the static image as well. Should roll back and only check for animated image

Fix the iOS 15+ force-decode hack break Apple's HEIF and JPEG YUV420 optimization

---

SDWebImage.xcodeproj/project.pbxproj
SDWebImage/Core/SDCallbackQueue.h
SDWebImage/Core/SDCallbackQueue.m
SDWebImage/Core/SDImageCache.h
SDWebImage/Core/SDImageCache.m
SDWebImage/Core/SDImageCacheDefine.h
SDWebImage/Core/SDImageCachesManager.m
SDWebImage/Core/SDImageLoader.h
SDWebImage/Core/SDWebImageDefine.h
SDWebImage/Core/SDWebImageDefine.m
SDWebImage/Core/SDWebImageDownloaderOperation.m
SDWebImage/Core/SDWebImageManager.m
SDWebImage/Core/SDWebImagePrefetcher.h
SDWebImage/Core/SDWebImagePrefetcher.m
SDWebImage/include/SDWebImage/SDCallbackQueue.h
Tests/Tests/SDImageCacheTests.m
Tests/Tests/SDUtilsTests.m
Tests/Tests/SDWebImageTestCache.m
WebImage/SDWebImage.h

This close #3457 
For a `SDCallbackQueue`, you can specify `which dispatch queue` to callback, and `how block is invoke on queue`.
There are 3 policies:
+ SafeExecute: When the current queue is equal to callback queue, sync/async will just invoke `block` directly without dispatch. Else it use `dispatch_async`/`dispatch_sync` to dispatch block on queue. This is useful for UIKit rendering to ensure all blocks executed in the same runloop
+ Dispatch: Follow async/sync using the correspond `dispatch_async`/`dispatch_sync` to dispatch block on queue
+ Invoke: Ignore any async/sync and just directly invoke `block` in current queue (without `dispatch_async/dispatch_sync`)
1. `dispatch_main_async_safe` is deprecated. Use …

Added context option `callbackQueue` and `SDCallbackQueue` wrapper for advanced user to control which queue to callback

---

SDWebImage/Core/SDAnimatedImageRep.m
SDWebImage/Core/SDImageCoder.h
SDWebImage/Core/SDImageCoderHelper.m
SDWebImage/Core/SDImageCodersManager.m
SDWebImage/Core/SDImageFrame.h
SDWebImage/Core/SDImageFrame.m
SDWebImage/Core/SDImageIOAnimatedCoder.m
Tests/Tests/SDImageCoderTests.m

The exist API need wrap the frames into a new image and extract, consume RAM and CPU. Because it need to `wrap SDImageFrame array into UIImage, then unwrap again :(`

Added encodeWithFrames API for animation encoding in custom coder, better for usage

---

SDWebImage/Core/SDImageIOAnimatedCoder.m
SDWebImage/Core/SDImageIOCoder.m

Fix the issue the fallback logic of ImageIO Source should avoid passing any UTI hint

---

SDWebImage/Private/SDAsyncBlockOperation.m

This close #3467
Seems the ivar generarted here break the super class atomic synmatic

Avoid compiler generate the wrong property attribute with non-atomic

---

Examples/SDWebImage Demo/MasterViewController.m
SDWebImage/Core/SDAnimatedImagePlayer.m
SDWebImage/Core/SDImageCache.m
SDWebImage/Core/SDWebImageDownloader.m
SDWebImage/Core/SDWebImageDownloaderOperation.h
SDWebImage/Core/SDWebImageDownloaderOperation.m
Tests/Tests/SDTestCase.m
Tests/Tests/SDWebImageDownloaderTests.m
Tests/Tests/SDWebImageManagerTests.m
Tests/Tests/SDWebImagePrefetcherTests.m

fix #3475 
The downloader will now check and ignore a `transferedDataFinished` operation (which is callbacking its own completion), because it's not safe in multi-thread environment, create new network request instead
See #3475

Ensure the Downloader and DownloaderOperation callback the completion in atomic and never miss one

---

SDWebImage/Core/SDWebImageDownloaderOperation.m
SDWebImage/Private/SDAsyncBlockOperation.m
Tests/Tests/SDWebImageTestDownloadOperation.m

Use the correct way for subclassing NSOperation
fix #3275
Use the correct way for subclassing NSOperation

Try to fix the SDAsyncBlockOperation's race condition

---

SDWebImage/Core/SDAnimatedImage.m

The `initWithAnimatedImageData:` on coder protocol impl should handle the mutable data, so it's no need to copy here.
This close #3303

Remove the unused extra copy for `SDAnimatedImage` data initializer

---

SDWebImage/Core/SDWebImageDownloader.m
SDWebImage/Core/SDWebImageDownloaderOperation.m

Remove the wrong logic to modify queue priority when re-use operation
Seems that #3477 merged still cause the test case failure, like https://github.com/SDWebImage/SDWebImage/actions/runs/4104353673
Also remove the wrong logic to modify queue priority when re-use operation

Fix the atomic logic between downloader and operation again

---

SDWebImage/Core/SDAnimatedImagePlayer.m
SDWebImage/Core/SDWebImageDownloader.m
SDWebImage/Core/SDWebImageDownloaderOperation.m
Tests/Tests/SDAnimatedImageTest.m
Tests/Tests/SDImageCacheTests.m

The Objc BOOL is typedef to `char` in 32-bit OS. So it's better to use `YES/NO`
```c
#if (TARGET_OS_IPHONE && __LP64__)  ||  TARGET_OS_WATCH
#define OBJC_BOOL_IS_BOOL 1
typedef bool BOOL;
#else
#define OBJC_BOOL_IS_CHAR 1
typedef signed char BOOL; 
#endif
```
Though there are no logic error here in SDWebImage all codebase, it makes the code style clear.

Code garden to change Objc bool from true/false to YES/NO

---

SDWebImage/Core/SDWebImageDownloaderOperation.m
Tests/Tests/SDWebImageDownloaderTests.m

This fix a bug in #3493 , close #3493

Fix the issue when multiple request for same url failed, the completedBlock will callback more times

---

SDWebImage/Core/SDImageIOCoder.m
SDWebImage/Core/UIImage+Transform.m

refactor:use SDGraphicsImageRenderer to render image instead of SDGraphicsBeginImageContextWithOptions/SDGraphicsEndImageContext directly.
as SDGraphicsImageRenderer will use UIGraphicsImageRenderer a better performance api for iOS 10 later
...

refactor:use SDGraphicsImageRenderer

---

SDWebImage/Core/SDCallbackQueue.h
SDWebImage/Core/SDCallbackQueue.m

This may cause the wrong lifecycle for block (earily release), from user report:

Fix the wrong declaration of SDCallbackQueue's block, should be escaping to match GCD block

---

SDWebImage/Core/SDImageCache.m

Protect the disk operation when input key is nil

---

SDWebImage/Core/SDCallbackQueue.m

This close #3512 
Guessing the queue ARC lifecycle is wrong during some of compiler optimization

Try to solve the strange dispatch group crash in SDSafeExecute by removing inline

---

SDWebImage/Core/SDImageCache.m
SDWebImage/Core/SDWebImageDefine.m

This PR add some logic to handle the special of `SDAnimatedImage` for exist util logic
+ Change scale (need special call)
+ Check frame count (should not use `sd_isAnimatedImage`)

Update the implementation `SDScaledImageForScaleFactor` to support SDAnimatedImage

---

Examples/SDWebImage Demo/DetailViewController.m
SDWebImage/Core/SDImageCacheDefine.m
SDWebImage/Core/SDImageCoder.h
SDWebImage/Core/SDImageCoder.m
SDWebImage/Core/SDImageIOAnimatedCoder.m
SDWebImage/Core/SDWebImageDefine.h
SDWebImage/Core/SDWebImageDefine.m

This is the solution for #3536
The exist SDWebImageScaleDownLargeImages translate to new option instead

Introduce the automatically calculation of thumbnail (include animated/static image) using `SDImageCoderDecodeScaleDownLimitBytes`

---

SDWebImage/Core/SDImageCoder.h
SDWebImage/Core/SDImageCoderHelper.h
SDWebImage/Core/SDImageCoderHelper.m
SDWebImage/Core/SDImageIOAnimatedCoder.m

Also, expose the limit bytes calculation utils method
This fix the test case `test13ThatScaleDownLargeImageUseThumbnailDecoding`

Fix macOS bug that SDImageCoderDecodeScaleDownLimitBytes still use the AnimatedImageRep and beyond the byte limit

---

Examples/SDWebImage Demo/DetailViewController.m
SDWebImage/Core/SDImageCache.h
SDWebImage/Core/SDImageCache.m
SDWebImage/Core/SDImageCacheDefine.m
SDWebImage/Core/SDImageCoderHelper.h
SDWebImage/Core/SDImageCoderHelper.m
SDWebImage/Core/SDImageGraphics.m
SDWebImage/Core/SDImageLoader.m
SDWebImage/Core/SDWebImageDefine.h
SDWebImage/Core/SDWebImageDefine.m
SDWebImage/Core/SDWebImageDownloader.h
SDWebImage/Core/SDWebImageDownloader.m
SDWebImage/Core/SDWebImageDownloaderOperation.m
SDWebImage/Core/UIImage+ForceDecode.h
SDWebImage/Core/UIImage+ForceDecode.m
SDWebImage/Core/UIImage+Transform.m
SDWebImage/Private/SDDeviceHelper.h
SDWebImage/Private/SDDeviceHelper.m
Tests/Tests/SDImageCoderTests.m
Tests/Tests/SDUtilsTests.m
Tests/Tests/SDWebImageManagerTests.m

This close https://github.com/SDWebImage/SDWebImage/issues/3417
This commit: ff6b3b9bb59613d1acde21258d45bfe83bd44fab cause to not force decode on `Non-ImageIO` created CGImage. In theory it's correct because like libwebp-created CGImage has already bitmap buffer in RAM.
However, this change has bad effect on final RAM usage. Because of https://github.com/path/FastImageCache#byte-alignment
When some bad coder (The SDWebImageWebPCoder in that example), does not handle the byte alignment correctly, CoreAnimation will try to copy the bitmap buffer when rendering, cause `2 * bitmap buffer` usage, instead of 1.
You can use Xcode's `Color Copied Image` to find this behavior.
See: 
1. SD itself provide the helper function to easily …

Refactory the logic to handle force decode logic to avoid CA copy frame buffer, introduce SDImageForceDecodePolicy detailed control

---

SDWebImage/Core/SDImageCoderHelper.m
Tests/Tests/SDImageCoderTests.m

This merge request fixes: [#3564]
It's a patch of this PR [#3321 ](https://github.com/SDWebImage/SDWebImage/pull/3321)
In File SDImageCoderHelper.m + 717
```
destTile.size.height += kDestSeemOverlap;
```
use ```kDestSeemOverlap``` to avoid the loss of precision. but when the original height can not be evenly divided by the target height, use the code below to avoid the content missing.
``` SDImageCoderHelper.m line: 722 -727
if( y == iterations - 1 && remainder ) {
float dify = destTile.size.height;
destTile.size.height = CGImageGetHeight( sourceTileImageRef ) * imageScale;
dify -= destTile.size.height;
destTile.origin.y = MIN(0, destTile.origin.y + dify);
}
```
But in the above code snippet,``` destTile.size. height ``` is not added with kDestSeemOverlap. so It may lead to one-pixel …

Fix bug #3564

---

SDWebImage/Core/SDAnimatedImage.h
SDWebImage/Core/SDAnimatedImageRep.h
SDWebImage/Core/SDAnimatedImageRep.m
SDWebImage/Core/UIImage+MultiFormat.h
SDWebImage/Core/UIImage+MultiFormat.m
Tests/Tests/SDImageCoderTests.m

This can avoid extra re-encoding (slow) for some cases if you need compressed image data, on macOS AppKit
Used in AVIFQuickLook or some other cases

Expose the data and format when SDAnimatedImageRep created with APNG/GIF/WebP/HEICS

---

SDWebImage/Core/SDWebImageDownloader.m
SDWebImage/Core/SDWebImageDownloaderOperation.m

fix redundant url requests #3571 
After SDWebImageDownloaderOperation finishes downloading and processing all the current tokens, check if there are any new tokens added during the previous processing. If there are, continue to perform decoding tasks for the newly added tokens until all tasks are completed, then execute [self done].

Fix redundant requests for the same url during decoding time

---

SDWebImage/Core/SDImageCoderHelper.h
SDWebImage/Core/SDImageCoderHelper.m
Tests/Tests/SDImageTransformerTests.m

This fix the issue I found in https://github.com/SDWebImage/SDWebImageAVIFCoder
The created 16-bit depth CGImage will fail on this. vImage need to handle the `pixel format` one by one, let's add the dummy code.....
Test Result :
```
<CGImage 0x100645080> (DP)
<<CGColorSpace 0x600002603900> (kCGColorSpaceICCBased; kCGColorSpaceModelRGB; Rec. ITU-R BT.2100 PQ)>
width = 4500, height = 3000, bpc = 16, bpp = 48, row bytes = 27000 
kCGImageAlphaNone | kCGImageByteOrder16Little  | kCGImagePixelFormatPacked 
is mask? No, has masking color? No, has soft mask? No, has matte? No, should interpolate? No
Printing description of imageRef:
<CGImage 0x100c0c460> (IP)
<<CGColorSpace 0x600002603900> (kCGColorSpaceICCBased; …
```

Fix the CGImageCreateScaled to support 16/32 bit depth CGImage (RGB161616) and always preserve pixel format info

---

SDWebImage.xcodeproj/project.pbxproj
SDWebImage/Core/NSButton+WebCache.m
SDWebImage/Core/UIButton+WebCache.h
SDWebImage/Core/UIButton+WebCache.m
SDWebImage/Core/UIImageView+HighlightedWebCache.h
SDWebImage/Core/UIImageView+HighlightedWebCache.m
SDWebImage/Core/UIImageView+WebCache.h
SDWebImage/Core/UIImageView+WebCache.m
SDWebImage/Core/UIView+WebCache.h
SDWebImage/Core/UIView+WebCache.m
SDWebImage/Core/UIView+WebCacheState.h
SDWebImage/Core/UIView+WebCacheState.m
SDWebImage/Private/SDInternalMacros.h
SDWebImage/include/SDWebImage/UIView+WebCacheState.h
Tests/Tests/SDWebCacheCategoriesTests.m
WebImage/SDWebImage.h

Key idea:
1. Image Loading pipeline is based on `operation key`, when start/cancel it always need operation key
2. Stateful view has multiple operation key for different image property, we can use KeyPath as the hint to generate operation key
3. To make exists API compatible, we do not change much, however, in 6.0 we may do refactory and store all the loadState/operation/result into the single object, instead of 3
This is the re-new of #2790 
This close #2701
This is the base need before #3569 been merged. Must merge this first then rebase that branch

Add better support for stateful view (UIButton) for image URL/progres s state management

---

SDWebImage/Core/SDWebImageDefine.h
SDWebImage/Core/UIView+WebCache.m
SDWebImage/Core/UIView+WebCacheOperation.m
Tests/Tests/SDWebCacheCategoriesTests.m

Added `SDWebImageAvoidAutoCancelImage` to avoid cancel loading image requests for the same operation key

---

README.md
SDWebImage.xcodeproj/project.pbxproj
Scripts/build-frameworks.sh
Scripts/create-xcframework.sh

Also, move the scripts from xcproj into the actual Scripts folder

Added the visionOS support for "Build XCFramework" script target

---

SDWebImage/Core/SDImageCache.m

Fix one warning because local variable shadows the variable outside of block

---

Package.swift
README.md
SDWebImage.xcodeproj/project.pbxproj
SDWebImage/Resources/PrivacyInfo.xcprivacy
SDWebImageMapKit/Resources/PrivacyInfo.xcprivacy
WebImage/PrivacyInfo.xcprivacy

This close #3550 
Note: CocoaPods does not has this feature currently
See: https://github.com/CocoaPods/CocoaPods/issues/10325

Added xcprivacy to framework target and SPM

---

SDWebImage/Private/SDDisplayLink.m

The first callback should be trigger in next runloop when calling `start`, but not callback in sync.
This match iOS/tvOS/macOS/visionOS behavior, only watchOS who use `NSTimer` contains issues...

Fix the SDDisplayLink on watchOS does not behave like other platform

---

SDWebImage/Core/SDAnimatedImage.m
SDWebImage/Core/UIImage+MultiFormat.m

This close #3616
Though I don't think this is good solution. Actually for user who understand what this API do, can manually check and use `SDImageCodersManager` to call the proper code instead...

Update the convenient API for case when user encode the format the same as image format, provide better quick return

---

SDWebImage/Core/SDAnimatedImage.h
SDWebImage/Core/SDAnimatedImage.m

See: #3625 discussion abour the old behavior
This previously will only return nil for static image, so this may be a behavior changes. Some user will forget to check the nil for SDAnimatedImage. So we make this more like the `YYImage` like object which return non-nil for static image.
For example, SDAnimatedImageView loading url will cache the `SDAnimatedImage` instead of `UIImage`
CC @hstdt

SDAnimatedImage now supports static image like JPEG data

---

SDWebImage/Core/SDImageIOAnimatedCoder.m
SDWebImage/Core/UIImage+Transform.m

This use the runtime detection instead of available check, more stable
When we detect the ImageIO is buggy, we will change the correct alpha info with non-premultiplied
This is the ultimate solution for Apple's bug #3605
1. Use a sample (only 1x1 pixel), decode its pixel values at runtime. 
2. If the R, G, and B values of this sample are not equal to 50, consider ImageIO to be in Buggy mode.
3. In Buggy mode, all instances where CGImageGetUTType() == UTTypePNG, and CGImageGetAlphaInfo == AlphaLast or  AlphaFirst, are forcefully treated as AlphaPremultipliedLast or AlphaPremultipliedFirst.
4. Optionally, an @available iOS 17 check can be added at the outermost level.

Introduce the hacky workaround for iOS 17 ImageIO indexed color png decode (Apple's bug)

---

SDWebImage/Private/SDDisplayLink.m
Tests/Tests/SDUtilsTests.m

This visually fix visionOS (90Hz) animated image duration
We don't use Media Time because it's not correct when lag or VSync not callback in current runloop
Instead, we use the `next targetTimestamp - previous targetTimestamp` to get the actual time during callbacks
Testing the Vision Simulator from Xcode 15.1, works better than current version (Current version will play large GIF in slow because the decoding of GIF is slow, and out-of-sync after 10 frames)
This close #3579 as well

Use the new solution for CADisplayLink duration calculation and fix 90Hz/120Hz display (iPhone Pro or Vision Pro)

---

README.md
SDWebImage.podspec

Using the resource bundle syntax
See: https://github.com/CocoaPods/CocoaPods/issues/10325
Should work when using CocoaPods with `use_frameworks! :linkage => what_ever`

Added xcprivacy manifest to CocoaPods

---

SDWebImage/Core/UIView+WebCacheOperation.h
SDWebImage/Core/UIView+WebCacheOperation.m

This close #3647 
This close #3646
When `nil` operation key provided, it should always translated into `NSClassFromString(self.class)` for history compatible behavior.

Fix the issue when using the `sd_cancelCurrentImageLoad` on non-stateful view (like UIImageView.image)

---

SDWebImage/Core/SDImageIOAnimatedCoder.m

This is a stupid DEBUG macro (which is intend to hide the NSLog)
close #3658 
The Log will using new macro to avoid this stupid issue again

Fix that PNG indexed color fix does not enable on Release Build configuration

---

SDWebImage/Core/SDImageCache.m
SDWebImage/Core/SDWebImageManager.m
Tests/Tests/SDWebImageManagerTests.m

This close #3656 
In history commits I do a hack which breaks's disk -> memory cache sync behavior for thumbnail. https://github.com/SDWebImage/SDWebImage/commit/e7e9268a7e9c2f1157f1cea1b88465bc1589b4f9
It's not correct. We should use another more better way for workaround.
The caller should not passes the `thumbnail` related context when querying the actual thumbnail key (calculate twice)

Fix the behavior that query thumbnail from full size data does not sync back the thumbnail image into memory cache

---

SDWebImage/Core/SDImageCache.h
SDWebImage/Core/SDImageCache.m

In #3657 I added an assert here.
But I think this may cause some behavior changes. Currently remove this to keep old patch version compatible

Temp remove the assert when thumbnail cache key used with thumbnail context , this may be changed later

---

SDWebImage/Core/SDImageCache.m
SDWebImage/Core/SDImageIOAnimatedCoder.m
SDWebImage/Core/UIImage+Transform.m
SDWebImage/Private/SDInternalMacros.h
SDWebImage/Private/SDInternalMacros.m

Using the subsystem (`com.hackemist.SDWebImage` for better filter
Need the runtime version check for now (will remove in 6.x)

Using os_log for our all log to replace the NSLog

---

SDWebImage/Core/NSData+ImageContentType.m

…e converting NSData to SDImageFormat
The function `+ (SDImageFormat)sd_imageFormatForImageData:(nullable NSData *)data` misses two break keyword in case  `PDF` and `SVG`
...

add missing break keyword while converting NSData to SDImageFormat

---

.github/workflows/CI.yml

It seems `macos-14` runner is arm64 based, not Intel.

[github action] Bumped to macos-14 and remove the unused visionOS download toolchain steps

---

SDWebImage/Core/SDWebImageDefine.h
SDWebImage/Core/UIView+WebCache.m

This can solve the simple case when people want to do another transition inside completedBlock and mass-up the UI status
We may supports the `pausable/cancellable` transition, but this relys on new API from UIKit:
https://stackoverflow.com/questions/554997/cancel-a-uiview-animation
For now, the `transition` is never cancellable once submitted, so this `wait transition finished` is used here.
This close #3674

Added `SDWebImageWaitTransition` to wait for transition finished and then callback `completedBlock`

---

Tests/Tests/SDImageCoderTests.m
Tests/Tests/SDWebImageDownloaderTests.m

Seems using `/dev/null` is not safe to always get invalid image data

Fix the unit test `test31ThatMultipleRequestForSameURLFailedCallback`

---

SDWebImage/Core/SDCallbackQueue.m
SDWebImage/Core/SDDiskCache.h
SDWebImage/Core/SDImageTransformer.h
SDWebImage/Core/SDWebImageCacheKeyFilter.h
SDWebImage/Core/SDWebImageCacheSerializer.h
SDWebImage/Core/SDWebImageDownloaderDecryptor.h
SDWebImage/Core/SDWebImageDownloaderRequestModifier.h
SDWebImage/Core/SDWebImageDownloaderResponseModifier.h
SDWebImage/Core/SDWebImageOptionsProcessor.h

1. Mark `SDWebImageCacheKeyFilter` default `init` and `new` initializer as `unavailable` to prevent unexpected behavior
2. add missing default case of `SDCallbackQueue`  `sync` and `async` function to avoid future unexpected behavior

mark `SDWebImageCacheKeyFilter` default initializer unavailable &  add missing default case of `SDCallbackQueue` sync/async function

---

SDWebImage/Core/UIView+WebCache.m
Tests/Tests/SDCategoriesTests.m
Tests/Tests/SDWebCacheCategoriesTests.m

* [] I have updated this branch with the latest master to avoid conflicts (via merge from master or rebase)
* [] I have added the required tests to prove the fix/feature I am adding
* [] I have updated the documentation (if necessary)
if url is NSString and shouldUseWeakMemoryCache is true, method [cacheKeyForURL:context] will crash.
...

url is kind of NSString and shouldUseWeakMemoryCache is YES, APP will crash.

---

SDWebImage/Core/SDDiskCache.m
SDWebImage/Core/SDImageCacheConfig.h
SDWebImage/Core/SDImageCacheConfig.m
Tests/Tests/SDImageCacheTests.m
Tests/Tests/SDWebImageTestCache.m

1. repalce ``@selector(enumeratorAtURL:)`` with ``@selector(enumeratorAtURL:)``
2. replace ``SDImageCacheConfig.ioQueueAttributes`` from ``DISPATCH_QUEUE_SERIAL`` to ``DISPATCH_QUEUE_SERIAL_WITH_AUTORELEASE_POOL`` >= ``iOS 10``
...

Replace NSFileManager.enumeratorAtPath with enumeratorAtURL for performance and RAM saving

---

SDWebImage/Core/SDAnimatedImage.m
SDWebImage/Core/SDAnimatedImageView.m
SDWebImage/Core/SDWebImageDefine.m
SDWebImage/Core/UIImage+Metadata.h
Tests/Tests/SDAnimatedImageTest.m
Tests/Tests/SDWebCacheCategoriesTests.m

This merge request fixes / refers to the following issues: close #3706 
For now, I still prefer to keep the idea that `SDAnimatedImage` can be created with non-static format like JPEG.
Why ?  Because even without the changes in #3626, you can still do hack using `NSCoder` to create a JPEG `SDAnimatedImage` object, before 5.19.0 version...😂 (See the line of code)
And this, match the behavior like `subclassing` (For the same input param, the parent class `UIImage` can init successfully, but why a subclass return nil ?)
And this matches the YYImage's behavior, it's more easy to keep sync of that https://github.com/SDWebImage/SDWebImageYYPlugin
CC @LeoTheCatMeow

Fix some regression when SDAnimatedImage created with static format like JPEG

---

.github/workflows/CI.yml
Tests/SDWebImage Tests.xcodeproj/xcshareddata/xcschemes/Tests Mac.xcscheme
Tests/SDWebImage Tests.xcodeproj/xcshareddata/xcschemes/Tests TV.xcscheme
Tests/SDWebImage Tests.xcodeproj/xcshareddata/xcschemes/Tests Vision.xcscheme
Tests/SDWebImage Tests.xcodeproj/xcshareddata/xcschemes/Tests iOS.xcscheme
Tests/Tests/SDImageCoderTests.m
Tests/Tests/SDTestCase.h
Tests/Tests/SDTestCase.m
Tests/Tests/SDUtilsTests.m

This is because GitHub CI bump macOS from 14.2.1 to 14.4.1, which contains bug

Try to fix the GitHub CI again because of macOS 14.4.1

---

SDWebImage/Core/SDImageCoderHelper.m
Tests/Tests/SDImageCoderTests.m

This was found during the test case `testSDGraphicsImageRenderer`
```
Draw Color ColorSpace: <CGColor 0x6000027c5620> [<CGColorSpace 0x6000027c48a0> (kCGColorSpaceICCBased; kCGColorSpaceModelRGB; sRGB IEC61966-2.1)] ( 1 0 0 1 )
Test Color ColorSpace: <CGColor 0x6000027c5980> [<CGColorSpace 0x6000027c48a0> (kCGColorSpaceICCBased; kCGColorSpaceModelRGB; sRGB IEC61966-2.1)] ( 0.978015 0.00459104 0.00225032 1 )
```
Also, fix the unit test on macOS.

Fix that `colorSpaceGetDeviceRGB` cache the color space even when active display changed

---

SDWebImage/Core/SDWebImageDownloader.h
SDWebImage/Core/SDWebImageDownloader.m
SDWebImage/Core/SDWebImageDownloaderOperation.h
SDWebImage/Core/SDWebImageDownloaderOperation.m

This merge request fixes / refers to the following issues: None
as clang [docs](https://clang.llvm.org/docs/AttributeReference.html#availability) said:
> macos
Apple’s macOS operating system. The minimum deployment target is specified as part of the -target *arch*-apple-macos*version* command line argument. Alternatively, it can be specified by the -mtargetos=macos*version* command-line argument. **macosx is supported for backward-compatibility reasons, but it is deprecated**.
I found the commit about this based on https://github.com/llvm/llvm-project/commit/ccf25bbf3fdf2905bba9a3b199d5367e9c88db43
the version of llvm is [llvmorg-3.9.0](https://github.com/llvm/llvm-project/releases/tag/llvmorg-3.9.0)/Apple LLVM Version 8.0.0(Xcode 8.0 Toolchain: …

chore: use macos platform name with-in API_AVAILABLE macro

---

SDWebImage/Core/SDAnimatedImage.h
SDWebImage/Core/SDAnimatedImageView.h

This close #3729 
UIImage subclass should be thread-safe
UIImageView subclass should be on MainActor only
CC @LeoTheCatMeow

Use the new macro from Swift compiler and SDK to mark the UIImage/UIImageView subclass matching what they designed to be

---

SDWebImage/Core/SDImageHEICCoder.m
SDWebImage/Core/SDImageIOAnimatedCoder.m

Also, some little behavior changes, the `format` arg in animated coder does not help for anything.
This close #3726

Fix our HEIC coder to encode `timed image sequences` instead of `non-timed image gallery` for HEIC encoding

---

SDWebImage/Core/SDGraphicsImageRenderer.m

This default value is useless and may cause misunderstanding.
Apple's own `UIGraphicsImageRendererFormat` does not use this as default value !

Remove the unused code for iOS 9- polyfill

---

SDWebImage/Core/SDImageCoderHelper.h
SDWebImage/Core/SDImageCoderHelper.m
SDWebImage/Core/SDImageIOAnimatedCoder.m
Tests/Tests/SDAnimatedImageTest.m
Tests/Tests/SDImageCoderTests.m
Tests/Tests/SDUtilsTests.m

This effect the thumbnail decoding (which produce non-lazy CGImage, but accidentally been force decoded)

Use the better way to detect lazy/non-lazy CGImage. Only do force decoding for lazy image (avoid thumbnail image been decoded twice)

---

SDWebImage/Core/SDImageIOAnimatedCoder.m
Tests/Tests/SDImageCoderTests.m

This can close #3742 
and also workaround that strange JFIF image bug in #3594

Fix the thumbnail decoding on JPEG which contains EXIF orientation, use the new way to workaround JFIF bug

---

SDWebImage/Core/SDDiskCache.m

if filePath is nil or (null)，framework will crash with this：
Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '*** -[_NSPlaceholderData initWithContentsOfFile:options:maxLength:error:]: nil file argument'
at - (NSData *)dataForKey:(NSString *)key in the file Core/SDDiskCache.m

Fix the crash when some special urls cause the cache path return nil and crash

---

SDWebImage/Core/SDDiskCache.m
Tests/Tests/SDImageCacheTests.m
Tests/Tests/SDImageCoderTests.m

Use the more robust way to calculate cache path, still keep the exists behavior
See: #3740 root case

Fix the issue that some URL which has percent-encoding with \0 will cause nil cache path

---

.github/workflows/CD.yml
.github/workflows/CI.yml

Due to https://github.com/actions/runner-images/issues/10559 , should download visionOS SDK before running workflow.

build: download visionOS SDK before CI/CD

---

SDWebImage/Core/SDImageTransformer.h
SDWebImage/Core/SDImageTransformer.m
SDWebImage/Core/UIImage+Transform.h
SDWebImage/Core/UIImage+Transform.m
Tests/Tests/SDImageTransformerTests.m

1. Also works for CIFilter variant
2. Added blend mode to transformer API as well
This close #3748

[Behavior changes] Add blend mode to UIImage+Transform tint color API, default blend mode changed to sourceIn

---

SDWebImage/Core/SDDiskCache.m
SDWebImage/Core/SDImageCacheConfig.h
SDWebImage/Core/SDImageCacheConfig.m
Tests/Tests/SDWebImageTestCache.m

`NSFileManager` does not automatically increment access date when reading files off disk, which means that use of `SDImageCacheConfigExpireTypeAccessDate` is effectively identical to using `SDImageCacheConfigExpireTypeCreationDate`. This doesn't seem like the correct behavior on SDWebImage's part, and it isn't what's documented [here](https://github.com/SDWebImage/SDWebImage/blob/d68b92db8557f1aed608106e5d6ae8826ce3afac/SDWebImage/Core/SDImageCacheConfig.h#L15). This PR makes it so that SDWebImage adjusts the file content access date when files are read off disk to address the issue.
I've also added a commit that updates the default cache behavior to `SDImageCacheConfigExpireTypeAccessDate` since I believe that's what's commonly expected. People generally want cache purging by time-of-use …

Fix issue causing disk cache eviction LRU to not function as expected.

---

SDWebImage/Core/SDAnimatedImage.m

This merge request fixes: 
`sd_imageFormat` returns nil when used on `SDAnimatedImage` to which static image were loaded.
When a static image is loaded into `SDAnimatedImage`, the `sd_imageFormat` remains unset. As a result, the associated object on the underlying `UIImage` is not present. This value is typically assigned by decoders; for instance, `SDImageIOCoder` does so [here](https://github.com/SDWebImage/SDWebImage/blob/0b10fcb54484b618a53386670bff38176a203290/SDWebImage/Core/SDImageIOCoder.m#L217). However, with `SDAnimatedImage`, the correct format is returned only if the `animatedImageData` is included. 
I’m uncertain if my solution is accurate (I’ve tested it, but I’m unsure if it’s the right approach). I’ve opened this PR to initiate a discussion on how to properly address that …

Fix `sd_imageFormat` sometimes returns `undefined` 

---

.github/workflows/CI.yml
SDWebImage/Core/SDImageCache.m
Tests/Tests/SDAnimatedImageTest.m
Tests/Tests/SDTestCase.m
Tests/Tests/SDWebImageManagerTests.m

This fix the regression because of #3523
> At that time, user query 100 image with the same URL at the same time
> Because NSURLSession only callback with 10 request completion once, we will query the disk cache in async concurrent and do 10x time more "real decoding and cache written operation" than user expected. This wastes CPU and RAM.
To optimize this case, we add a `second memory cache check` during the async disk cache query logic, but this logic should follows the same requirement as the `first memory cache check`
I copy the `// First check the in-memory cache...` comment 3 times to mention that these code should follows the same logic

Fix the issue that previous optimization for special case (multiple same URL in prefetcher list) breaks the `queryCacheType` option sematic

---

SDWebImage/Core/SDCallbackQueue.h
SDWebImage/Core/SDCallbackQueue.m
Tests/Tests/SDUtilsTests.m

This is the best practice for UI related code
After discussion in #3766 
Actually this `SafeAsyncMainQueue` does not do anything useful. UIKit always check `MainThread` , but not `MainQueue`. So, we should remove this policy and always use `SafeAsyncMainThread` instead
This is also what Kingfisher or ReactNative do in their latest release, to support UICollectionViewDiffableDataSource

Change the default callback queue policy to SafeAsyncMainThread, don't need main queue check at all

---

README.md
SDWebImage/Core/SDImageCoder.h
SDWebImage/Core/SDImageCoder.m
SDWebImage/Core/SDImageCoderHelper.h
SDWebImage/Core/SDImageIOAnimatedCoder.m
SDWebImage/Core/SDImageIOCoder.m
SDWebImage/Private/SDImageIOAnimatedCoderInternal.h
Tests/Tests/SDImageCoderTests.m

This just forward the options, no extra logic, really simple changes
To test Apple ImageIO HDR encoding, you need iOS 18 and macOS 15 device (not simulator)

Supports HDR encoding on Apple ImageIO coder
